import type { Trilha } from '../types';

export const COMECE_POR_AQUI: Trilha = {
  id: 'comece',
  titulo: 'Comece por aqui',
  subtitulo: 'Seus primeiros dias no Frider Andrade',
  icone: 'Rocket',
  cor: '#7048E8',
  publico: 'Todo mundo que entra — advogado, estagiário, back office.',
  aulas: [
    {
      id: 'como-usar',
      videoPlanejado: true,
      titulo: 'Comece por aqui: como usar esta Academia',
      resumo: 'O mapa da biblioteca, o que é obrigatório e em que ordem fazer.',
      minutos: 5,
      video: {
        fonte: 'url',
        url: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/como-usar.mp4',
        legendas: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/como-usar.vtt',
        duracao: '3 min',
      },
      manual: [
        '## O que é a Academia',
        '',
        'É o treinamento do escritório, dentro do próprio hub. Cada aula tem **vídeo** e **manual escrito** — o manual não é resumo do vídeo, é o procedimento completo. Dá para aprender só lendo, e dá para voltar depois, no meio de um caso, para conferir um passo.',
        '',
        '## As 8 trilhas',
        '',
        '1. **Comece por aqui** — quem somos, como o escritório funciona, regras, ferramentas e sua primeira semana.',
        '2. **O Hub por dentro** — módulo a módulo, o que fazer em cada tela.',
        '3. **Claude: peças, pesquisa e revisão** — a ferramenta que produz e as regras que impedem ela de estragar a peça.',
        '4. **Prazos e controladoria** — a obrigação número um do regimento.',
        '5. **A fase judicial ponta a ponta** — do protocolo ao dinheiro na conta do cliente.',
        '6. **As teses do escritório** — RMC, RCC, contrato digital e as demais verticais.',
        '7. **Cliente: atendimento e comunicação** — para ele, você é o escritório inteiro.',
        '8. **Ética, sigilo e segurança** — o que não se negocia.',
        '',
        '## A ordem da primeira semana',
        '',
        'Cinco trilhas são obrigatórias, uma por dia:',
        '',
        '- **Dia 1** — Comece por aqui.',
        '- **Dia 2** — O Hub por dentro.',
        '- **Dia 3** — As teses do escritório.',
        '- **Dia 4** — Claude: peças, pesquisa e revisão.',
        '- **Dia 5** — Prazos e controladoria.',
        '',
        'Cliente e Ética entram na segunda semana, mas quem já vai atender no primeiro dia faz **Cliente** antes.',
        '',
        '## Como cada aula funciona',
        '',
        '![A Academia: as trilhas à esquerda, a aula aberta à direita, o progresso e a busca no topo](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/academia-visao-geral.png)',
        '',
        '- **Vídeo** no topo, quando já existe. Aula sem vídeo tem o manual completo, que vale sozinho.',
        '- **Manual escrito** — é o procedimento. É ele que se consulta depois.',
        '- **Você consegue fazer sozinho** — a lista do que você tem que conseguir executar ao fim da aula. Se não conseguir um item, volte à aula ou pergunte.',
        '- **Marcar como concluída** — o progresso é seu, fica salvo neste navegador.',
        '- **Busca** — no topo da tela, procura dentro do texto de todas as aulas de uma vez.',
        '',
        '## Ajuda x Academia',
        '',
        'A **Ajuda** é um chat que responde "onde eu clico". A **Academia** responde "como se faz e por quê". Use as duas — e, quando a dúvida for de tese ou de estratégia, pergunte a uma pessoa.',
      ].join('\n'),
      checklist: [
        'Sei quais são as 5 trilhas obrigatórias e em que ordem fazer.',
        'Sei que o manual escrito é o procedimento, não um resumo do vídeo.',
      ],
      promptVideo: [
        'Gere o vídeo de abertura da Academia do escritório Frider Andrade | Advogados, de 3 a 5 minutos.',
        '',
        'PÚBLICO: pessoa no primeiro dia, abrindo a Academia pela primeira vez.',
        'TOM: acolhedor e organizado, de quem entrega um mapa. Português do Brasil. Trate a pessoa por "você".',
        '',
        'ROTEIRO:',
        '1. O que é a Academia: o treinamento do escritório dentro do próprio hub, com vídeo e manual escrito em cada aula.',
        '   Deixe claro que o manual não é resumo do vídeo, é o procedimento completo, e que serve para consultar depois,',
        '   no meio de um caso.',
        '2. Apresente as 8 trilhas, uma frase cada, na ordem: Comece por aqui, O Hub por dentro, Claude, Prazos e',
        '   controladoria, A fase judicial ponta a ponta, As teses do escritório, Cliente, e Ética sigilo e segurança.',
        '3. A ordem da primeira semana, dia a dia: dia 1 cultura, dia 2 hub, dia 3 tese, dia 4 Claude, dia 5 prazo.',
        '   Diga que quem já vai atender cliente no primeiro dia adianta a trilha de Cliente.',
        '4. Como cada aula funciona: vídeo, manual escrito, a lista "você consegue fazer sozinho", marcar como concluída',
        '   e a busca que procura dentro do texto de todas as aulas.',
        '5. Feche com a diferença entre Ajuda e Academia: a Ajuda responde onde eu clico, a Academia responde como se faz',
        '   e por quê. E que dúvida de tese ou estratégia se pergunta a uma pessoa.',
        '',
        'NÃO FAÇA: listar nomes de pessoas do escritório.',
      ].join('\n'),
    },
    {
      id: 'quem-somos',
      videoPlanejado: true,
      titulo: 'Quem somos: missão, visão e valores',
      resumo: 'Para quem o escritório trabalha, o que ele persegue e o que ele não aceita.',
      minutos: 8,
      manual: [
        '## Nossa missão',
        '',
        'Ser a voz e a força de quem mais precisa, garantindo que a justiça chegue aos menos favorecidos.',
        '',
        'Existimos para lutar por quem o Estado esquece, por quem é explorado por grandes instituições e, especialmente, pelos **idosos e aposentados**. O que nos diferencia é o atendimento humanizado e a transparência total durante todo o processo.',
        '',
        '> Na prática: a cliente do outro lado da linha tem 74 anos, recebe um salário mínimo e teve R$ 68 descontados todo mês por cinco anos sem nunca ter pedido um cartão. Ela é o motivo de tudo aqui.',
        '',
        '## Nossa visão',
        '',
        'Faturamento previsível e saudável, sede consolidada e atuação em todo o território brasileiro. Uma equipe enxuta que gera grandes resultados, onde quem entra tem caminho aberto para virar sócio.',
        '',
        'Queremos que o cliente sinta **segurança, profissionalismo e requinte** em cada contato com a marca.',
        '',
        '## Os 15 valores',
        '',
        'Honestidade · Transparência · Eficiência · Segurança · Vontade · Felicidade · Diálogo · Cortesia · Humanidade · Confiança · Curiosidade · Determinação · Profissionalismo · Resultados · Força.',
        '',
        '### Os 5 que são o coração da cultura',
        '',
        '1. **Eficiência** — a melhor e mais rápida solução, sempre.',
        '2. **Transparência** — a verdade do processo dita ao cliente, sem maquiagem.',
        '3. **Vontade** — acordar querendo crescer.',
        '4. **Segurança** — saber o que está fazendo, e o cliente sentir isso.',
        '5. **Felicidade** — um lugar onde é bom trabalhar, com conquista celebrada.',
        '',
        '## Como NÃO vivemos nossos valores',
        '',
        '- **Trabalhar desmotivado** — sem meta, sem organização, sem entusiasmo.',
        '- **Agir "na sorte"** — apostar em vez de estudar. Cada ação aqui nasce de estudo e planejamento.',
        '- **Omitir informação** — deixar o cliente sem notícia, ou dourar a pílula de uma decisão ruim.',
        '',
        '## Nossas vantagens competitivas',
        '',
        '- **Tecnologia e estudo constante** — é o que nos faz chegar mais rápido e tirar mais valor de cada condenação.',
        '- **Atendimento individualizado com padronização** — o processo é padronizado, a dedicação ao caso é única.',
        '- **Desenvolvimento contínuo** — cursos, mentorias e conversa. Ninguém fica parado.',
        '- **Humildade e ambição juntas** — humildade para ver onde estamos, ambição para saber aonde vamos.',
        '',
        '## Três palavras',
        '',
        '**Justiça** (missão) · **Crescimento** (visão) · **Excelência** (valores).',
      ].join('\n'),
      checklist: [
        'Sei dizer, em uma frase, para quem o escritório trabalha.',
        'Sei citar os 5 valores prioritários.',
        'Entendi por que "agir na sorte" é falta grave de cultura aqui.',
      ],
      promptVideo: [
        'Gere um vídeo de boas-vindas, de 3 a 5 minutos para novos integrantes do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado, estagiário ou back office no primeiro dia. Nunca ouviu falar do escritório por dentro.',
        'TOM: caloroso, direto, orgulhoso sem ser pomposo. Português do Brasil. Trate a pessoa por "você".',
        '',
        'ROTEIRO OBRIGATÓRIO, NESTA ORDEM:',
        '1. Abertura com a missão: somos a voz de quem o Estado esquece, especialmente idosos e aposentados.',
        '2. Um exemplo concreto de cliente: aposentada de 74 anos com desconto de RMC que nunca contratou.',
        '3. A visão: faturamento previsível, atuação nacional, equipe enxuta, caminho até a sociedade.',
        '4. Os 15 valores citados rapidamente, depois os 5 prioritários explicados um a um com exemplo do dia a dia.',
        '5. Como NÃO vivemos os valores: trabalhar desmotivado, agir na sorte, omitir informação do cliente.',
        '6. As 4 vantagens competitivas.',
        '7. Fechamento com as três palavras: Justiça, Crescimento, Excelência. E a frase "Vamos crescer juntos".',
        '',
        'NÃO FAÇA: promessa de resultado processual, número de faturamento como meta pessoal do espectador, jargão jurídico não explicado.',
      ].join('\n'),
    },

    {
      id: 'como-funciona',
      titulo: 'Como o escritório funciona por dentro',
      resumo: 'Estrutura, cargos, quem decide o quê e por onde passa a sua carreira.',
      minutos: 10,
      manual: [
        '## Os cargos',
        '',
        '1. **Sócios Nominais** — respondem pelo escritório, decidem capital, estatuto e entrada de sócios.',
        '2. **Sócios** (Sênior, Pleno, Júnior) — conduzem carteira e gestão.',
        '3. **Associados** — advogados que tocam os processos ponta a ponta.',
        '4. **Back Office** — suporte, cadastro, atendimento, organização.',
        '5. **Estagiários** — formação com trabalho real supervisionado.',
        '',
        '## Os setores',
        '',
        '- **Controladoria Jurídica** — prazos, publicações, curadoria do sistema, custas e guias. É quem impede prazo de morrer.',
        '- **Back Office** — cadastro, documentos, atendimento, organização das pastas.',
        '- **Diretoria Estratégica (CEO)** — rumo do escritório, entrada de sócios, representação.',
        '- **Diretoria de RH (Pessoas)** — admissão, desligamento, plano de carreira, folha, disciplina.',
        '- **Diretoria de Marketing** — marca, redes, material, site. Nada sai em nome do escritório sem passar por aqui.',
        '- **Diretoria Operacional** — estrutura, insumos, risco operacional.',
        '- **Diretoria Financeira** — DRE, orçamento, pagamentos, cobrança de cotas, notas fiscais.',
        '',
        '## Quem decide o quê',
        '',
        '- **Assembleia Geral de Sócios Nominais** — capital social, estatuto, eleição e saída de sócios, alienação de cotas, normas internas.',
        '- **Assembleia Geral de Sócios** — rotina e gestão, remuneração de sócios gestores, metas, punições e desligamentos.',
        '- **Diretorias** — executam dentro da competência de cada uma.',
        '',
        '> Regra prática: se a decisão muda a estrutura ou o dinheiro do escritório, ela não é sua. Leve para a coordenação.',
        '',
        '## Plano de carreira',
        '',
        'O crescimento interno é parte da visão: **associado vira sócio**. O caminho passa por resultado, cumprimento de prazo, qualidade técnica e postura. Seu cargo, suas atribuições e a progressão estão descritos em **Meu Espaço → Estrutura**, no hub.',
        '',
        '## O que se espera de você no cargo de associado',
        '',
        '- Conduzir o caso do cadastro ao repasse final.',
        '- 100% de cumprimento de prazos. Zero audiência perdida.',
        '- Responder o cliente no **mesmo dia**.',
        '- Manter o hub atualizado — o que não está no sistema não existe.',
        '- 5 dias úteis para montar as ações de um cliente distribuído a você.',
        '',
        '> Caso em atraso é redistribuído para outro associado. Não é punição: é o cliente que não pode esperar.',
      ].join('\n'),
      checklist: [
        'Sei a quem levar uma decisão que não é minha.',
        'Sei onde ver meu cargo e minha progressão no hub.',
        'Sei os 4 números que medem um associado aqui.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos explicando a estrutura interna do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: pessoa recém-contratada, primeira semana.',
        'TOM: organizacional e claro, como quem desenha um mapa. Português do Brasil.',
        '',
        'ROTEIRO:',
        '1. Os 5 cargos, do estagiário ao sócio nominal, com uma frase do que cada um faz.',
        '2. Os 7 setores, com destaque especial para a Controladoria Jurídica: explique que ela existe para impedir perda de prazo e documento.',
        '3. Quem decide o quê: assembleias x diretorias. Dê a regra prática "se muda estrutura ou dinheiro, não é decisão sua".',
        '4. O plano de carreira: associado pode virar sócio, e o que pesa nessa avaliação.',
        '5. As 4 metas de um associado: 48h para cadastro, 100% de prazos, resposta ao cliente no mesmo dia, 5 dias úteis para montar as ações.',
        '6. Feche explicando que caso atrasado é redistribuído, e que isso protege o cliente, não pune a pessoa.',
        '',
        'NÃO FAÇA: inventar nomes de pessoas, inventar salários, transformar as metas em ameaça.',
      ].join('\n'),
    },

    {
      id: 'regras-do-jogo',
      titulo: 'As regras do jogo: regimento interno na prática',
      resumo: 'O que é obrigação, o que é proibição e o que acontece quando se descumpre.',
      minutos: 9,
      manual: [
        '## Suas obrigações (as que mais pesam)',
        '',
        '- **Cumprir e fazer cumprir os prazos judiciais.** É a primeira da lista por um motivo.',
        '- **Registrar tudo no sistema.** Toda demanda, dado e processo entram no hub. Sem isso não há controle de prazo nem prova do que foi feito.',
        '- **Guardar sigilo** de tudo que você souber pela função — durante e depois do contrato.',
        '- **Comparecer a assembleias e treinamentos.**',
        '- **Manter OAB e obrigações profissionais em dia**, por sua conta. O escritório pode pedir comprovação a qualquer momento.',
        '- **Comunicar irregularidade** de que tomar ciência.',
        '- **Apresentar-se adequadamente** e tratar todo mundo com urbanidade.',
        '- **Observar o Estatuto da Advocacia e o Código de Ética.** Isso está acima de qualquer regra interna.',
        '',
        '## Proibições',
        '',
        '- Usar a condição funcional para proveito pessoal.',
        '- Cuidar de assunto particular durante o expediente.',
        '- Retirar material ou documento do escritório sem autorização.',
        '- Fornecer informação a terceiro sem autorização.',
        '- **Manifestar-se em nome do escritório** por qualquer meio sem passar pelo Marketing.',
        '- Usar recurso material ou humano do escritório em atividade particular.',
        '- Usar a razão social para fim estranho à sociedade (aval, fiança e afins são nulos).',
        '',
        '## Descumprimentos e consequências',
        '',
        'A gradação é **leve, média ou grave**. Leve e média são aplicadas pela Diretoria de RH; grave vai à Assembleia Geral.',
        '',
        '### Para empregados',
        '- Leve: advertência até suspensão de 6 dias.',
        '- Média: suspensão de 7 a 15 dias.',
        '- Grave: suspensão de 16 dias até demissão.',
        '',
        '### Para sócios e associados',
        '- Leve: advertência até 1 semana sem receber processos.',
        '- Média: 1 a 3 semanas sem receber processos.',
        '- Grave: 3 a 4 semanas sem receber processos, ou rescisão contratual.',
        '',
        '> Suspender o recebimento de processos é o que mais dói no bolso de quem é remunerado por êxito. É de propósito.',
        '',
        '## A regra que salva você',
        '',
        'Problema profissional acontece: doença, sobreposição de audiência, caso que travou. **Comunique com a maior antecedência possível.**',
        '',
        'A ausência de comunicação transforma um problema contornável em falha irreversível. Ninguém aqui é punido por avisar cedo. Todo mundo é cobrado por avisar depois que já era.',
      ].join('\n'),
      checklist: [
        'Li o regimento interno completo (Meu Espaço → Documentos institucionais).',
        'Sei que não posso falar em nome do escritório sem o Marketing.',
        'Sei a quem avisar, e com quanto tempo, quando algo vai atrasar.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre o Regimento Interno do escritório Frider Andrade | Advogados, traduzido para o dia a dia.',
        '',
        'PÚBLICO: pessoa recém-contratada. Não leu o regimento inteiro ainda.',
        'TOM: firme e adulto, sem tom de ameaça. Deixe claro que as regras existem para proteger cliente e equipe.',
        '',
        'ROTEIRO:',
        '1. Comece pela obrigação número um: cumprir e fazer cumprir prazos judiciais. Explique por que ela abre a lista.',
        '2. As obrigações de registro no sistema, sigilo, OAB em dia, urbanidade e Código de Ética.',
        '3. As proibições, com ênfase em: falar em nome do escritório sem o Marketing, e usar recurso do escritório para fim particular.',
        '4. A gradação leve, média e grave, e as consequências diferentes para empregados e para sócios/associados. Explique que suspender o recebimento de processos atinge a remuneração por êxito, e por que isso é proposital.',
        '5. Termine com a regra que salva: comunicar cedo. A frase "a ausência de comunicação transforma um problema contornável em falha irreversível" deve aparecer.',
        '',
        'NÃO FAÇA: tom de intimidação, lista decorada sem exemplo, citação de artigo de lei sem explicar.',
      ].join('\n'),
    },

    {
      id: 'ferramentas',
      titulo: 'Suas ferramentas e seus acessos',
      resumo: 'O que cada sistema faz, quais acessos você precisa e a regra de login.',
      minutos: 8,
      manual: [
        '## O que você usa hoje',
        '',
        '- **Hub (hub.friderandrade.com.br)** — o centro de tudo. Atendimento por WhatsApp, kanban dos processos, prazos, agenda, financeiro, RH, calculadoras e geração de peças.',
        '- **Claude (Cowork)** — inteligência artificial com as *skills* do escritório para montar peças, pesquisar jurisprudência e revisar.',
        '- **Google Drive** — pasta de cada cliente, modelos, documentos institucionais e este acervo de treinamento.',
        '- **ZapSign** — assinatura eletrônica de contrato e procuração.',
        '- **Cálculo Jurídico** — cálculos de execução e atualização quando a calculadora do hub não cobrir.',
        '- **PJe, e-SAJ, Projudi, eproc** — os sistemas dos tribunais. É onde se protocola.',
        '- **ASAAS** — cobrança (boleto, PIX, cartão).',
        '',
        '## Seus acessos',
        '',
        'A liberação de todas as credenciais leva até **48 horas** depois do ingresso. Peça ao RH o que faltar. Você precisa de:',
        '',
        '1. E-mail do escritório.',
        '2. Login no hub.',
        '3. Acesso ao Google Drive do escritório.',
        '4. Claude / Cowork com as skills instaladas.',
        '5. Certificado digital e cadastro nos sistemas dos tribunais em que atuará.',
        '6. WhatsApp do escritório configurado no hub (você não usa seu número pessoal com cliente).',
        '',
        '## Regra de ouro dos acessos',
        '',
        '- Senha do escritório **não** se compartilha por WhatsApp nem se anota em papel na mesa.',
        '- Cada pessoa usa o **próprio login**. Trabalho feito com login de outro não tem dono — e prazo sem dono é prazo perdido.',
        '- Saiu do escritório? Os acessos são revogados no mesmo dia pelo RH.',
      ].join('\n'),
      checklist: [
        'Consigo entrar no hub, no Drive e no Claude.',
        'Meu certificado digital está instalado e testado em um tribunal.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos apresentando as ferramentas do escritório Frider Andrade | Advogados a um novo contratado.',
        '',
        'PÚBLICO: pessoa na primeira semana, ainda esperando alguns acessos.',
        'TOM: prático, de tour guiado.',
        '',
        'ROTEIRO:',
        '1. Apresente o Hub como o centro de tudo, listando o que ele faz: atendimento, kanban, prazos, financeiro, RH, calculadoras, geração de peças.',
        '2. Apresente o Claude com as skills do escritório como a ferramenta de peças e pesquisa.',
        '3. Apresente Drive, ZapSign, Cálculo Jurídico, ASAAS e os sistemas dos tribunais.',
        '4. Liste os 6 acessos que a pessoa precisa ter, e diga que a liberação leva até 48 horas.',
        '5. Feche com a regra de ouro: login é pessoal, senha não circula por WhatsApp, e trabalho feito no login de outra pessoa é prazo sem dono.',
        '',
        'NÃO FAÇA: mostrar senha real, ensinar a burlar acesso, prometer prazo de liberação menor que 48h.',
      ].join('\n'),
    },

    {
      id: 'primeira-semana',
      titulo: 'Sua primeira semana, dia a dia',
      resumo: 'O roteiro exato dos 5 primeiros dias e dos 30 primeiros.',
      minutos: 7,
      manual: [
        '## Dia 1 — entender onde você está',
        '',
        '- Assistir "Quem somos" e "Como o escritório funciona".',
        '- Ler o Regimento Interno e o Missão, Visão e Valores por inteiro.',
        '- Receber e testar os acessos que já saíram.',
        '- Conhecer quem é quem: **Meu Espaço → Estrutura** tem o organograma.',
        '- Assinar contrato, procuração de representação e termo de sigilo/LGPD com o RH.',
        '',
        '## Dia 2 — o hub',
        '',
        '- Fazer a trilha **O Hub por dentro** inteira.',
        '- Abrir uma conversa, um card do kanban e uma ficha de processo só para navegar.',
        '- Configurar suas notificações e conferir se a Agenda está mostrando algo.',
        '',
        '## Dia 3 — a tese',
        '',
        '- Fazer a trilha **As teses do escritório**, no mínimo RMC e RCC.',
        '- Ler uma inicial de RMC e uma sentença de procedência do acervo, do começo ao fim.',
        '- Entender de onde vem o dinheiro: o que é repetição de indébito, o que é dano moral.',
        '',
        '## Dia 4 — a ferramenta de produção',
        '',
        '- Fazer a trilha **Claude: peças, pesquisa e revisão**.',
        '- Montar uma peça de treino com a skill, do zero ao timbrado, **sem protocolar**.',
        '- Levar a peça para revisão de quem te acompanha.',
        '',
        '## Dia 5 — prazo',
        '',
        '- Fazer a trilha **Prazos e controladoria**.',
        '- Acompanhar a controladoria tratando as publicações do dia.',
        '- Montar a sua rotina fixa de prazo (horário do dia em que você trata publicação).',
        '',
        '## Primeiros 15 dias — a rede de proteção',
        '',
        'Nos primeiros 15 dias a **controladoria do escritório agenda os seus prazos** para você. É período de adaptação. Depois disso, a controladoria de cada caso passa a ser integralmente sua.',
        '',
        '> Use esses 15 dias para aprender a agendar, não para deixar de olhar. Quem só começa a olhar no dia 16 perde prazo no dia 17.',
        '',
        '## Primeiros 30 dias — o que se espera',
        '',
        '- Carteira própria de casos, com o kanban atualizado por você.',
        '- Nenhuma publicação sua acumulada.',
        '- Cliente respondido no mesmo dia.',
        '- Ao menos uma inicial e uma peça de resposta montadas e protocoladas por você.',
        '- Uma conversa de acompanhamento com a coordenação sobre o que travou.',
      ].join('\n'),
      checklist: [
        'Fiz as 5 trilhas obrigatórias da primeira semana.',
        'Montei uma peça de treino e ela foi revisada.',
        'Tenho horário fixo no dia para tratar publicação.',
        'Sei que a partir do dia 16 o prazo é meu.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos com o roteiro da primeira semana de trabalho no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: pessoa que acabou de ser contratada, provavelmente ansiosa.',
        'TOM: acolhedor e organizado, de quem entrega um mapa. Português do Brasil.',
        '',
        'ROTEIRO: percorra dia a dia, do Dia 1 ao Dia 5, dizendo o objetivo do dia e as tarefas concretas.',
        'Dia 1 entender onde está. Dia 2 o hub. Dia 3 a tese. Dia 4 a ferramenta de produção com Claude. Dia 5 prazo.',
        'Depois explique a rede de proteção dos primeiros 15 dias: a controladoria agenda os prazos, e a partir do dia 16 o prazo é da pessoa. Inclua o alerta de que quem só começa a olhar no dia 16 perde prazo no dia 17.',
        'Feche com as 5 expectativas dos primeiros 30 dias.',
        '',
        'NÃO FAÇA: prometer que a primeira semana é leve, omitir que a responsabilidade pelo prazo é transferida.',
      ].join('\n'),
    },
  ],
};
