import type { Trilha } from '../types';

export const HUB: Trilha = {
  id: 'hub',
  titulo: 'O Hub por dentro',
  subtitulo: 'Módulo a módulo, o que fazer em cada tela',
  icone: 'LayoutGrid',
  cor: '#228BE6',
  publico: 'Todo mundo. Advogado usa tudo; back office usa Comercial e Cadastros.',
  aulas: [
    {
      id: 'visao-geral',
      videoPlanejado: true,
      video: {
        fonte: 'url',
        url: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/visao-geral.mp4',
        legendas: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/visao-geral.vtt',
        duracao: '3:38',
      },
      titulo: 'Visão geral: a lógica do hub',
      resumo: 'A lógica do sistema: uma conversa vira lead, vira cliente, vira processo, vira dinheiro.',
      minutos: 8,
      manual: [
        '## O que o hub é',
        '',
        'O hub (**hub.friderandrade.com.br**) é o sistema próprio do escritório. Ele reúne em um lugar só o atendimento por WhatsApp, o funil comercial, o kanban dos processos, os prazos, a agenda, o financeiro, o RH e as calculadoras.',
        '',
        '## A linha da vida de um caso',
        '![O Funil, no bloco Comercial: cada lead é um card e caminha da Recepção até a assinatura no ZapSign. Os nomes estão borrados de propósito — o que importa aqui são as colunas.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/funil-comercial.png)',
        '',
        '',
        '1. **Conversa** — a pessoa chama no WhatsApp. A IA atende, qualifica e faz a triagem.',
        '2. **Lead** — vira card no kanban comercial. Documento, proposta, contrato pelo ZapSign.',
        '3. **Cliente** — assinado o contrato, nasce a pasta no Drive e o cadastro no hub.',
        '4. **Processo** — a ficha do processo, com partes, documentos, cálculo e etiquetas.',
        '5. **Kanban jurídico** — o card anda de fase conforme o processo anda de verdade.',
        '6. **Agenda e prazos** — cada publicação do DJEN vira item para tratar.',
        '7. **Execução e repasse** — cálculo, alvará, prestação de contas, dinheiro na mão do cliente.',
        '',
        '> Tudo que você faz fora do hub some. Reunião no corredor, combinação por áudio, anotação no caderno: para o escritório, não aconteceu.',
        '',
        '## Os grandes blocos da barra lateral',
        '',
        '- **Início** — sua mesa de trabalho: o que está esperando por você agora.',
        '- **Conquistas** — depoimentos e resultados dos clientes.',
        '- **Comercial** — Dashboard, Conversas, Kanban de leads, Contatos, Agentes de IA, Follow-ups, Conexões.',
        '- **Jurídico** — Dashboard, Agenda, Publicações, Processos, os Kanbans, Recursos, Jurimetria, Calculadoras, Clientes.',
        '- **Administrativo** — Financeiro, RH & Seleção, Contabilidade.',
        '- **Rodapé** — Copiloto (sócios), Ajuda, Meu Espaço, Configurações.',
        '',
        '## Barra simples',
        '',
        'Dá para reduzir a barra lateral só ao que você usa. A preferência é sua e viaja com o seu login, em qualquer aparelho.',
        '',
        '## Modo escuro',
        '',
        'O hub tem tema claro e escuro. O ajuste é pessoal e fica salvo.',
        '',
        '## No celular',
        '',
        'O hub é instalável como aplicativo (PWA). Abra no navegador do celular e escolha "adicionar à tela de início". Serve para responder cliente e conferir prazo fora do escritório — mas peça se monta no computador.',
      ].join('\n'),
      checklist: [
        'Sei recitar a linha da vida de um caso, da conversa ao repasse.',
        'Instalei o hub no celular.',
        'Configurei a barra lateral com o que eu uso.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos apresentando o Hub, o sistema interno do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: pessoa nova, que nunca abriu o sistema.',
        'TOM: tour guiado, entusiasmado mas objetivo. Português do Brasil.',
        '',
        'ROTEIRO:',
        '1. O que o hub é: o sistema próprio do escritório, que reúne atendimento, funil, processos, prazos, financeiro e RH em um lugar só.',
        '2. A linha da vida de um caso, em 7 passos: conversa, lead, cliente, processo, kanban jurídico, agenda e prazos, execução e repasse. Este é o miolo do vídeo, gaste tempo aqui.',
        '3. Os blocos da barra lateral: Início, Conquistas, Comercial, Jurídico, Administrativo e o rodapé.',
        '4. Recursos de conforto: barra simples, modo escuro, instalação no celular como aplicativo.',
        '5. Feche com a regra: o que não está no hub não aconteceu.',
        '',
        'NÃO FAÇA: detalhar campo por campo de tela, prometer funcionalidade que não existe.',
      ].join('\n'),
    },

    {
      id: 'inicio',
      titulo: 'Início: sua mesa de trabalho',
      resumo: 'Como começar o dia olhando uma tela só.',
      minutos: 5,
      video: {
        fonte: 'url',
        url: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/inicio.mp4',
        legendas: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/inicio.vtt',
        duracao: '3 min',
      },
      manual: [
        '## O que o Início mostra',
        '',
        'O Início responde a uma pergunta: **o que está esperando por mim agora?**',
        '',
        '- Conversas que aguardam resposta sua.',
        '- Tarefas e prazos atribuídos a você.',
        '- Publicações novas que caíram nos seus processos.',
        '- Avisos do escritório e notificações.',
        '',
        '![O Início: os números do dia, as Conquistas, as mensagens esperando resposta e o que entrou na agenda](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/inicio-mesa.png)',
        '',
        '## O filtro "esperando você"',
        '',
        'O Início mostra **as suas** conversas e tarefas — não a fila do escritório inteiro. Se você está vendo pouca coisa, provavelmente há pouca coisa atribuída a você, não pouca coisa acontecendo.',
        '',
        '## A rotina de abertura do dia',
        '',
        '1. Abrir o Início e limpar o que está pendente de resposta.',
        '2. Ir em **Publicações** e tratar tudo que chegou.',
        '3. Abrir a **Agenda** e conferir os prazos da semana, não só do dia.',
        '4. Voltar aos cards do kanban que dependem de você.',
        '',
        '> Ordem importa: publicação primeiro, porque é dela que nasce prazo. Conversa depois, porque cliente espera resposta no mesmo dia mas não preclui.',
        '',
        '## Notificações',
        '',
        'O sino traz atribuição de tarefa, prazo criado, publicação classificada, alvará disponível e aviso de repasse. Notificação não substitui a Agenda: **prazo se confere na Agenda**, não no sino.',
      ].join('\n'),
      checklist: [
        'Tenho uma rotina fixa de abertura do dia.',
        'Sei que o Início mostra só o que é meu.',
        'Confiro prazo na Agenda, não na notificação.',
      ],
      promptVideo: [
        'Gere um vídeo curto, de 3 a 5 minutos, sobre a tela Início do Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado ou estagiário que vai usar o sistema todo dia.',
        'TOM: prático, de rotina de trabalho.',
        '',
        'ROTEIRO:',
        '1. Explique que o Início responde a uma única pergunta: o que está esperando por mim agora.',
        '2. Liste o que aparece: conversas aguardando resposta, tarefas e prazos, publicações novas, avisos.',
        '3. Explique o filtro: o Início mostra o que é da pessoa, não a fila do escritório inteiro.',
        '4. Ensine a rotina de abertura do dia em 4 passos, na ordem: publicações, conversas, agenda da semana, cards do kanban. Justifique a ordem: publicação gera prazo e prazo preclui.',
        '5. Alerte que notificação não substitui a Agenda.',
        '',
        'NÃO FAÇA: transformar em tutorial de cliques.',
      ].join('\n'),
    },

    {
      id: 'conversas',
      videoPlanejado: true,
      titulo: 'Conversas: WhatsApp, IA e quando você assume',
      resumo: 'Como a IA atende, quando ela para, e como não estragar o atendimento.',
      minutos: 12,
      video: {
        fonte: 'url',
        url: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/conversas.mp4',
        legendas: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/conversas.vtt',
        duracao: '3 min',
      },
      manual: [
        '## Como funciona',
        '',
        '![A tela de Conversas: à esquerda a fila, no meio a conversa, à direita a ficha do contato. O balão verde com a etiqueta *Atendimento ao Cliente* é do agente de IA; abaixo dele, o ponto em que a pessoa assumiu. No rodapé, o número oficial de onde a mensagem sai.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/conversas-chat.png)',
        '',
        'Todo o WhatsApp do escritório entra em **Conversas**. Os **agentes de IA do próprio hub** fazem a recepção, a triagem e boa parte do atendimento; quando o caso exige gente, a conversa é transferida para uma pessoa.',
        '',
        '> Não confunda: quem atende cliente no WhatsApp são os agentes do hub. O **Claude** é a ferramenta de produção de peça e pesquisa, e não fala com cliente nenhum. São coisas diferentes, em trilhas diferentes.',
        '',
        '## A regra que mais confunde',
        '',
        '**Quando um humano responde manualmente, a IA daquela conversa é pausada automaticamente.** Isso é de propósito: evita a IA falar por cima de você.',
        '',
        'Consequência: se depois você quiser que a IA volte a atender aquele cliente, precisa **reativá-la na própria conversa**. Se alguém reclamar que "o robô parou de responder", quase sempre foi isso.',
        '',
        '## A janela de 24 horas',
        '',
        'A API oficial do WhatsApp só deixa enviar mensagem livre dentro de **24 horas** desde a última mensagem do cliente. Passou disso, o envio falha na hora.',
        '',
        'Para reabrir a conversa fora da janela, use **Enviar template** (menu ＋ no chat) e escolha um modelo aprovado. O template reabre a janela e aí você conversa normalmente.',
        '',
        '> Erro clássico: escrever uma mensagem linda, mandar, ver "enviado" e o cliente nunca receber. Se passou de 24h, é template ou nada.',
        '',
        '## Números do escritório',
        '',
        'O escritório atende por números oficiais configurados no hub. **Nunca** use seu número pessoal com cliente: o histórico fica fora do sistema, o escritório perde a prova do que foi dito e você leva o cliente embora quando sair.',
        '',
        '> Nunca faça disparo em massa. O escritório já teve número banido exatamente por isso.',
        '',
        '## Recursos do chat',
        '',
        '- **Ficha do cliente a um clique** — abre o cadastro e os processos daquela pessoa.',
        '- **Mensagens rápidas** — respostas padronizadas com atalho.',
        '- **Editar e apagar mensagem** — funciona, com limite de tempo do próprio WhatsApp.',
        '- **Enviar contato (vCard)** e **enviar documento**.',
        '- **Áudio, imagem e PDF** — a IA lê e transcreve o que o cliente manda.',
        '',
        '## Cliente com número novo',
        '',
        'Quando um cliente conhecido escreve de outro número, o hub oferece **vincular** ao cadastro existente. Faça o vínculo — senão você fica com dois históricos da mesma pessoa e responde no lugar errado.',
        '',
        '> Nunca junte pessoas por nome. Homônimo existe e já causou estrago aqui. O vínculo se faz por CPF ou pelo contato, nunca por nome parecido.',
        '',
        '## Sua meta de atendimento',
        '',
        'Responder no **mesmo dia**. Se precisa apurar algo antes, avise o cliente que está apurando e dê um prazo de retorno — e cumpra.',
      ].join('\n'),
      checklist: [
        'Sei reativar a IA de uma conversa.',
        'Sei o que fazer quando passou de 24h desde a última mensagem do cliente.',
        'Nunca uso meu número pessoal com cliente.',
        'Sei vincular cliente que apareceu com número novo.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre o módulo Conversas do Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado e back office que vão atender cliente por WhatsApp dentro do sistema.',
        'TOM: prático, com alerta claro nos pontos que costumam dar errado.',
        '',
        'ROTEIRO:',
        '1. Como funciona: todo o WhatsApp do escritório entra em Conversas, com os agentes de IA do próprio hub na recepção e na triagem. Deixe explícito que NÃO é o Claude que atende cliente — o Claude é a ferramenta de peça, de outra trilha.',
        '2. A regra mais importante: quando um humano responde manualmente, a IA daquela conversa é pausada de propósito, e precisa ser reativada na própria conversa. Diga que a queixa "o robô parou de responder" quase sempre é isso.',
        '3. A janela de 24 horas da API oficial do WhatsApp: fora dela o envio falha, e a saída é enviar um template aprovado, que reabre a janela. Dê o exemplo do erro clássico de escrever, mandar e o cliente nunca receber.',
        '4. Regra dos números: sempre o número oficial no hub, nunca o pessoal. Explique as três razões: histórico fora do sistema, perda de prova e perda do cliente. Inclua a proibição de disparo em massa, citando que o escritório já teve número banido.',
        '5. Recursos do chat: ficha do cliente a um clique, mensagens rápidas, editar e apagar, enviar contato e documento, leitura de áudio e PDF pela IA.',
        '6. Cliente com número novo: vincular ao cadastro, e a regra de nunca casar pessoas por nome por causa de homônimo.',
        '7. Feche com a meta: responder no mesmo dia.',
        '',
        'NÃO FAÇA: ensinar a contornar a janela de 24h por caminho não oficial, sugerir uso de número pessoal em qualquer hipótese.',
      ].join('\n'),
    },

    {
      id: 'kanbans',
      titulo: 'Os kanbans: onde cada caso mora',
      resumo: 'Sete quadros, cada um com uma pergunta diferente. Como o card anda.',
      minutos: 10,
      manual: [
        '## Os quadros',
        '',
        '- **Pré-Processual** — o caso antes de existir processo: documento, análise, decisão de entrar.',
        '- **Fase Bancária Investigativa** — extrato, HISCON, HISCRE, contrato: montar a prova antes da inicial.',
        '- **REPB — Reestruturação de Passivo** — a esteira própria dessa vertical.',
        '- **Fase Judicial** — o processo em curso, da inicial ao trânsito.',
        '- **Execução & Repasse** — cálculo, cumprimento, alvará, prestação de contas, dinheiro no cliente.',
        '- **Planejamento Previdenciário** e **INSS Administrativo** — as verticais previdenciárias.',
        '- **Quadros personalizados** — quadros criados pelo escritório sem precisar de programação.',
        '',
        '![O **Pré-Processual**: do fechamento do contrato até o protocolo. Ao protocolar, o caso migra sozinho para a Fase Judicial.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/pre-processual.png)',
        '',
        '![O **Execução & Repasse**, a outra ponta: cumprimento de sentença, recebimento, prestação de contas — e as colunas de ações vencidas e perdidas, que ninguém gosta de olhar e todo mundo precisa.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/execucao-repasse.png)',
        '',
        '## Como o card anda',
        '',
        'Na Fase Judicial, **quem move o card é o DJEN**. A publicação chega, o classificador lê o teor, entende o ato e empurra o card para a fase certa. Você não fica arrastando card o dia inteiro.',
        '',
        '![A Fase Judicial: o cabeçalho diz que o quadro se move sozinho conforme as publicações do DJEN. O card em destaque mostra a anatomia — etiqueta da tese, partes, número, valor e o selo de vencimento.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/kanban-fase-judicial.png)',
        '',
        'Quando o sistema não tem certeza, ele marca o card com um selo de **revisar fase** — é o pedido para uma pessoa olhar.',
        '',
        '![A Fase Judicial: repare no aviso do próprio quadro — “o quadro se move sozinho conforme as publicações do DJEN” — e nos selos amarelos de revisar fase](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/kanban-fase-judicial.png)',
        '',
        '> Card parado numa fase estranha quase nunca é bug de arrastar: é publicação que chegou sem teor (ponteiro do Projudi, por exemplo) ou ato que o classificador não reconheceu. Trate a publicação, não o card.',
        '',
        '## O que você faz manualmente',
        '',
        '- **Arrastar card e arrastar fase** — dá para reordenar cards e reordenar as próprias colunas.',
        '- **Seleção e ações em massa** — marcar vários cards e mover, etiquetar ou atribuir de uma vez.',
        '- **Criar fase nova** direto no quadro, sem programação.',
        '- **Atribuir responsável** — card sem dono é trabalho que ninguém faz.',
        '',
        '## Etiquetas',
        '',
        'Use as etiquetas que **já existem**. Não crie etiqueta nova por conta própria: etiqueta duplicada quebra filtro, relatório e busca. Processo em CAIXA ALTA, cliente em Maiúsculas Normais.',
        '',
        '## Card terminal',
        '',
        'Quando o caso chega ao fim com êxito, o card vai para a coluna final e o hub comemora. Não é enfeite: é o sinal de que não há mais providência pendente ali.',
      ].join('\n'),
      checklist: [
        'Sei em qual quadro cada tipo de caso mora.',
        'Entendi que o DJEN é quem move o card na Fase Judicial.',
        'Sei o que significa o selo de revisar fase.',
        'Não crio etiqueta nova.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre os kanbans do Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado que vai conduzir carteira de processos.',
        'TOM: explicativo, com ênfase em desfazer o mal-entendido de que o kanban é movido na mão.',
        '',
        'ROTEIRO:',
        '1. Apresente os sete quadros e a pergunta que cada um responde.',
        '2. Explique que na Fase Judicial quem move o card é o DJEN: a publicação chega, o classificador lê o teor e empurra o card. Explique o selo de revisar fase para quando o sistema não tem certeza.',
        '3. Dê o diagnóstico do card parado em fase estranha: quase sempre é publicação sem teor, como ponteiro do Projudi, ou ato não reconhecido. A instrução é tratar a publicação, não arrastar o card.',
        '4. Mostre o que é manual: arrastar card e coluna, seleção em massa, criar fase, atribuir responsável. Diga que card sem dono é trabalho que ninguém faz.',
        '5. Regra das etiquetas: usar as que já existem, nunca criar. Processo em caixa alta, cliente em maiúsculas normais.',
        '6. Feche com o card terminal e o que ele significa.',
        '',
        'NÃO FAÇA: ensinar a arrastar card para "consertar" fase errada sem tratar a publicação.',
      ].join('\n'),
    },

    {
      id: 'processos',
      titulo: 'Processos: a ficha do caso',
      resumo: 'Onde vive o número do processo, as partes, os documentos e o cálculo.',
      minutos: 10,
      manual: [
        '## O que a ficha guarda',
        '',
        '![A ficha de um processo: cabeçalho com as partes, número, juízo e valor da causa; à direita o cliente com atalho para a conversa, as próximas atividades e os prazos abertos.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/ficha-processo.png)',
        '',
        '- **Número do CNJ**, comarca, vara e juízo — no formato curto (ex.: 2ª Vara Cível de Maringá/PR), sempre vindo do DataJud, nunca digitado de cabeça.',
        '- **Partes** — cliente e parte adversa, com CPF/CNPJ. É daqui que a peça puxa a qualificação.',
        '- **Documentos** — procuração, documentos pessoais, extratos, contrato, e as peças geradas.',
        '- **Movimentações** — o histórico do que aconteceu.',
        '- **Etiquetas** e **fase** no kanban.',
        '- **Cálculo** salvo, que vira valor da causa e depois valor da execução.',
        '- **Apensos** — processos ligados (recurso registrado vira apenso automaticamente).',
        '',
        '![A ficha do processo: as etiquetas, o juízo em formato curto, o valor da causa, as abas Resumo/Atividades/Recursos/Histórico e, à direita, a conversa do cliente e os prazos abertos](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/processo-ficha.png)',
        '',
        '## Documentos do cliente',
        '',
        'Os documentos vivem na **pasta do cliente no Google Drive**. O hub guarda o ponteiro, não o arquivo. Duas consequências práticas:',
        '',
        '1. Excluir um documento no hub **não apaga** o arquivo no Drive.',
        '2. Se o arquivo for movido ou renomeado no Drive, o hub pode perder o link. Organize a pasta pelo padrão, não pelo gosto.',
        '',
        '## Arquivar a peça protocolada',
        '',
        'Depois de protocolar, a peça e o comprovante voltam para a pasta do cliente no Drive, numerados, e a tarefa é fechada com **Concluir e arquivar**. É esse gesto que fecha o ciclo — não o protocolo em si.',
        '',
        '## Gerar peça pela ficha',
        '',
        'Na ficha há o bloco de geração de peça por IA: réplica, especificação de provas e recurso. Você sobe o documento-base (contestação, réplica ou sentença), escolhe o produto e recebe um **rascunho** no timbrado, anexado ao processo.',
        '',
        '> Leva 1 a 2 minutos quando há vários PDFs. Não feche a tela achando que travou.',
        '',
        '## Processo que não está no hub',
        '',
        'Se chegar publicação de processo que o hub não conhece, o aviso leva direto ao cadastro do CNJ, com a opção de **apensar ao principal**. Cadastre na hora: publicação de processo não cadastrado é prazo que ninguém está contando.',
      ].join('\n'),
      checklist: [
        'Sei onde vejo partes, documentos e cálculo de um processo.',
        'Entendi que documento fica no Drive e o hub guarda o ponteiro.',
        'Sei usar Concluir e arquivar depois de protocolar.',
        'Cadastro na hora processo que apareceu e não está no hub.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre o módulo Processos do Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado que vai gerir a carteira.',
        'TOM: prático e minucioso, sem virar lista de cliques.',
        '',
        'ROTEIRO:',
        '1. O que a ficha guarda: CNJ, comarca e juízo em formato curto vindo do DataJud, partes com CPF, documentos, movimentações, etiquetas, fase, cálculo salvo e apensos.',
        '2. Documentos do cliente: ficam no Google Drive, o hub guarda o ponteiro. Explique as duas consequências: excluir no hub não apaga no Drive, e mover ou renomear no Drive quebra o link.',
        '3. O fechamento do ciclo: depois de protocolar, a peça e o comprovante voltam numerados para a pasta do cliente e a tarefa é encerrada com Concluir e arquivar.',
        '4. Geração de peça por IA a partir da ficha, com aviso de que leva 1 a 2 minutos e que o resultado é rascunho.',
        '5. Publicação de processo não cadastrado: cadastrar na hora, com opção de apensar ao principal. Explique que processo fora do hub é prazo que ninguém conta.',
        '',
        'NÃO FAÇA: dizer que a peça gerada está pronta para protocolo.',
      ].join('\n'),
    },

    {
      id: 'agenda-prazos',
      titulo: 'Agenda, Publicações e Tarefas',
      resumo: 'Como o prazo nasce do DJEN, aparece na agenda e morre protocolado.',
      minutos: 12,
      manual: [
        '## Publicações',
        '',
        '![A agenda na visão semana: a faixa *Dia todo*, no topo, é onde os prazos processuais aparecem. É esta visão que a rotina exige olhar — não a notificação isolada.](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/agenda-semana.png)',
        '',
        'A tela **Publicações** é a caixa de entrada do DJEN. Cada publicação é lida por um classificador que identifica o ato (sentença, despacho, intimação para réplica, designação de audiência, acórdão), calcula o prazo e cria o item na Agenda — já com o card do kanban movido.',
        '',
        '## O que você ainda precisa fazer',
        '',
        'O classificador é bom, não é infalível. Você confere:',
        '',
        '1. **O ato foi lido certo?** Sentença de mérito não pode virar "suspensão".',
        '2. **O prazo bate?** Confira a contagem, principalmente em prazo em dobro.',
        '3. **É prazo meu?** Publicação que intima a parte contrária não gera prazo para nós.',
        '4. **A publicação tem teor?** Muita publicação do Projudi é só ponteiro, sem conteúdo. Nesse caso é preciso abrir os autos.',
        '',
        '> Cerca de um quarto das publicações não traz o teor do ato. Elas ganham um selo de "ato cego": é aviso de que você tem que ir ao processo ver o que aconteceu.',
        '',
        '![Quando o classificador entende o ato, ele diz o que fazer — e o que NÃO fazer](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/agenda-prazo-recorte.png)',
        '',
        '## Agenda',
        '',
        'A Agenda mostra prazos, tarefas, audiências e eventos. Clicando no item você vê o recorte da publicação, o dispositivo da decisão e as ações possíveis.',
        '',
        '![A Agenda no mês: dá para ver a carga real da semana, com o já cumprido riscado](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/agenda-mes.png)',
        '',
        '![O detalhe de um prazo: os selos PRAZO e FATAL, a data fatal em vermelho, o responsável e o recorte da publicação](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/agenda-prazo-detalhe.png)',
        '',
        '- **Criar prazo de recurso** — escolhe o recurso e o prazo nasce já contado em dias úteis, com feriados e recesso considerados.',
        '- **Gerar peça (IA)** — o mesmo gerador da ficha do processo, ali no item.',
        '- **Editar a atividade inteira** — processo, responsável, data, prioridade.',
        '- **Anexos** — dá para anexar arquivo ao prazo, à tarefa ou ao evento.',
        '- **Comentários** — com menção a pessoa, para combinar dentro do item e não por fora.',
        '',
        '## Tarefas',
        '',
        'Tarefa é trabalho sem prazo processual: ligar para cliente, pedir documento, conferir cálculo. Ela tem dono, data e comentários. Tarefa sem dono não é feita.',
        '',
        '## A regra de ouro',
        '',
        '**Prazo se confere na Agenda, todo dia, olhando a semana inteira.** Notificação é lembrete, não controle.',
      ].join('\n'),
      checklist: [
        'Trato as publicações todo dia, sem deixar acumular.',
        'Sei reconhecer publicação sem teor e ir aos autos.',
        'Sei criar prazo de recurso pela Agenda.',
        'Confiro a semana, não só o dia.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre Publicações, Agenda e Tarefas no Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado responsável pela própria controladoria.',
        'TOM: sério, é o módulo em que erro custa prazo.',
        '',
        'ROTEIRO:',
        '1. Publicações como caixa de entrada do DJEN: o classificador lê o ato, calcula o prazo, cria o item na agenda e move o card.',
        '2. As quatro conferências humanas obrigatórias: o ato foi lido certo, o prazo bate, o prazo é nosso, e a publicação tem teor.',
        '3. Explique o problema das publicações sem teor, comuns no Projudi, que recebem selo de ato cego e exigem abrir os autos. Diga que é cerca de um quarto das publicações.',
        '4. A Agenda: recorte da publicação, dispositivo da decisão, criar prazo de recurso com contagem automática em dias úteis, gerar peça por IA, editar a atividade inteira, anexos e comentários com menção.',
        '5. Tarefas: trabalho sem prazo processual, sempre com dono.',
        '6. Feche com a regra de ouro: prazo se confere na Agenda, todo dia, olhando a semana inteira. Notificação é lembrete, não controle.',
        '',
        'NÃO FAÇA: dar a entender que o classificador dispensa conferência humana.',
      ].join('\n'),
    },

    {
      id: 'calculadoras',
      titulo: 'Calculadoras',
      resumo: 'RMC/RCC, revisional, trabalhista, superendividamento e cumprimento de sentença.',
      minutos: 8,
      manual: [
        '## As calculadoras do hub',
        '',
        '- **RMC / RCC** — o cálculo da tese bancária: o que foi descontado, o que seria devido, a diferença e a repetição.',
        '- **Revisional** — recálculo de contrato de empréstimo.',
        '- **Trabalhista** — rescisão e verbas.',
        '- **Superendividamento** — capacidade de pagamento e plano.',
        '- **Cumprimento de sentença** — atualização da condenação para a execução.',
        '- **Provisionamento / perda esperada** — projeção da carteira.',
        '',
        '![A calculadora de RMC/RCC: a fase do cálculo, a importação do HISCON e do HISCRE, a escolha entre RMC e RCC, e os campos do contrato](https://api.friderandrade.com.br/api/v1/uploads/assets/academia/prints/calculadora-rmc.png)',
        '',
        '## Como o cálculo entra no processo',
        '',
        '1. Você calcula na calculadora.',
        '2. **Salva** o cálculo no processo.',
        '3. O valor salvo vira **valor da causa** na inicial e depois base da execução.',
        '',
        'Cálculo que você fez e não salvou não existe para a peça.',
        '',
        '## Antiexcesso',
        '',
        'A calculadora tem trava de antiexcesso: quando o valor pedido extrapola o que a tese sustenta, ela **recusa e registra** a recusa. Não é implicância do sistema — é o que evita a peça ser fulminada por excesso e o escritório perder credibilidade na vara.',
        '',
        '## Blindagem do art. 50 do Código de Ética',
        '',
        'Em caso de êxito, honorário contratual somado à sucumbência **não pode superar a vantagem do cliente**. Quando o cálculo se aproxima disso, aparece um alerta vermelho no cálculo do alvará.',
        '',
        '> O honorário contratual incide sobre o **proveito econômico**, não sobre o total recebido. Sucumbência fica fora dessa base (art. 23 do Estatuto). Confira sempre a cláusula do contrato daquele cliente.',
        '',
        '## Quando usar o Cálculo Jurídico externo',
        '',
        'Para atualização e índices que a calculadora do hub não cobre. O resultado volta para o processo como documento e, se for base de execução, também como cálculo salvo.',
      ].join('\n'),
      checklist: [
        'Sei salvar o cálculo no processo, não só calcular.',
        'Entendo por que a trava de antiexcesso recusa valores.',
        'Sei que contratual incide sobre proveito econômico.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre as calculadoras do Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado que vai montar inicial e execução.',
        'TOM: técnico e cuidadoso com números.',
        '',
        'ROTEIRO:',
        '1. Liste as calculadoras: RMC e RCC, revisional, trabalhista, superendividamento, cumprimento de sentença, provisionamento.',
        '2. Explique o fluxo: calcular, salvar no processo, e o valor salvo virar valor da causa e depois base da execução. Frise que cálculo não salvo não existe para a peça.',
        '3. Explique a trava de antiexcesso: ela recusa e registra quando o pedido extrapola a tese, e isso protege a peça de ser fulminada por excesso.',
        '4. Explique a blindagem do artigo 50 do Código de Ética: em êxito, contratual mais sucumbência não pode superar a vantagem do cliente, com alerta no cálculo do alvará. Deixe claro que o contratual incide sobre o proveito econômico, e não sobre o total recebido, e que a sucumbência fica fora dessa base.',
        '5. Diga quando recorrer ao Cálculo Jurídico externo.',
        '',
        'NÃO FAÇA: dar fórmula de honorário como se valesse para todo contrato; mande sempre conferir a cláusula do cliente.',
      ].join('\n'),
    },

    {
      id: 'financeiro',
      titulo: 'Financeiro, alvará e prestação de contas',
      resumo: 'Do depósito judicial ao dinheiro na conta do cliente, com prova.',
      minutos: 10,
      manual: [
        '## O que o Financeiro faz',
        '',
        'Livro-caixa, contas a pagar e a receber, cartão, conciliação bancária, DRE e o controle de repasses. Para o advogado, o que importa mais é a ponta final do processo.',
        '',
        '## O caminho do dinheiro',
        '',
        '1. **Condenação transitada** → cumprimento de sentença com cálculo atualizado.',
        '2. **Depósito judicial** → petição de alvará.',
        '3. **Alvará levantado** → entra no financeiro.',
        '4. **Prestação de contas ao cliente** → prévia, aprovação e envio.',
        '5. **Repasse** → dinheiro na conta do cliente, com comprovante guardado.',
        '',
        '## Prestação de contas',
        '',
        'O hub monta a prestação: valor bruto, honorário contratual, sucumbência, custas e o líquido do cliente. Você revisa o texto, confere o PDF e só então aprova o envio.',
        '',
        'Fora da janela de 24 horas do WhatsApp, o envio sai por template aprovado, e o hub guarda a prova do envio.',
        '',
        '## Repasse e a prova',
        '',
        'Cada tentativa de contato para o repasse fica registrada, com cadência (48 horas, depois 5 dias). O hub guarda o identificador da mensagem e verifica se foi lida.',
        '',
        '> Isso não é burocracia: é a prova que sustenta uma eventual **consignação em pagamento** se o cliente sumir. Sem esse rastro, o dinheiro fica parado e o escritório fica exposto.',
        '',
        '## Baixa com data certa',
        '',
        'Ao marcar um lançamento como pago ou recebido, a data que vale é a **da baixa** — não a do lançamento nem a do alvará. É assim que o caixa e o mês fecham com a realidade.',
        '',
        '## O que não é seu',
        '',
        'Ações destrutivas e financeiras são restritas a sócio/admin. Se você precisa de algo assim, peça — não procure atalho.',
      ].join('\n'),
      checklist: [
        'Sei a sequência do dinheiro, da condenação ao repasse.',
        'Reviso a prestação de contas antes de aprovar o envio.',
        'Entendi por que o registro das tentativas de repasse existe.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre Financeiro, alvará e prestação de contas no Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado que conduz o caso até o repasse.',
        'TOM: sério, é dinheiro de cliente.',
        '',
        'ROTEIRO:',
        '1. O que o Financeiro faz em geral, e o recorte que interessa ao advogado: a ponta final do processo.',
        '2. O caminho do dinheiro em cinco passos: condenação transitada, cumprimento com cálculo atualizado, depósito judicial e alvará, prestação de contas, repasse com comprovante.',
        '3. A prestação de contas: composição do valor bruto, contratual, sucumbência, custas e líquido do cliente. Revisão humana antes de aprovar o envio. Envio por template quando passou de 24 horas.',
        '4. O registro das tentativas de repasse com cadência de 48 horas e 5 dias, guardando identificador da mensagem e leitura. Explique que esse rastro é a prova que sustenta uma consignação em pagamento se o cliente sumir.',
        '5. A regra da data: ao dar baixa, vale a data da baixa, não a do lançamento nem a do alvará.',
        '6. Feche dizendo que ações financeiras e destrutivas são restritas a sócio e admin, e que a saída é pedir, nunca contornar.',
        '',
        'NÃO FAÇA: sugerir reter valor de cliente, ou tratar o registro de tentativas como formalidade dispensável.',
      ].join('\n'),
    },

    {
      id: 'meu-espaco',
      titulo: 'Meu Espaço, Ajuda e Copiloto',
      resumo: 'Seu contrato, seu holerite, sua carreira — e onde pedir socorro.',
      minutos: 6,
      manual: [
        '## Meu Espaço',
        '',
        '- **Perfil** — sua foto, bio, OAB, frase. Você mesmo edita.',
        '- **Meu Contrato** — o contrato assinado, disponível para você consultar quando quiser.',
        '- **Financeiro pessoal** — holerite, honorários, condições do seu contrato.',
        '- **Estrutura** — organograma, cargos, plano de carreira e as verticais do escritório.',
        '- **Cultura e documentos institucionais** — missão, visão, valores, regimento interno.',
        '- **Manuais e onboarding** — os materiais escritos do escritório.',
        '',
        '## Ajuda',
        '',
        'Chat de IA que ensina a usar o hub, com guias passo a passo. Pergunte "como faço X" em português. É aberto a todo mundo.',
        '',
        '## Copiloto',
        '',
        'Assistente administrativo com visão do escritório inteiro — restrito a sócios e admins.',
        '',
        '## Academia',
        '',
        'É esta biblioteca. Trilhas com vídeo e manual escrito. Serve para o primeiro dia e para consultar depois, quando bater dúvida no meio de um caso.',
        '',
        '> Ajuda responde "onde clico". Academia responde "como se faz e por quê". Use as duas.',
      ].join('\n'),
      checklist: [
        'Sei onde ver meu contrato e meu holerite.',
        'Sei a diferença entre Ajuda e Academia.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre Meu Espaço, Ajuda, Copiloto e Academia no Hub do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: qualquer pessoa da equipe, inclusive quem não é advogado.',
        'TOM: leve e prático, é a parte do sistema que fala da própria pessoa.',
        '',
        'ROTEIRO:',
        '1. Meu Espaço, item por item: Perfil que a própria pessoa edita, Meu Contrato assinado disponível para consulta,',
        '   Financeiro pessoal com holerite e honorários, Estrutura com organograma e plano de carreira, Cultura e',
        '   documentos institucionais, e os manuais.',
        '2. Ajuda: chat de inteligência artificial que ensina a usar o hub, aberto a todo mundo, para perguntas do tipo',
        '   "como faço tal coisa".',
        '3. Copiloto: assistente administrativo com visão do escritório inteiro, restrito a sócios e admins.',
        '4. Academia: a biblioteca de trilhas com vídeo e manual escrito, para o primeiro dia e para consultar depois.',
        '5. Feche com a distinção: a Ajuda responde onde eu clico, a Academia responde como se faz e por quê. Recomende usar as duas.',
        '',
        'NÃO FAÇA: mostrar valores de holerite ou dados financeiros de pessoas reais.',
      ].join('\n'),
    },
  ],
};
