import type { Trilha } from '../types';

export const CLAUDE: Trilha = {
  id: 'claude',
  titulo: 'Claude: peças, pesquisa e revisão',
  subtitulo: 'A ferramenta que produz — e as regras que impedem ela de estragar tudo',
  icone: 'Sparkles',
  cor: '#E8590C',
  publico: 'Advogados e estagiários que produzem peça.',
  aulas: [
    {
      id: 'o-que-e',
      videoPlanejado: true,
      video: {
        fonte: 'url',
        url: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/o-que-e.mp4',
        legendas: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/o-que-e.vtt',
        duracao: '3:29',
      },
      titulo: 'O que o Claude é aqui — e o que ele não é',
      resumo: 'O papel da IA no escritório e o limite que não se atravessa.',
      minutos: 8,
      manual: [
        '## O que é',
        '',
        'O Claude é a inteligência artificial de produção do escritório. Ele roda com as **skills do escritório** — procedimentos escritos que carregam nossos modelos, nossas teses, nosso timbrado e nossos acabamentos.',
        '',
        'Ele faz: montar peça sobre nossas bases, pesquisar jurisprudência citável, ler documento e extrair dado, revisar peça pronta, tirar dúvida de tese.',
        '',
        '## O que ele NÃO é',
        '',
        '- **Não é advogado.** A responsabilidade da peça é sua, com sua OAB.',
        '- **Não é fonte.** Jurisprudência que ele citar sem link de tribunal, você confere. Sempre.',
        '- **Não substitui a leitura dos autos.** Ele lê o que você sobe. O que você não subiu, ele não sabe.',
        '- **Não decide estratégia.** Tese, pedido e valor são decisão de advogado.',
        '',
        '## A regra de ouro do escritório',
        '',
        '> **Se existe skill para a tarefa, a skill manda. Improvisar é proibido.**',
        '',
        'As skills não são sugestão nem ponto de partida: são o procedimento. Cada regra dentro delas foi escrita depois de um erro medido em peça real. Contrariá-las por conta própria refaz exatamente os erros que elas existem para impedir.',
        '',
        '### O que isso proíbe, na prática',
        '',
        '1. **Escrever script próprio para o que a skill já faz.** Se a skill tem o programa de preencher, é ele que roda. Editar o arquivo na mão perde dezenas de acabamentos.',
        '2. **Pular passo da skill** porque "neste caso não parece necessário". O passo existe porque num caso pareceu desnecessário e deu errado.',
        '3. **Inventar regra nova** de forma ou estrutura que a skill não tem. Se a skill não cobre o caso, a resposta é **perguntar**, não deduzir.',
        '4. **Trocar de ferramenta no meio sem reler a skill.** Trocar o motor de montagem por outro faz perder negrito, fonte do corpo, citação em itálico, o azul da jurisprudência e as lacunas em amarelo.',
        '',
        '## Antes de entregar, sempre',
        '',
        '- Ler a skill inteira **antes** de tocar no arquivo, não depois que já deu errado.',
        '- Abrir a **base** daquela família de peça e comparar. A base é a fonte de verdade da forma.',
        '- Rodar a skill de revisão quando existir, e só entregar com a nota fechada.',
        '- **Nunca aceitar "aplicado com sucesso" como verificação.** Mensagem de programa diz que rodou, não que ficou certo.',
        '',
        '## Quando não souber',
        '',
        'Pergunte. Uma pergunta custa uma linha; um palpite custa uma peça refeita.',
      ].join('\n'),
      checklist: [
        'Entendi que a responsabilidade da peça é minha, não da IA.',
        'Sei que a skill é procedimento, não sugestão.',
        'Sei que "aplicado com sucesso" não é verificação.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos explicando o papel da inteligência artificial Claude no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado e estagiário que vão produzir peça com IA. Alguns vão chegar achando que a IA escreve a peça sozinha.',
        'TOM: firme e desmistificador, sem ser antitecnologia. Português do Brasil.',
        '',
        'ROTEIRO:',
        '1. O que o Claude faz no escritório: monta peça sobre nossas bases, pesquisa jurisprudência, lê documento, revisa, tira dúvida de tese.',
        '2. O que ele NÃO é, nos quatro pontos: não é advogado, não é fonte, não substitui a leitura dos autos, não decide estratégia.',
        '3. A regra de ouro, dita com todas as letras: se existe skill para a tarefa, a skill manda, improvisar é proibido. Explique que cada regra dentro da skill foi escrita depois de um erro medido em peça real.',
        '4. As quatro proibições práticas: escrever script próprio, pular passo, inventar regra nova, trocar de ferramenta no meio sem reler a skill.',
        '5. O checklist antes de entregar, incluindo a frase: nunca aceitar "aplicado com sucesso" como verificação, porque mensagem de programa diz que rodou, não que ficou certo.',
        '6. Feche com: quando não souber, pergunte. Uma pergunta custa uma linha, um palpite custa uma peça refeita.',
        '',
        'NÃO FAÇA: sugerir que a IA pode assinar ou responder pela peça; sugerir que dá para pular passo em caso simples.',
      ].join('\n'),
    },

    {
      id: 'skills',
      titulo: 'As skills do escritório: qual usar em cada peça',
      resumo: 'O mapa completo de qual procedimento chamar para cada situação.',
      minutos: 10,
      manual: [
        '## Como se chama uma skill',
        '',
        'Você descreve a tarefa em português. A skill certa é acionada sozinha quando você diz o que quer — "monta a inicial de RMC do fulano", "o banco recorreu, faz as contrarrazões", "saiu o laudo, monta a impugnação".',
        '',
        'Você **não** precisa decorar nomes. Precisa saber que existe uma para cada peça, e não aceitar peça montada fora delas.',
        '',
        '## Bancário — RMC e RCC',
        '',
        '- **Petição inicial** — escolhe a base pelo status do contrato: quitado (com repetição de indébito) ou em aberto (conversão e danos morais). Lê cálculo, procuração e justiça gratuita, preenche qualificação, comarca, banco réu e valores. Ao final, organiza a pasta e monta o pacote de protocolo.',
        '- **Réplica** — a partir da contestação.',
        '- **Especificação de provas** — lê a réplica já protocolada para decidir: se não pediu perícia, vira alegações finais com pedido de julgamento antecipado; se pediu, monta a especificação pertinente.',
        '- **Recurso**, **agravo de instrumento e agravo interno**, **embargos de declaração**.',
        '- **Contrarrazões** — quando quem recorreu foi a parte contrária.',
        '- **Cumprimento de sentença** — lê a sentença, o acórdão e o cálculo.',
        '- **Manifestação de alvará** e **arquivamento provisório** (art. 921, III).',
        '',
        '## Acidente de trabalho e doença ocupacional',
        '',
        '- **Triagem e viabilidade** — o caso é bom? tem NTEP? prescreveu? quem entra no polo passivo?',
        '- **Petição inicial** sobre a base real, com a escada da responsabilidade em três degraus.',
        '- **Quesitos** de perícia médica e ergonômica.',
        '- **Impugnação de laudo** pericial.',
        '- **Réplica**, **razões finais**, **recurso ordinário**, **recurso de revista**, **embargos de declaração**.',
        '- **Revisão de peça** antes de protocolar.',
        '',
        '## Transversais',
        '',
        '- **Timbrado** — aplica o timbrado oficial e mais atualizado em qualquer peça pronta do escritório, inclusive petições avulsas (desistência, resposta a custas, justificativa de ausência, audiência virtual, dispensa de conciliação).',
        '- **Pesquisa de jurisprudência citável** — busca em portais oficiais e entrega ementa formatada, pronta para colar.',
        '- **Revisão** — confere fundamentos, pedidos, prescrição, valor da causa, coerência entre prova e pedido, e a ética do art. 41.',
        '',
        '## A pergunta que você faz antes de começar',
        '',
        '**"Existe skill para isso?"** Se sim, use. Se não sabe, pergunte. Se não existe, é caso de conversar com a coordenação antes de improvisar — e provavelmente de criar a skill depois.',
      ].join('\n'),
      checklist: [
        'Sei que há skill para cada peça e não monto peça fora delas.',
        'Sei que a skill de especificação decide sozinha entre alegações finais e perícia lendo a réplica.',
        'Sei que existe skill de timbrado para peça avulsa.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos mapeando as skills do escritório Frider Andrade | Advogados no Claude.',
        '',
        'PÚBLICO: advogado que vai produzir peça e ainda não sabe o que existe pronto.',
        'TOM: de catálogo comentado, prático.',
        '',
        'ROTEIRO:',
        '1. Explique que a skill se aciona descrevendo a tarefa em português, e que ninguém precisa decorar nomes, mas precisa saber que existe uma para cada peça.',
        '2. Percorra o bloco bancário RMC e RCC: inicial com escolha de base entre contrato quitado e em aberto, réplica, especificação de provas, recurso, agravos, embargos, contrarrazões, cumprimento de sentença, alvará, arquivamento provisório. Destaque que a skill de especificação lê a réplica já protocolada para decidir entre alegações finais e perícia.',
        '3. Percorra o bloco de acidente de trabalho e doença ocupacional: triagem de viabilidade, inicial, quesitos, impugnação de laudo, réplica, razões finais, recurso ordinário, recurso de revista, embargos, revisão.',
        '4. Apresente as transversais: timbrado, pesquisa de jurisprudência citável e revisão.',
        '5. Feche com a pergunta que abre todo trabalho: existe skill para isso? Se não sabe, pergunte; se não existe, converse com a coordenação antes de improvisar.',
        '',
        'NÃO FAÇA: inventar nome de skill que não foi citada, prometer que a skill entrega peça pronta para protocolo.',
      ].join('\n'),
    },

    {
      id: 'inicial',
      titulo: 'Montando uma inicial de RMC/RCC do zero',
      resumo: 'O caminho completo: dados, cálculo, base, timbrado, pasta, protocolo.',
      minutos: 14,
      manual: [
        '## Antes de chamar a skill',
        '',
        'Tenha em mãos, na pasta do cliente:',
        '',
        '1. **Documento pessoal e comprovante de residência.**',
        '2. **Procuração assinada** (ZapSign) e contrato de honorários.',
        '3. **HISCON e HISCRE** — o histórico de consignações e de créditos do INSS.',
        '4. **Extrato do benefício** com os descontos.',
        '5. **Contrato do banco**, se houver.',
        '6. **Justiça gratuita** — histórico de créditos ou declaração de imposto de renda.',
        '7. **Cálculo salvo no processo.**',
        '',
        '> Faltando o cálculo, a inicial sai sem valor da causa. Faltando o JG, sai sem o pedido de gratuidade instruído. Junte tudo antes.',
        '',
        '## A escolha da base',
        '',
        'A skill escolhe a base pelo **status do contrato**:',
        '',
        '- **Quitado** → base com **repetição de indébito** (devolução do que foi descontado).',
        '- **Em aberto** → base de **conversão** do cartão em empréstimo consignado comum + danos morais.',
        '',
        'Essa escolha muda pedido, cálculo e valor da causa. Confira se a skill acertou o status antes de seguir.',
        '',
        '## O que a skill faz',
        '',
        '1. Lê o cálculo, a procuração e o comprovante de gratuidade.',
        '2. Preenche qualificação do cliente, comarca, vara, banco réu e valores.',
        '3. Monta a peça **sobre a base pronta no timbrado** — não redige do zero.',
        '4. Organiza a pasta do cliente e monta o pacote de protocolo.',
        '',
        '## O que VOCÊ faz depois',
        '',
        '- **Conferir a qualificação** — nome completo, CPF, endereço, benefício. Erro aqui gera emenda.',
        '- **Conferir a comarca e a vara** — foro do domicílio do consumidor.',
        '- **Ler os fatos** — a narrativa tem que bater com o que os documentos provam.',
        '- **Conferir o valor da causa** contra o cálculo salvo.',
        '- **Preencher as lacunas** marcadas em amarelo. Peça com lacuna protocolada é vexame.',
        '- **Conferir o timbrado** — logo, cabeçalho, fontes, fechamento com assinatura.',
        '',
        '## Protocolo',
        '',
        'PJe, e-SAJ ou Projudi, conforme o tribunal. Guarde o número do processo e o comprovante. Depois: cadastro no hub, cálculo salvo no processo, etiquetas, responsável, e a peça arquivada na pasta do cliente.',
        '',
        '## O prazo',
        '',
        '**5 dias úteis** para montar todas as ações de um cliente distribuído a você. Atrasou, o caso é redistribuído.',
      ].join('\n'),
      checklist: [
        'Sei a lista de documentos que a inicial exige.',
        'Sei que a base muda conforme o contrato esteja quitado ou em aberto.',
        'Confiro qualificação, comarca, fatos, valor e lacunas antes de protocolar.',
        'Cadastro o processo no hub logo depois do protocolo.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos ensinando a montar uma petição inicial de RMC ou RCC no escritório Frider Andrade | Advogados usando a skill do Claude.',
        '',
        'PÚBLICO: advogado associado que vai montar a primeira inicial.',
        'TOM: passo a passo, de bancada, com alertas nos pontos de erro.',
        '',
        'ROTEIRO:',
        '1. A lista do que precisa estar na pasta antes de chamar a skill: documento pessoal, comprovante de residência, procuração e contrato, HISCON e HISCRE, extrato do benefício, contrato do banco, comprovante de gratuidade e o cálculo salvo. Alerte que sem cálculo a inicial sai sem valor da causa.',
        '2. A escolha da base pelo status do contrato: quitado leva a repetição de indébito, em aberto leva a conversão do cartão em consignado comum mais danos morais. Explique que isso muda pedido, cálculo e valor da causa, e que é preciso conferir se a skill acertou o status.',
        '3. O que a skill faz: lê os documentos, preenche qualificação, comarca, vara, banco réu e valores, monta sobre a base pronta no timbrado, organiza a pasta e monta o pacote de protocolo. Frise que ela preenche uma base, não redige do zero.',
        '4. As seis conferências humanas: qualificação, comarca e vara, coerência dos fatos com os documentos, valor da causa contra o cálculo, lacunas em amarelo e o timbrado.',
        '5. O protocolo e o pós-protocolo: guardar número e comprovante, cadastrar no hub, salvar cálculo, etiquetar, atribuir responsável e arquivar a peça na pasta.',
        '6. Feche com o prazo de 5 dias úteis e a regra de redistribuição.',
        '',
        'NÃO FAÇA: sugerir protocolar sem preencher as lacunas; prometer êxito na ação.',
      ].join('\n'),
    },

    {
      id: 'pecas-resposta',
      titulo: 'Réplica, especificação de provas e recurso',
      resumo: 'As peças de resposta, pelo hub ou pela skill — e a diferença entre as duas vias.',
      minutos: 12,
      manual: [
        '## Duas vias, propósitos diferentes',
        '',
        '### Pelo hub (Agenda ou ficha do processo)',
        '',
        'Rápido, para quando você quer um rascunho já no timbrado, anexado ao processo. Você sobe a contestação (para réplica), a réplica (para especificação) ou a sentença (para recurso), escolhe o produto e gera.',
        '',
        'Leva 1 a 2 minutos com vários PDFs. Sai um **rascunho redigido por IA** encaixado no timbrado.',
        '',
        '### Pela skill no Claude',
        '',
        'Mais completo: a skill escolhe o modelo certo dentro da biblioteca, aplica os acabamentos do escritório e roda a checagem própria. É o caminho preferencial quando a peça é sensível.',
        '',
        '> As duas vias existem porque a skill lê a biblioteca de modelos, que não está no servidor do hub. Quando der para usar a skill, use a skill.',
        '',
        '## Réplica',
        '',
        'Sobe a contestação. O que você confere depois:',
        '',
        '- Toda preliminar da contestação foi enfrentada?',
        '- Todo documento novo juntado pelo réu foi impugnado ou reconhecido?',
        '- Os pontos da inicial que o réu **não** impugnou foram destacados?',
        '- Pediu as provas que você vai precisar?',
        '',
        '## Especificação de provas',
        '',
        'A regra do escritório: **lê-se a réplica já protocolada** para decidir.',
        '',
        '- A réplica **não** pediu perícia → alegações finais com **pedido de julgamento antecipado**, reforçando as teses (assinatura relâmpago, contrato sem certificação ICP-Brasil, faturas sem compras, ausência de uso, prova emprestada, laudo do assistente técnico).',
        '- A réplica **pediu** perícia → especificação pertinente ao tipo: contrato digital, contrato físico, perícia de áudio ou perícia contábil.',
        '',
        '## Recurso',
        '',
        'Sobe a sentença ou o acórdão. Antes de recorrer:',
        '',
        '1. **Vale a pena?** Sentença parcialmente favorável pode ser melhor que o risco do recurso.',
        '2. **Qual recurso cabe?** Metade do problema é acertar isso.',
        '3. **Tempestividade e preparo** — deserção mata recurso bom.',
        '4. **Prequestionamento**, se o horizonte for tribunal superior.',
        '',
        '## O que nunca muda',
        '',
        'Peça gerada por IA é **rascunho**. Revise tese por tese, confira as lacunas e leia em voz alta o pedido antes de protocolar.',
      ].join('\n'),
      checklist: [
        'Sei quando usar o gerador do hub e quando usar a skill.',
        'Sei a regra que decide entre alegações finais e perícia.',
        'Confiro tempestividade e preparo antes de qualquer recurso.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre as peças de resposta no escritório Frider Andrade | Advogados: réplica, especificação de provas e recurso.',
        '',
        'PÚBLICO: advogado associado conduzindo processo em curso.',
        'TOM: técnico e decisório.',
        '',
        'ROTEIRO:',
        '1. Explique as duas vias de produção: o gerador dentro do Hub, rápido, que devolve rascunho no timbrado anexado ao processo em 1 a 2 minutos; e a skill no Claude, mais completa, que escolhe o modelo na biblioteca e roda checagem própria. Diga que quando der para usar a skill, use a skill.',
        '2. Réplica: sobe a contestação e confere quatro coisas — toda preliminar enfrentada, todo documento novo impugnado, os pontos não impugnados pelo réu destacados, e as provas requeridas.',
        '3. Especificação de provas e a regra do escritório: lê-se a réplica já protocolada. Se ela não pediu perícia, vira alegações finais com pedido de julgamento antecipado, reforçando as teses de assinatura relâmpago, contrato sem certificação ICP-Brasil, faturas sem compras e ausência de uso. Se pediu, monta a especificação pertinente ao tipo de perícia.',
        '4. Recurso: as quatro perguntas antes de recorrer — vale a pena, qual recurso cabe, tempestividade e preparo, e prequestionamento se o horizonte for tribunal superior.',
        '5. Feche com a regra invariável: peça gerada por IA é rascunho, revisa-se tese por tese e lê-se o pedido em voz alta antes de protocolar.',
        '',
        'NÃO FAÇA: dar a entender que a especificação pode ser decidida sem ler a réplica.',
      ].join('\n'),
    },

    {
      id: 'jurisprudencia',
      titulo: 'Pesquisa de jurisprudência citável',
      resumo: 'Como achar julgado que sustenta a tese — e como não citar acórdão que não existe.',
      minutos: 8,
      manual: [
        '## Como pedir',
        '',
        'Descreva a tese e o tribunal desejado: "acha jurisprudência do TJPR sobre conversão de RMC em empréstimo consignado comum", "preciso de STJ sobre repetição de indébito em cartão consignado".',
        '',
        'A skill busca em portais oficiais de tribunais — TJs, TRFs, TRTs, STJ, STF, TST, CJF — e devolve **ementas já formatadas**, prontas para colar na peça.',
        '',
        '## A regra inegociável',
        '',
        '> **Toda citação vai com número do acórdão, relator, órgão julgador e data. Se você não consegue abrir o julgado no site do tribunal, ele não entra na peça.**',
        '',
        'IA generalista inventa acórdão convincente. Já houve advogado punido no Brasil por citar precedente inexistente. Conferir é obrigação sua, não da máquina.',
        '',
        '## Hierarquia do que convence',
        '',
        '1. **Vinculante** — súmula vinculante, repetitivo do STJ, repercussão geral do STF, IRDR e IAC do próprio tribunal.',
        '2. **Do tribunal que vai julgar** — acórdão da câmara em que seu processo está.',
        '3. **Do mesmo tribunal**, outra câmara.',
        '4. **De outros tribunais** — reforço, não sustentação.',
        '',
        '## Como usar na peça',
        '',
        '- **Poucas e boas.** Três ementas certeiras valem mais que doze coladas.',
        '- **Amarre ao caso.** Depois da ementa, uma frase dizendo por que aquele julgado decide o seu caso.',
        '- **Formato do escritório** — jurisprudência sai no padrão da base (destaque em azul, citação em itálico). Não invente formatação.',
        '',
        '## Quando o julgado é contra',
        '',
        'Se há tese vinculante contrária, não finja que não existe. Ou você faz **distinguishing** (mostra que o seu caso é diferente), ou pede a superação, ou ajusta o pedido. Ignorar tese vinculante é perder com custo.',
      ].join('\n'),
      checklist: [
        'Nunca cito acórdão que não consegui abrir no site do tribunal.',
        'Sei a ordem de força dos precedentes.',
        'Amarro cada ementa ao caso com uma frase.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre pesquisa de jurisprudência no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado e estagiário que fundamentam peça.',
        'TOM: técnico, com um alerta forte no meio.',
        '',
        'ROTEIRO:',
        '1. Como pedir a pesquisa: descrever a tese e o tribunal. A skill busca em portais oficiais e devolve ementas formatadas prontas para colar.',
        '2. A regra inegociável, com peso: toda citação vai com número do acórdão, relator, órgão julgador e data, e se não abre no site do tribunal, não entra na peça. Explique que IA generalista inventa acórdão convincente e que já houve advogado punido no Brasil por citar precedente inexistente.',
        '3. A hierarquia do que convence: vinculante, depois o tribunal que vai julgar, depois o mesmo tribunal em outra câmara, depois outros tribunais como reforço.',
        '4. Como usar na peça: poucas e boas, amarrar cada ementa ao caso com uma frase, e respeitar a formatação da base do escritório.',
        '5. O que fazer quando o precedente é contra: distinguishing, pedido de superação ou ajuste do pedido. Nunca fingir que não existe.',
        '',
        'NÃO FAÇA: sugerir citar julgado sem conferir; ensinar a esconder precedente contrário.',
      ].join('\n'),
    },

    {
      id: 'timbrado',
      titulo: 'Timbrado, Word e formatação',
      resumo: 'A peça do escritório tem cara. Como não estragar.',
      minutos: 8,
      manual: [
        '## O timbrado é procedimento, não estética',
        '',
        'A skill de timbrado aplica o modelo oficial e mais atualizado do escritório: logo, endereçamento, tabela do processo, fontes, formatação do corpo e o fechamento com a assinatura dos sócios.',
        '',
        'Use sempre que uma peça estiver pronta e precisar sair no padrão — inclusive petições avulsas que não têm skill própria: desistência, resposta a custas, justificativa de ausência, gratuidade já documentada, procuração, audiência virtual, dispensa de conciliação.',
        '',
        '## O erro que mais custou retrabalho',
        '',
        '> Trocar o motor de montagem por outro no meio do caminho faz **perder todos os acabamentos**: negrito, fonte do corpo, citação em itálico, o azul da jurisprudência e as lacunas em amarelo.',
        '',
        'Se a troca for mesmo necessária, os acabamentos perdidos têm de ser rodados à parte — e conferidos um a um.',
        '',
        '## Como se confere formatação',
        '',
        '**No arquivo, não no PDF.** O PDF confirma, não diagnostica.',
        '',
        'Cuidado com negrito: a fonte tem uma face própria de negrito, que desenha negrito sem a marcação. Conferir só a marcação deixa passar erro — foi assim que já passou batido.',
        '',
        '## Fontes',
        '',
        'O escritório usa **Tasman** e **Sole Sans**. Elas ficam no acervo de tutoriais e precisam estar instaladas na sua máquina, senão o Word troca por outra e a peça sai desalinhada.',
        '',
        '## Macro de negrito',
        '',
        'Há uma macro pronta no acervo para aplicar negrito no padrão da peça. Use-a em vez de sair marcando na mão.',
        '',
        '## Copiar e colar',
        '',
        'Texto colado de PDF ou de site vem com formatação do lugar de origem. Cole **sem formatação** e depois aplique o padrão da base. Colar direto é a origem mais comum de peça com três fontes diferentes.',
      ].join('\n'),
      acervo: {
        titulo: 'Acervo — Word, fontes, jurisprudência, legislação e macro de negrito',
        url: 'https://drive.google.com/drive/folders/1Ja7_8zirC55f_J3--UpRL0gP9UlNPNO_',
      },
      checklist: [
        'Instalei as fontes Tasman e Sole Sans.',
        'Sei que confiro formatação no arquivo, não no PDF.',
        'Colo texto sem formatação e depois aplico o padrão.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre o timbrado e a formatação das peças do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: quem produz peça, inclusive estagiário.',
        'TOM: de padrão de qualidade, mostrando que forma aqui é procedimento.',
        '',
        'ROTEIRO:',
        '1. Explique que existe uma skill de timbrado que aplica o modelo oficial e mais atualizado, e que ela serve inclusive para petições avulsas sem skill própria, citando exemplos como desistência, resposta a custas e dispensa de conciliação.',
        '2. Conte o erro que mais custou retrabalho: trocar o motor de montagem no meio do caminho faz perder negrito, fonte do corpo, citação em itálico, azul da jurisprudência e lacunas em amarelo. Se a troca for necessária, os acabamentos precisam ser rodados à parte e conferidos um a um.',
        '3. Ensine a conferir no arquivo, não no PDF, e explique a armadilha do negrito: a fonte tem face própria de negrito que desenha negrito sem a marcação, então conferir só a marcação deixa passar erro.',
        '4. As fontes Tasman e Sole Sans precisam estar instaladas na máquina.',
        '5. A macro de negrito e a regra de colar sem formatação, que evita peça com três fontes diferentes.',
        '',
        'NÃO FAÇA: tratar formatação como detalhe estético dispensável.',
      ].join('\n'),
    },

    {
      id: 'revisao',
      titulo: 'A revisão antes de protocolar',
      resumo: 'O que a IA erra com mais frequência e como pegar antes do juiz.',
      minutos: 10,
      manual: [
        '## Rode a skill de revisão',
        '',
        'Existe skill de revisão para as famílias principais. Ela confere fundamentos, pedidos, prescrição, valor da causa, coerência entre prova e pedido, e a ética do art. 41. **Só entregue com a nota fechada.**',
        '',
        '## O que a IA erra com mais frequência',
        '',
        '1. **Qualificação** — nome incompleto, CPF trocado, endereço velho, número de benefício errado.',
        '2. **Datas** — período do desconto, data do contrato, marco da prescrição.',
        '3. **Valor** — valor da causa que não bate com o cálculo salvo.',
        '4. **Pedido genérico** — pedido que não fecha com a causa de pedir, ou pedido que ficou de fora.',
        '5. **Jurisprudência não conferida.**',
        '6. **Lacuna não preenchida** — os campos em amarelo.',
        '7. **Excesso** — pedir mais do que a tese sustenta.',
        '8. **Promessa de resultado** no texto voltado ao cliente.',
        '',
        '## O roteiro de leitura final',
        '',
        '1. Ler **os pedidos primeiro**, isolados. Eles fazem sentido sozinhos?',
        '2. Voltar aos fatos e conferir se cada pedido tem fato e prova que o sustente.',
        '3. Conferir qualificação contra o documento, campo por campo.',
        '4. Conferir valor da causa contra o cálculo salvo.',
        '5. Abrir cada julgado citado no site do tribunal.',
        '6. Buscar no arquivo por colchete, por marca de lacuna e por "XXX".',
        '7. Conferir o timbrado.',
        '8. Ler o cabeçalho: juízo, comarca, número do processo, partes.',
        '',
        '## A pergunta final',
        '',
        '> Se o juiz ler só os pedidos e o cabeçalho, ele entende o que eu quero e de quem?',
        '',
        'Se a resposta for não, a peça não está pronta — por mais bonito que esteja o meio.',
      ].join('\n'),
      checklist: [
        'Rodo a skill de revisão quando existe.',
        'Leio os pedidos isolados antes de tudo.',
        'Busco lacunas por marca de texto antes de fechar.',
        'Abro cada julgado citado.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre a revisão obrigatória antes de protocolar uma peça no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado que acabou de gerar uma peça com IA e está com o dedo no botão de protocolar.',
        'TOM: de checklist de segurança, como piloto antes de decolar.',
        '',
        'ROTEIRO:',
        '1. Diga que existe skill de revisão para as famílias principais, que ela confere fundamentos, pedidos, prescrição, valor da causa, coerência entre prova e pedido e a ética do artigo 41, e que só se entrega com a nota fechada.',
        '2. Liste os oito erros mais frequentes da IA: qualificação, datas, valor, pedido genérico, jurisprudência não conferida, lacuna não preenchida, excesso e promessa de resultado.',
        '3. Ensine o roteiro de leitura final em oito passos, começando por ler os pedidos isolados.',
        '4. Feche com a pergunta final: se o juiz ler só os pedidos e o cabeçalho, ele entende o que eu quero e de quem? Se a resposta for não, a peça não está pronta.',
        '',
        'NÃO FAÇA: sugerir revisão por amostragem em peça de rotina.',
      ].join('\n'),
    },

    {
      id: 'etica-ia',
      titulo: 'IA e dados de cliente: o que pode e o que não pode',
      resumo: 'Sigilo profissional e LGPD dentro da ferramenta que você usa todo dia.',
      minutos: 7,
      manual: [
        '## O princípio',
        '',
        'Dado de cliente é **sigilo profissional** (Estatuto da Advocacia) e **dado pessoal** (LGPD). Usar IA não suspende nenhum dos dois.',
        '',
        '## Pode',
        '',
        '- Subir documentos do caso nas ferramentas **do escritório** (hub e Claude configurado pelo escritório) — é tratamento de dado para execução do contrato com o cliente.',
        '- Pedir análise, resumo, peça e pesquisa sobre esses documentos.',
        '',
        '## Não pode',
        '',
        '- Colar dado de cliente em IA pública pessoal (conta particular, ferramenta aleatória da internet).',
        '- Mandar documento de cliente para grupo de WhatsApp, colega de fora ou nuvem pessoal.',
        '- Usar caso real, com nome, em exemplo público, post ou aula, sem autorização.',
        '- Guardar cópia de documento de cliente no seu computador pessoal fora da estrutura do escritório.',
        '',
        '## Depoimento e uso de imagem',
        '',
        'Depoimento de cliente e resultado só viram material de marketing com autorização e dentro do que o Provimento da OAB sobre publicidade permite. Mural interno de conquistas é uso interno. Post é decisão do Marketing.',
        '',
        '## Nunca prometa resultado',
        '',
        '> **Código de Ética da OAB, art. 41.** Não se promete resultado, nem para o cliente, nem em anúncio, nem no texto que a IA escreveu e você não leu.',
        '',
        'A linguagem certa é de objetivo e possibilidade: "o que buscamos é", "o objetivo da ação é", "você pode ter direito a". Nunca "você vai receber", "é certo que", "garantimos".',
        '',
        '## Se vazou',
        '',
        'Avise a coordenação **na hora**. Incidente com dado pessoal tem prazo curto de comunicação e a demora piora tudo. Ninguém aqui é punido por avisar cedo.',
      ].join('\n'),
      checklist: [
        'Só uso as ferramentas de IA do escritório com dado de cliente.',
        'Sei a diferença entre linguagem de objetivo e promessa de resultado.',
        'Sei que aviso a coordenação na hora se houver vazamento.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre uso de inteligência artificial com dados de cliente no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: todos que lidam com documento de cliente.',
        'TOM: sério e claro, sem juridiquês.',
        '',
        'ROTEIRO:',
        '1. O princípio: dado de cliente é sigilo profissional pelo Estatuto da Advocacia e dado pessoal pela LGPD, e usar IA não suspende nenhum dos dois.',
        '2. O que pode: subir documento nas ferramentas do escritório, hub e Claude configurado pelo escritório, e pedir análise, peça e pesquisa sobre eles.',
        '3. O que não pode: colar dado de cliente em IA pública pessoal, mandar documento para grupo de WhatsApp ou nuvem pessoal, usar caso real com nome em exemplo público, guardar cópia fora da estrutura do escritório.',
        '4. Depoimento e imagem de cliente só com autorização e dentro das regras de publicidade da OAB; mural interno é uso interno e post é decisão do Marketing.',
        '5. A regra do artigo 41 do Código de Ética: nunca prometer resultado. Ensine a linguagem certa, de objetivo e possibilidade, contra a linguagem errada de garantia.',
        '6. Feche com o protocolo de vazamento: avisar a coordenação na hora, porque o prazo de comunicação é curto e a demora piora tudo, e ninguém é punido por avisar cedo.',
        '',
        'NÃO FAÇA: dar exemplo com nome real de cliente; sugerir que basta anonimizar para usar IA pessoal.',
      ].join('\n'),
    },
  ],
};
