import type { Trilha } from '../types';

export const PRAZOS: Trilha = {
  id: 'prazos',
  titulo: 'Prazos e controladoria',
  subtitulo: 'A obrigação número um do regimento',
  icone: 'CalendarClock',
  cor: '#F08C00',
  publico: 'Advogados, estagiários e controladoria.',
  aulas: [
    {
      id: 'como-chega',
      videoPlanejado: true,
      video: {
        fonte: 'url',
        url: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/como-chega.mp4',
        legendas: 'https://api.friderandrade.com.br/api/v1/uploads/assets/academia/como-chega.vtt',
        duracao: '2:52',
      },
      titulo: 'Como o prazo chega até você',
      resumo: 'DJEN, portal do tribunal, Projudi e as armadilhas de cada caminho.',
      minutos: 10,
      manual: [
        '## As fontes',
        '',
        '- **DJEN** — o Diário de Justiça Eletrônico Nacional, criado pela Resolução 455/2022 do CNJ. É a fonte principal. O hub lê o DJEN todo dia e classifica o que chega.',
        '- **Portal do tribunal (intimação eletrônica)** — em muitos sistemas a intimação se dá no portal, com regra de prazo própria: se você não abrir, ela se considera lida em 10 dias corridos.',
        '- **Projudi** — no Paraná, muitas publicações são só **ponteiro**: avisam que houve ato, sem trazer o teor. Há uma rotina de vigilância que varre o Projudi algumas vezes por dia.',
        '- **Citação e intimação por oficial/carta** — chegam ao cliente ou ao escritório físico.',
        '',
        '## A armadilha do ponteiro',
        '',
        '> Cerca de um quarto das publicações não traz o teor do ato. O card recebe um selo de **ato cego**: significa "houve algo aqui, e ninguém sabe o quê".',
        '',
        'Ato cego não é prazo tratado. É pedido de abrir os autos e ver o que aconteceu — hoje, não amanhã.',
        '',
        '## A armadilha dos 10 dias',
        '',
        'Intimação disponibilizada no portal e não aberta se considera realizada no fim do prazo de consulta. Se você deixar acumular, o prazo pode já estar correndo há dias quando você abrir.',
        '',
        '## O que o classificador faz por você',
        '',
        'Lê o teor, identifica o ato (sentença, despacho, intimação para réplica, especificação de provas, designação de audiência, acórdão), calcula o prazo, cria o item na Agenda e move o card do kanban.',
        '',
        '## O que ele não faz',
        '',
        '- Não abre autos. Publicação sem teor continua cega.',
        '- Não sabe da sua estratégia.',
        '- Não decide se o prazo é seu ou da parte contrária em caso ambíguo.',
        '',
        '## Sua rotina',
        '',
        '**Todo dia, no mesmo horário**, trate as publicações até zerar. Não deixe acumular: publicação acumulada é a origem de quase toda perda de prazo.',
        '',
        '> O manual do associado é explícito: as publicações devem ser verificadas e tratadas diariamente, sem exceções.',
      ].join('\n'),
      checklist: [
        'Tenho horário fixo diário para tratar publicação.',
        'Sei o que é ato cego e o que fazer com ele.',
        'Sei que intimação não aberta no portal se considera lida em 10 dias.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre como um prazo processual chega até o advogado no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado que vai assumir a própria controladoria.',
        'TOM: sério e didático, é o tema em que erro custa mais caro.',
        '',
        'ROTEIRO:',
        '1. As fontes: DJEN como fonte principal, portal do tribunal, Projudi e as intimações por oficial ou carta.',
        '2. A armadilha do ponteiro: cerca de um quarto das publicações não traz o teor, e o card ganha selo de ato cego, que significa "houve algo aqui e ninguém sabe o quê". A instrução é abrir os autos hoje, não amanhã.',
        '3. A armadilha dos 10 dias. DIGA O NÚMERO EM VOZ ALTA: intimação disponibilizada no portal e não aberta se considera lida em 10 DIAS CORRIDOS. Quem acumula descobre o prazo já correndo há dias. O número é o conteúdo desta parte — não o substitua por "ao fim do prazo de consulta".',
        '4. O que o classificador faz: lê o teor, identifica o ato, calcula prazo, cria item na agenda e move o card.',
        '5. O que ele não faz: não abre autos, não conhece a estratégia, não resolve ambiguidade sobre de quem é o prazo.',
        '6. Feche com a rotina: todo dia, mesmo horário, tratar até zerar. Cite que o manual do associado exige tratamento diário sem exceções.',
        '',
        'NÃO FAÇA: passar a ideia de que o sistema cuida do prazo sozinho.',
      ].join('\n'),
    },

    {
      id: 'contagem',
      titulo: 'Contagem de prazo: as regras que se erra',
      resumo: 'Dias úteis, termo inicial, dobro, feriados e recesso.',
      minutos: 12,
      manual: [
        '## As regras básicas do processo civil',
        '',
        '- **Dias úteis** — no processo civil, prazo em dias conta-se apenas em dias úteis (art. 219 do CPC). Atenção: no processo penal e em boa parte do processo do trabalho a contagem é diferente.',
        '- **Termo inicial** — o prazo começa a correr no **primeiro dia útil seguinte** à data em que se considera feita a intimação (art. 224, §§ 2º e 3º).',
        '- **Intimação eletrônica** — considera-se realizada no dia da consulta, ou no fim do prazo de consulta se não houver acesso. A publicação em diário se considera feita no primeiro dia útil seguinte à disponibilização.',
        '- **Prazo em dobro** — Fazenda Pública (art. 183), Ministério Público (art. 180), Defensoria (art. 186) e litisconsortes com procuradores diferentes em autos físicos (art. 229).',
        '- **Suspensão** — de 20 de dezembro a 20 de janeiro os prazos ficam suspensos (art. 220).',
        '',
        '## Feriados que derrubam contagem',
        '',
        'Além dos feriados nacionais, contam **os feriados forenses do tribunal** e os **feriados municipais** da comarca. Um feriado local que você não conhece é o jeito mais bobo de perder prazo.',
        '',
        '> O hub calcula considerando dias úteis, feriados e recesso. Ainda assim, confira: o cálculo automático não conhece um feriado municipal recém-criado.',
        '',
        '## Prazos que mais aparecem aqui',
        '',
        '- Contestação: 15 dias úteis.',
        '- Réplica: 15 dias úteis.',
        '- Especificação de provas: conforme o despacho (em geral 5 a 15 dias).',
        '- Embargos de declaração: 5 dias úteis.',
        '- Apelação e contrarrazões: 15 dias úteis.',
        '- Agravo de instrumento: 15 dias úteis.',
        '- Recurso inominado no juizado: 10 dias.',
        '- Cumprimento de sentença — pagamento voluntário: 15 dias.',
        '',
        '> Prazo de juizado especial tem regra própria e nem sempre é em dias úteis. Confira a lei do juizado antes de aplicar a contagem do CPC.',
        '',
        '## Como conferir sem erro',
        '',
        '1. Achar a **data da disponibilização** e a data da **publicação**.',
        '2. Achar o **primeiro dia útil seguinte** à publicação — é o dia 1.',
        '3. Contar só dias úteis, pulando feriado nacional, forense e municipal.',
        '4. Verificar se cabe dobro.',
        '5. Verificar se atravessa o recesso.',
        '6. Anotar a data fatal e recuar a régua de lembretes.',
        '',
        '## A margem',
        '',
        'Trabalhe para protocolar **no penúltimo dia útil**. O último dia é reserva para o sistema do tribunal cair — e ele cai.',
      ].join('\n'),
      checklist: [
        'Sei achar o dia 1 de um prazo a partir da disponibilização.',
        'Confiro feriado forense e municipal, não só nacional.',
        'Trabalho com a meta do penúltimo dia útil.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos ensinando contagem de prazo processual, no padrão do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado e estagiário. Alguns nunca contaram prazo sozinhos.',
        'TOM: professoral e paciente, com exemplo numérico.',
        '',
        'ROTEIRO:',
        '1. As regras básicas do CPC: contagem em dias úteis pelo artigo 219, termo inicial no primeiro dia útil seguinte pelo artigo 224, regra da intimação eletrônica, prazos em dobro para Fazenda, Ministério Público, Defensoria e litisconsortes com procuradores diferentes, e a suspensão de 20 de dezembro a 20 de janeiro. Avise que processo penal e trabalhista têm contagem diferente.',
        '2. Feriados: além dos nacionais, contam os forenses do tribunal e os municipais da comarca. Diga que feriado local desconhecido é o jeito mais bobo de perder prazo, e que o cálculo automático pode não conhecer feriado municipal recém-criado.',
        '3. Percorra a lista dos prazos mais comuns no escritório, avisando que juizado especial tem regra própria.',
        '4. Ensine o roteiro de conferência em seis passos, com um exemplo numérico real, do tipo publicação numa segunda-feira com feriado na quarta.',
        '5. Feche com a margem: protocolar no penúltimo dia útil, porque o último é reserva para o sistema do tribunal cair.',
        '',
        'NÃO FAÇA: dar tabela de prazo como se valesse para todo rito sem ressalva.',
      ].join('\n'),
    },

    {
      id: 'regua',
      titulo: 'A régua D-7, D-3, D-1 e D-0',
      resumo: 'Como transformar uma data fatal em trabalho distribuído.',
      minutos: 7,
      manual: [
        '## Por que régua',
        '',
        'Prazo perdido raramente é esquecimento no dia. É **acúmulo**: a pessoa lembrava, mas só ia começar amanhã, e amanhã virou o dia do prazo com o cliente sem documento.',
        '',
        'A régua desfaz isso: cada prazo vira quatro compromissos, não um.',
        '',
        '## A régua',
        '',
        '- **D-7 — abrir o trabalho.** Ler a decisão inteira, listar o que falta (documento do cliente, cálculo, laudo), pedir o que falta. É o dia de descobrir problema, não de escrever.',
        '- **D-3 — a peça existe.** Rascunho montado (skill ou gerador), revisado por você. Se ainda não existe rascunho no D-3, isto é um alerta: avise a coordenação hoje.',
        '- **D-1 — revisão final e protocolo.** Meta: protocolar aqui.',
        '- **D-0 — reserva.** Só existe para imprevisto. Se você está usando o D-0 com frequência, sua régua está atrasada em três dias.',
        '',
        '## Prazos curtos',
        '',
        'Em prazo de 5 dias (embargos de declaração, por exemplo), a régua comprime: D-4 abrir, D-2 peça pronta, D-1 protocolar.',
        '',
        '## Onde a régua mora',
        '',
        'Na **Agenda do hub**. O prazo já nasce com a data fatal; você cria as tarefas intermediárias com dono e data. Tarefa sem dono não é feita.',
        '',
        '## O sinal de alarme',
        '',
        '> Se no D-3 a peça não existe, o problema já não é seu sozinho. **Avise.** A coordenação consegue realocar em D-3. Em D-0, não consegue.',
      ].join('\n'),
      checklist: [
        'Todo prazo meu tem tarefas em D-7, D-3 e D-1.',
        'Sei que D-0 é reserva, não plano.',
        'Aviso a coordenação quando a peça não existe no D-3.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre a régua de prazos do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado com carteira própria.',
        'TOM: de método, quase de coaching operacional, mas seco.',
        '',
        'ROTEIRO:',
        '1. Comece com o diagnóstico: prazo perdido raramente é esquecimento no dia, é acúmulo. A pessoa lembrava, mas ia começar amanhã.',
        '2. Apresente a régua: D-7 abrir o trabalho e descobrir o que falta, D-3 a peça já existe em rascunho revisado, D-1 revisão final e protocolo, D-0 apenas reserva.',
        '3. Explique a compressão da régua em prazos de 5 dias.',
        '4. Diga que a régua mora na Agenda do hub e que tarefa sem dono não é feita.',
        '5. Feche com o sinal de alarme: se no D-3 a peça não existe, avise, porque a coordenação consegue realocar em D-3 e não consegue em D-0.',
        '',
        'NÃO FAÇA: sugerir que dá para deixar tudo para o último dia se a pessoa for rápida.',
      ].join('\n'),
    },

    {
      id: 'quando-nao-da',
      titulo: 'Quando você não vai dar conta',
      resumo: 'O procedimento que transforma um problema em contratempo, e não em falha.',
      minutos: 6,
      manual: [
        '## A regra do escritório',
        '',
        '> Problemas profissionais fazem parte da advocacia, mas seus impactos podem ser minimizados com comunicação adequada. **A ausência de comunicação transforma um problema contornável em falha irreversível.**',
        '',
        '## O procedimento',
        '',
        '1. **Identifique cedo.** Doença, sobreposição de audiência, cliente que não manda documento, cálculo que não fecha, volume acima do que cabe na semana.',
        '2. **Comunique à coordenação imediatamente**, com o quadro completo: qual processo, qual prazo, qual a data fatal, o que já está feito, o que falta e o que você precisa.',
        '3. **Proponha a solução** que você enxerga: realocar a peça, pedir dilação, priorizar A em vez de B.',
        '4. **Combine e execute** o que for acordado.',
        '',
        '## O que não fazer',
        '',
        '- Sumir.',
        '- Avisar no dia do prazo.',
        '- Protocolar peça ruim só para dizer que protocolou.',
        '- Prometer ao cliente algo que compensaria o atraso.',
        '',
        '## Audiência',
        '',
        'A tolerância para audiência perdida é **zero**. Se houver qualquer risco de não comparecer, avise com a maior antecedência: dá para substabelecer, pedir adiamento ou mandar preposto, mas nada disso se faz de véspera.',
        '',
        '## Se o prazo já foi perdido',
        '',
        'Avise **na hora**, sem rodeio. O que se avalia em seguida:',
        '',
        '1. Cabe alguma medida (embargos, recurso, pedido de devolução de prazo por justa causa)?',
        '2. Qual o dano real ao cliente?',
        '3. O cliente precisa ser comunicado — e quem comunica.',
        '',
        'Esconder é o que transforma um prazo perdido em responsabilidade civil e problema disciplinar. Avisar cedo quase sempre deixa alguma saída.',
      ].join('\n'),
      checklist: [
        'Sei exatamente o que informar quando algo vai atrasar.',
        'Sei que audiência tem tolerância zero e avisa-se com antecedência.',
        'Sei que prazo perdido se comunica na hora.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre o que fazer quando não se vai dar conta de um prazo, no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado sob pressão. O vídeo precisa reduzir o medo de avisar.',
        'TOM: adulto e acolhedor, sem passar a mão na cabeça.',
        '',
        'ROTEIRO:',
        '1. Comece pela regra do escritório: problemas fazem parte da advocacia, e a ausência de comunicação transforma um problema contornável em falha irreversível.',
        '2. O procedimento em quatro passos: identificar cedo, comunicar imediatamente com o quadro completo, propor a solução que enxerga, combinar e executar.',
        '3. O que não fazer: sumir, avisar no dia, protocolar peça ruim só para dizer que protocolou, prometer algo ao cliente para compensar.',
        '4. Audiência: tolerância zero, e as saídas de substabelecer, pedir adiamento ou mandar preposto só existem com antecedência.',
        '5. Se o prazo já foi perdido: avisar na hora, e as três perguntas seguintes sobre medida cabível, dano ao cliente e quem comunica. Deixe claro que esconder é o que vira responsabilidade civil e problema disciplinar.',
        '',
        'NÃO FAÇA: tom punitivo que desestimule a pessoa a avisar; sugerir esconder ou "dar um jeito".',
      ].join('\n'),
    },

    {
      id: 'audiencias',
      titulo: 'Audiências',
      resumo: 'Preparação, cliente presente ou não, virtual e o pós.',
      minutos: 8,
      manual: [
        '## Assim que a audiência for designada',
        '',
        '1. **Confirme na Agenda** e cheque conflito com outra audiência sua.',
        '2. **Avise o cliente imediatamente**: data, hora, se ele precisa comparecer e como acessa (link, sala virtual, endereço do fórum).',
        '3. **Confirme de novo em D-7 e D-1.** Cliente idoso esquece, muda de número e às vezes não sabe usar o aplicativo.',
        '',
        '## Cliente precisa ir?',
        '',
        '- **Vara cível** — em regra basta o advogado.',
        '- **Juizado especial** — a presença da parte é **obrigatória**, sob pena de extinção. Isso não se negocia: se o cliente não puder, resolva antes.',
        '- **Justiça do Trabalho** — parte e testemunhas conforme o caso; empresa vai por preposto com carta de preposição.',
        '',
        '## Audiência virtual',
        '',
        '- Teste o link e o áudio **antes**.',
        '- Se o cliente vai participar, faça um teste com ele no dia anterior.',
        '- Tenha o número do cliente aberto: cai conexão, e alguém precisa avisar o outro.',
        '- Fundo neutro, traje adequado, ambiente silencioso. Você está no fórum.',
        '',
        '## Conciliação',
        '',
        'Exponha os termos de acordo com clareza, mas com firmeza quanto aos direitos do cliente. Nas nossas ações raramente há acordo já na primeira audiência — o que não autoriza ir despreparado.',
        '',
        '**Nenhum acordo se fecha sem autorização expressa do cliente.** Preferencialmente por escrito, no WhatsApp do hub, ficando registrado.',
        '',
        '## Depois da audiência',
        '',
        '1. Registrar o resultado no processo (movimentação e comentário).',
        '2. Mover o card, se mudou de fase.',
        '3. Criar os prazos que nasceram ali.',
        '4. Avisar o cliente do que aconteceu, em linguagem que ele entenda.',
      ].join('\n'),
      checklist: [
        'Aviso o cliente na designação e confirmo em D-7 e D-1.',
        'Sei em que rito a presença do cliente é obrigatória.',
        'Nunca fecho acordo sem autorização registrada do cliente.',
        'Registro o resultado no hub no mesmo dia.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre audiências no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado, incluindo quem vai fazer a primeira audiência virtual.',
        'TOM: prático e checklist, com cuidado especial com cliente idoso.',
        '',
        'ROTEIRO:',
        '1. O que fazer assim que a audiência é designada: confirmar na agenda, checar conflito, avisar o cliente com data, hora, necessidade de comparecer e forma de acesso, e confirmar de novo em D-7 e D-1. Explique que cliente idoso esquece, troca de número e às vezes não sabe usar o aplicativo.',
        '2. Quando o cliente precisa comparecer: em regra não na vara cível, obrigatoriamente no juizado especial sob pena de extinção, e conforme o caso na Justiça do Trabalho.',
        '3. Audiência virtual: testar link e áudio antes, ensaiar com o cliente no dia anterior, ter o telefone do cliente à mão, fundo neutro, traje adequado e ambiente silencioso.',
        '4. Conciliação: clareza nos termos com firmeza nos direitos, e a regra absoluta de que nenhum acordo se fecha sem autorização expressa do cliente, de preferência registrada por escrito.',
        '5. O pós-audiência em quatro passos: registrar no processo, mover o card, criar os prazos nascidos ali e avisar o cliente em linguagem acessível.',
        '',
        'NÃO FAÇA: sugerir fechar acordo com autorização apenas verbal e não registrada.',
      ].join('\n'),
    },
  ],
};
