import type { Trilha } from '../types';

export const FASE_JUDICIAL: Trilha = {
  id: 'fase-judicial',
  titulo: 'A fase judicial ponta a ponta',
  subtitulo: 'Do protocolo da inicial ao dinheiro na conta do cliente',
  icone: 'Scale',
  cor: '#15AABF',
  publico: 'Advogados associados. Estagiário faz para entender o todo.',
  aulas: [
    {
      id: 'panorama',
      videoPlanejado: true,
      titulo: 'Panorama: as etapas e o que se faz em cada uma',
      resumo: 'O mapa inteiro antes do detalhe.',
      minutos: 7,
      acervo: {
        titulo: 'Acervo — Passo a passo da fase judicial (gravações antigas)',
        url: 'https://drive.google.com/drive/folders/1s9W7Nj9qhvyfbPWDDVwxHGnb7QWcX0lm',
      },
      manual: [
        '## As quatro grandes etapas',
        '',
        '1. **Início processual** — protocolo da inicial e admissibilidade.',
        '2. **Conhecimento** — conciliação, contestação, réplica, provas.',
        '3. **Sentença** — alegações finais e decisão.',
        '4. **Encerramento** — recursos, cumprimento de sentença, alvará, prestação de contas e arquivamento.',
        '',
        '## O ciclo completo, ato por ato',
        '',
        '- Protocolo da inicial → cadastro no hub → card na fase inicial.',
        '- Despacho de admissibilidade: recebimento, emenda ou indeferimento de gratuidade.',
        '- Citação do réu.',
        '- Audiência de conciliação (quando designada).',
        '- Contestação.',
        '- Réplica.',
        '- Especificação de provas (ou alegações finais com pedido de julgamento antecipado).',
        '- Perícia, quando deferida.',
        '- Alegações finais.',
        '- Sentença.',
        '- Recurso, contrarrazões, acórdão.',
        '- Trânsito em julgado.',
        '- Cumprimento de sentença.',
        '- Depósito judicial e alvará.',
        '- Prestação de contas e repasse.',
        '- Arquivamento.',
        '',
        '## O princípio que atravessa tudo',
        '',
        '> Cada ato do processo gera **três obrigações**: cumprir o ato, registrar no hub e comunicar o cliente quando for relevante para ele. Fazer só a primeira é fazer um terço do trabalho.',
        '',
        '## Onde isso vive no hub',
        '',
        'O kanban **Fase Judicial** tem uma coluna para cada etapa. O card anda com o DJEN. **Execução & Repasse** é um quadro à parte, porque a lógica da ponta final é outra: lá o que importa é dinheiro, não prazo.',
      ].join('\n'),
      checklist: [
        'Sei recitar o ciclo do processo, do protocolo ao arquivamento.',
        'Sei que cada ato gera três obrigações.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos com o panorama da fase judicial no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado novo e estagiário que precisa enxergar o processo inteiro.',
        'TOM: de mapa, com sequência clara.',
        '',
        'ROTEIRO:',
        '1. As quatro grandes etapas: início processual, conhecimento, sentença e encerramento.',
        '2. O ciclo ato por ato, do protocolo da inicial ao arquivamento, passando por admissibilidade, citação, conciliação, contestação, réplica, provas, perícia, alegações finais, sentença, recurso, trânsito, cumprimento, alvará, prestação de contas e repasse.',
        '3. O princípio que atravessa tudo: cada ato gera três obrigações — cumprir o ato, registrar no hub e comunicar o cliente quando for relevante. Fazer só a primeira é fazer um terço do trabalho.',
        '4. Onde isso vive no hub: o kanban Fase Judicial com uma coluna por etapa, movido pelo DJEN, e o quadro separado de Execução e Repasse, porque na ponta final o que importa é dinheiro e não prazo.',
        '',
        'NÃO FAÇA: entrar em detalhe técnico de cada peça, isso é assunto das aulas seguintes.',
      ].join('\n'),
    },

    {
      id: 'inicial-protocolo',
      titulo: 'Petição inicial e protocolo',
      resumo: 'O que conferir antes de distribuir e o que fazer depois.',
      minutos: 9,
      manual: [
        '## Antes de protocolar',
        '',
        '1. **Documentos** — procuração assinada, documentos pessoais, comprovante de residência, provas da causa de pedir e o comprovante de gratuidade.',
        '2. **Formatação** — a peça no timbrado do escritório, sem lacuna aberta.',
        '3. **Competência** — foro do domicílio do consumidor, em regra. Vara certa dentro do foro.',
        '4. **Valor da causa** — batendo com o cálculo salvo.',
        '5. **Pedidos** — específicos, líquidos onde couber, com astreinte quando houver obrigação de fazer.',
        '6. **Tutela de urgência** — se for pedir, os requisitos precisam estar demonstrados com documento, não com adjetivo.',
        '',
        '## Protocolo',
        '',
        'PJe, e-SAJ ou Projudi, conforme o tribunal. Confira a classe, o assunto e o cadastro das partes na distribuição — erro aqui atrasa semanas.',
        '',
        'Guarde **número do processo** e **comprovante de protocolo**.',
        '',
        '## Imediatamente depois',
        '',
        '1. Cadastrar o processo no hub com o CNJ, comarca e vara (formato curto, vindo do DataJud).',
        '2. Vincular o cliente e a parte adversa.',
        '3. Salvar o cálculo no processo.',
        '4. Aplicar as etiquetas existentes.',
        '5. Atribuir responsável.',
        '6. Arquivar a peça e o comprovante na pasta do cliente, numerados.',
        '7. Avisar o cliente que a ação foi distribuída, explicando o que acontece agora e em quanto tempo.',
        '',
        '## Acompanhamento inicial',
        '',
        'Monitore os primeiros dias: recebimento da inicial, designação do juízo, decisão sobre gratuidade e tutela. É a fase em que despacho aparece rápido.',
        '',
        '## O prazo interno',
        '',
        '**5 dias úteis** desde a distribuição do caso a você até as ações montadas. Celeridade aqui não é capricho: o recebimento do escritório e o seu dependem do andamento.',
      ].join('\n'),
      checklist: [
        'Confiro os 6 itens antes de protocolar.',
        'Cadastro no hub imediatamente depois do protocolo.',
        'Aviso o cliente da distribuição.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre petição inicial e protocolo no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado que vai distribuir a primeira ação pelo escritório.',
        'TOM: checklist operacional.',
        '',
        'ROTEIRO:',
        '1. As seis conferências antes de protocolar: documentos, formatação no timbrado sem lacuna, competência com foro do domicílio do consumidor, valor da causa batendo com o cálculo salvo, pedidos específicos com astreinte quando couber, e tutela de urgência demonstrada com documento e não com adjetivo.',
        '2. O protocolo em PJe, e-SAJ ou Projudi, com atenção à classe, ao assunto e ao cadastro das partes, porque erro ali atrasa semanas. Guardar número e comprovante.',
        '3. Os sete passos imediatamente depois: cadastrar no hub, vincular partes, salvar cálculo, etiquetar, atribuir responsável, arquivar peça e comprovante na pasta do cliente, e avisar o cliente.',
        '4. O acompanhamento dos primeiros dias: recebimento, designação do juízo, gratuidade e tutela.',
        '5. Feche com o prazo interno de 5 dias úteis e a razão dele: o recebimento do escritório e do associado dependem do andamento.',
        '',
        'NÃO FAÇA: prometer deferimento de tutela ou de gratuidade.',
      ].join('\n'),
    },

    {
      id: 'admissibilidade',
      titulo: 'Admissibilidade: emenda, gratuidade e custas',
      resumo: 'Os primeiros despachos e como responder cada um.',
      minutos: 9,
      acervo: {
        titulo: 'Acervo — Admissibilidade da inicial',
        url: 'https://drive.google.com/drive/folders/1IVhAexGk_eMX3ScMkeQmuCe9aIw-JWeJ',
      },
      manual: [
        '## O que costuma vir',
        '',
        '- **Emenda à inicial** — juntar documento, corrigir valor da causa, esclarecer pedido, regularizar representação.',
        '- **Indeferimento ou exigência quanto à gratuidade** — o juízo pede comprovação ou indefere.',
        '- **Determinação de recolhimento de custas** — às vezes antes mesmo da citação do réu.',
        '- **Indeferimento de tutela de urgência.**',
        '',
        '## Emenda',
        '',
        'Prazo em regra de 15 dias. Cumpra **integralmente e de uma vez**: emenda pela metade gera nova determinação e mais um mês perdido. Se algo pedido não for possível, explique no corpo da petição por que não é, com fundamento.',
        '',
        '## Gratuidade',
        '',
        'A gratuidade se instrui com prova de hipossuficiência: histórico de créditos do benefício, declaração de imposto de renda, comprovantes de despesa. Nossa clientela em regra tem direito, mas o direito precisa estar **documentado**.',
        '',
        'Indeferida, cabe **agravo de instrumento** — e há skill do escritório para essa peça, com modelo específico para indeferimento de gratuidade.',
        '',
        '## Custas exigidas sem citação do réu',
        '',
        'Situação recorrente e há modelo próprio de agravo para ela. Não recolha por reflexo: avalie primeiro.',
        '',
        '## Tutela indeferida',
        '',
        'Avalie o agravo pelo custo-benefício: chance de reforma, urgência real do cliente, risco de antecipar debate de mérito num tribunal antes da instrução.',
        '',
        '## O que sempre fazer',
        '',
        '- Registrar no hub e mover o card.',
        '- Explicar ao cliente o que houve, sem alarmá-lo: emenda e exigência de documento são rotina, não derrota.',
        '',
        '> Cliente idoso que ouve "o juiz indeferiu" entende "perdi a ação". Explique a diferença entre despacho de expediente e decisão de mérito.',
      ].join('\n'),
      checklist: [
        'Cumpro emenda integralmente e de uma vez.',
        'Sei que há skill de agravo para gratuidade e para custas.',
        'Explico ao cliente sem alarmá-lo.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre a fase de admissibilidade da inicial no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado.',
        'TOM: técnico, com cuidado na parte de comunicação com cliente idoso.',
        '',
        'ROTEIRO:',
        '1. Os quatro despachos que costumam vir: emenda à inicial, exigência ou indeferimento de gratuidade, determinação de custas antes da citação, e indeferimento de tutela.',
        '2. Emenda: prazo em regra de 15 dias, cumprir integralmente e de uma vez, porque emenda pela metade gera nova determinação e mais um mês perdido. Se algo não for possível, explicar com fundamento.',
        '3. Gratuidade: instruir com histórico de créditos, declaração de imposto de renda e comprovantes de despesa. Frisar que a clientela em regra tem direito, mas o direito precisa estar documentado. Indeferida, cabe agravo de instrumento, e há modelo próprio no escritório.',
        '4. Custas exigidas sem citação do réu: situação recorrente com modelo próprio de agravo; não recolher por reflexo.',
        '5. Tutela indeferida: avaliar o agravo pelo custo-benefício.',
        '6. Feche com a comunicação ao cliente: explicar que emenda e exigência de documento são rotina, e a diferença entre despacho de expediente e decisão de mérito, porque cliente idoso ouve "indeferiu" e entende "perdi".',
        '',
        'NÃO FAÇA: sugerir recolher custas sem avaliar; prometer reforma em agravo.',
      ].join('\n'),
    },

    {
      id: 'contestacao-replica',
      titulo: 'Contestação e réplica',
      resumo: 'Ler a defesa do banco e responder ponto a ponto.',
      minutos: 12,
      acervo: {
        titulo: 'Acervo — Contestação e réplica (passo a passo)',
        url: 'https://drive.google.com/drive/folders/1-9PLgFW6mOpTNbjaconEmMmSbFOp75k5',
      },
      manual: [
        '## Como ler uma contestação',
        '',
        'Leia duas vezes. Na primeira, entenda a estratégia da defesa. Na segunda, marque:',
        '',
        '1. **Preliminares** — incompetência, ilegitimidade, prescrição, falta de interesse, inépcia. Cada uma precisa de resposta específica.',
        '2. **Documentos novos** — o banco costuma juntar contrato, print de sistema, gravação de áudio, termo de adesão. Cada documento novo é uma frente: você reconhece, impugna ou pede perícia.',
        '3. **O que ele NÃO impugnou** — fato não impugnado se presume verdadeiro. Isso é ouro: destaque na réplica.',
        '4. **Contradições internas** — a defesa que diz que houve contratação por telefone e junta contrato assinado se contradiz.',
        '',
        '## Contrato digital: o que olhar',
        '',
        '- Há **certificação ICP-Brasil**? Assinatura eletrônica simples não tem a mesma força.',
        '- Qual o **intervalo entre a abertura e a assinatura**? Assinatura "relâmpago" (segundos) é indício de que ninguém leu nada.',
        '- Há **geolocalização, IP e device** compatíveis com a cliente?',
        '- As **faturas mostram compras**? Cartão consignado sem nenhuma compra em anos é cartão que nunca foi usado como cartão.',
        '- O **valor sacado** corresponde ao que a cliente diz ter recebido?',
        '',
        '## A réplica',
        '',
        'Estrutura que funciona:',
        '',
        '1. Enfrentar cada preliminar, na ordem em que vieram.',
        '2. Impugnar especificamente cada documento novo.',
        '3. Destacar os fatos não impugnados.',
        '4. Reforçar a causa de pedir com a prova já produzida.',
        '5. Requerer as provas que você vai precisar — **sem** requerer perícia se a estratégia é julgamento antecipado.',
        '',
        '> A decisão de pedir ou não perícia na réplica determina o passo seguinte. A skill de especificação lê a réplica exatamente para saber qual caminho seguir. Decida com consciência.',
        '',
        '## Prazo',
        '',
        '15 dias úteis, em regra. Régua: D-7 ler a contestação e listar documentos novos; D-3 réplica montada; D-1 protocolo.',
      ].join('\n'),
      checklist: [
        'Leio a contestação duas vezes, com marcação.',
        'Impugno especificamente cada documento novo.',
        'Destaco os fatos não impugnados.',
        'Decido conscientemente sobre pedir perícia.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre contestação e réplica no escritório Frider Andrade | Advogados, com foco em ações bancárias.',
        '',
        'PÚBLICO: advogado associado que vai responder à defesa de um banco.',
        'TOM: técnico e estratégico.',
        '',
        'ROTEIRO:',
        '1. Como ler uma contestação: duas leituras, a primeira para entender a estratégia e a segunda para marcar preliminares, documentos novos, o que não foi impugnado e as contradições internas. Explique que fato não impugnado se presume verdadeiro e que isso é ouro para a réplica.',
        '2. Contrato digital, os cinco pontos de exame: certificação ICP-Brasil, intervalo entre abertura e assinatura com o indício da assinatura relâmpago, geolocalização e IP compatíveis, faturas sem compras, e correspondência entre valor sacado e valor recebido.',
        '3. A estrutura da réplica em cinco movimentos, terminando no requerimento de provas.',
        '4. Destaque a decisão estratégica: pedir ou não perícia na réplica determina o passo seguinte, porque a skill de especificação lê a réplica para escolher o caminho.',
        '5. Feche com o prazo de 15 dias úteis e a régua D-7, D-3, D-1 aplicada a essa peça.',
        '',
        'NÃO FAÇA: dar a entender que perícia sempre ajuda; explique que é decisão estratégica.',
      ].join('\n'),
    },

    {
      id: 'provas',
      titulo: 'Especificação de provas e perícias',
      resumo: 'Julgamento antecipado ou perícia — e qual perícia.',
      minutos: 10,
      acervo: {
        titulo: 'Acervo — Especificação de provas',
        url: 'https://drive.google.com/drive/folders/1aQboZz1JJVXJZyTyxVOIUq09k08L_Eq-',
      },
      manual: [
        '## A bifurcação',
        '',
        '- **Réplica não pediu perícia** → alegações finais com **pedido de julgamento antecipado**. Você reforça as teses já alegadas: assinatura relâmpago, contrato sem certificação ICP-Brasil, faturas sem compras, ausência de uso do cartão, prova emprestada e laudos do assistente técnico.',
        '- **Réplica pediu perícia** → especificação pertinente ao tipo.',
        '',
        '## As perícias',
        '',
        '- **Grafotécnica** — autenticidade da assinatura em contrato **físico**. Quando o cliente diz que nunca assinou aquilo.',
        '- **Documentoscópica** — integridade do documento físico: adulteração, montagem, colagem de assinatura.',
        '- **Digital documentoscópica** — contrato **eletrônico**: validade da assinatura digital, o procedimento de contratação, os metadados, o consentimento informado.',
        '- **Contábil** — abusividade: juros excessivos, capitalização indevida, evolução da dívida.',
        '- **De áudio** — quando a contratação foi por telefone e o banco junta a gravação.',
        '',
        '## Como escolher',
        '',
        'Pergunte: **o que está em disputa?**',
        '',
        '- Disputa se foi ela que assinou → grafotécnica (físico) ou digital documentoscópica (eletrônico).',
        '- Disputa se o documento é íntegro → documentoscópica.',
        '- Disputa se a cliente entendeu o que contratava → digital documentoscópica ou de áudio.',
        '- Disputa quanto se deve → contábil.',
        '',
        '## Quesitos e assistente técnico',
        '',
        'Perícia deferida abre prazo para **quesitos** e indicação de **assistente técnico**. Quesito ruim entrega o laudo ao perito; quesito bem feito amarra a resposta. Há skill própria para quesitos em acidente de trabalho, com catálogo pronto.',
        '',
        '## Laudo desfavorável',
        '',
        'Não é o fim. Impugna-se: vício de método, quesito não respondido, conclusão sem fundamento, critério errado. Há skill de impugnação de laudo com taxonomia de vícios.',
        '',
        '> Laudo que não respondeu seus quesitos é laudo incompleto — e isso se alega, não se aceita.',
      ].join('\n'),
      checklist: [
        'Sei escolher a perícia pela pergunta "o que está em disputa".',
        'Sei que a réplica é que determina o caminho da especificação.',
        'Sei que laudo desfavorável se impugna.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre especificação de provas e perícias no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado em processo bancário na fase de provas.',
        'TOM: técnico e decisório.',
        '',
        'ROTEIRO:',
        '1. A bifurcação: se a réplica não pediu perícia, faz-se alegações finais com pedido de julgamento antecipado, reforçando as teses do escritório; se pediu, monta-se a especificação pertinente.',
        '2. As cinco perícias: grafotécnica para contrato físico, documentoscópica para integridade do documento, digital documentoscópica para contrato eletrônico, contábil para abusividade e de áudio para contratação por telefone.',
        '3. Ensine a escolher pela pergunta "o que está em disputa", com os quatro pareamentos entre disputa e perícia.',
        '4. Quesitos e assistente técnico: quesito ruim entrega o laudo ao perito, quesito bem feito amarra a resposta.',
        '5. Laudo desfavorável não é o fim: impugna-se por vício de método, quesito não respondido, conclusão sem fundamento e critério errado. Laudo que não respondeu os quesitos é laudo incompleto.',
        '',
        'NÃO FAÇA: sugerir pedir todas as perícias para garantir; isso encarece e atrasa sem estratégia.',
      ].join('\n'),
    },

    {
      id: 'sentenca',
      titulo: 'Sentença: ler, decidir e comunicar',
      resumo: 'O que conferir na decisão e como decidir se recorre.',
      minutos: 10,
      acervo: {
        titulo: 'Acervo — Sentença e recursos',
        url: 'https://drive.google.com/drive/folders/1RTc9CWokOmfi62Sz6kwHQ2M5Jb8hcymj',
      },
      manual: [
        '## Como ler a sentença',
        '',
        '1. **Vá ao dispositivo primeiro.** É ali que está o que foi decidido.',
        '2. **Confira pedido por pedido**: todos foram apreciados? Ficou algum de fora? Isso é omissão e cabe embargos.',
        '3. **Leia a fundamentação** para entender por que ganhou ou perdeu cada ponto.',
        '4. **Confira os acessórios**: juros, correção, marco inicial de cada um, honorários e custas.',
        '5. **Confira se há erro material** — nome, valor, data trocados.',
        '',
        '## Embargos de declaração',
        '',
        'Cabem para omissão, obscuridade, contradição e erro material. Prazo de 5 dias. Há skill do escritório com modelos por tipo de vício.',
        '',
        'Servem também para **prequestionar**, se o horizonte é tribunal superior. Prequestionamento que não foi feito derruba recurso bom lá na frente.',
        '',
        '## Decidir se recorre',
        '',
        'Pese:',
        '',
        '- **O que ainda dá para ganhar** — a diferença entre o que veio e o que se pediu.',
        '- **A chance real** — como aquela câmara vem decidindo esse tema.',
        '- **O custo e o tempo** — preparo, mais um ano, e o cliente com 78 anos esperando.',
        '- **O risco** — em algumas situações o recurso pode piorar.',
        '',
        '> A decisão de recorrer é do **cliente**, informada por você. Explique o que há a ganhar, a chance, o tempo e o custo — e registre a decisão dele.',
        '',
        '## Comunicação ao cliente',
        '',
        'Sentença é o momento em que a comunicação mais importa. **Comunique imediatamente**, em linguagem que ele entenda:',
        '',
        '- Ganhou: o que ganhou, quanto, quando entra e o que ainda falta (o banco pode recorrer).',
        '- Perdeu: o que o juiz decidiu e por quê, o que ainda é possível, e qual a sua recomendação.',
        '',
        'Nunca use "ganhamos" quando ainda cabe recurso do banco sem explicar que o dinheiro ainda não é certo nem imediato.',
        '',
        '## No hub',
        '',
        'Registrar, mover o card, criar o prazo de recurso pela Agenda (a contagem sai pronta) e anexar a sentença.',
      ].join('\n'),
      checklist: [
        'Leio o dispositivo primeiro e confiro pedido por pedido.',
        'Sei quando cabem embargos e para que servem no prequestionamento.',
        'Registro a decisão do cliente sobre recorrer.',
        'Comunico sentença no mesmo dia.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre como ler uma sentença e decidir o próximo passo, no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado.',
        'TOM: técnico, e muito cuidadoso na parte de comunicação com o cliente.',
        '',
        'ROTEIRO:',
        '1. Como ler: ir ao dispositivo primeiro, conferir pedido por pedido para achar omissão, ler a fundamentação, conferir juros, correção, marcos, honorários e custas, e procurar erro material.',
        '2. Embargos de declaração: hipóteses de omissão, obscuridade, contradição e erro material, prazo de 5 dias, existência de modelos por tipo de vício, e a função de prequestionar quando o horizonte é tribunal superior.',
        '3. Decidir se recorre, pesando quatro fatores: o que ainda dá para ganhar, a chance real naquela câmara, o custo e o tempo com o cliente idoso esperando, e o risco de piorar. Deixe claro que a decisão é do cliente, informada pelo advogado, e que ela se registra.',
        '4. Comunicação ao cliente: imediata, em linguagem acessível, com roteiros diferentes para ganhou e perdeu. Alerte que não se diz "ganhamos" quando ainda cabe recurso do banco sem explicar que o dinheiro não é certo nem imediato.',
        '5. O registro no hub: mover o card, criar o prazo de recurso pela Agenda com contagem pronta e anexar a sentença.',
        '',
        'NÃO FAÇA: prometer resultado de recurso; sugerir decidir recorrer sem consultar o cliente.',
      ].join('\n'),
    },

    {
      id: 'execucao',
      titulo: 'Cumprimento de sentença e execução',
      resumo: 'Transitou em julgado. Agora é transformar decisão em dinheiro.',
      minutos: 10,
      acervo: {
        titulo: 'Acervo — Execução (cálculos e petição)',
        url: 'https://drive.google.com/drive/folders/1XBzEPoi_E2qDikZ4h2PGUBkPoc_Y4F55',
      },
      manual: [
        '## O gatilho',
        '',
        'Trânsito em julgado da sentença ou do acórdão. O card vai para **Execução & Repasse**.',
        '',
        '## O cálculo',
        '',
        'Antes da petição, o cálculo. São duas contas diferentes que às vezes convivem:',
        '',
        '- **Repetição de indébito** — a devolução do que foi descontado indevidamente, atualizada.',
        '- **Condenação** — danos morais e demais verbas fixadas, com juros e correção conforme o dispositivo.',
        '',
        'Some honorários de sucumbência quando fixados. Atualize pelos índices que a **sentença** mandou — não pelos que você acha melhor.',
        '',
        '## A petição de cumprimento',
        '',
        'Há skill própria. Ela lê a sentença, o acórdão (se houve recurso) e o cálculo, transcreve o dispositivo, monta o quadro-resumo dos valores executados e ajusta os pedidos.',
        '',
        'O devedor é intimado para pagar em **15 dias**. Não pagando: multa de 10% e honorários de 10%.',
        '',
        '## Se não pagar',
        '',
        '- Penhora online pelo sistema de bloqueio de ativos.',
        '- Bloqueio de veículos.',
        '- Protesto e negativação da decisão judicial.',
        '',
        'Contra banco, o pagamento em geral vem — o gargalo costuma ser tempo, não solvência.',
        '',
        '## Executado sem bens ou não localizado',
        '',
        'Existe a suspensão com **arquivamento provisório** (art. 921, III, do CPC), e há skill própria para essa petição. Serve para não deixar prescrever enquanto não há o que penhorar.',
        '',
        '## Depois do depósito',
        '',
        'Depósito judicial feito → **petição de alvará** (há skill, com os dados do escritório já preenchidos) → levantamento → prestação de contas → repasse.',
      ].join('\n'),
      checklist: [
        'Sei a diferença entre cálculo de repetição e de condenação.',
        'Atualizo pelos índices que a sentença mandou.',
        'Sei que existe arquivamento provisório para executado sem bens.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre cumprimento de sentença e execução no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado com sentença transitada em julgado.',
        'TOM: técnico e financeiro.',
        '',
        'ROTEIRO:',
        '1. O gatilho: trânsito em julgado, e o card indo para o quadro de Execução e Repasse.',
        '2. O cálculo: as duas contas que às vezes convivem, repetição de indébito e condenação, mais honorários de sucumbência quando fixados. Regra: atualizar pelos índices que a sentença mandou, não pelos que se acha melhores.',
        '3. A petição de cumprimento, feita por skill própria que lê sentença, acórdão e cálculo, transcreve o dispositivo e monta o quadro-resumo. Intimação para pagar em 15 dias, com multa de 10% e honorários de 10% se não pagar.',
        '4. Se não pagar: penhora online, bloqueio de veículos, protesto e negativação. Observe que contra banco o gargalo costuma ser tempo e não solvência.',
        '5. Executado sem bens ou não localizado: suspensão com arquivamento provisório do artigo 921, inciso três, do CPC, com skill própria, para não deixar prescrever.',
        '6. Feche com a sequência final: depósito, alvará, prestação de contas e repasse.',
        '',
        'NÃO FAÇA: prometer prazo de recebimento ao cliente.',
      ].join('\n'),
    },

    {
      id: 'alvara-prestacao',
      titulo: 'Alvará, prestação de contas e repasse',
      resumo: 'A hora mais delicada: o dinheiro do cliente passa pela nossa mão.',
      minutos: 10,
      acervo: {
        titulo: 'Acervo — Prestação de contas',
        url: 'https://drive.google.com/drive/folders/1EZzwTNubTEcUXlOVewV8z0HceyKUVT0D',
      },
      manual: [
        '## Alvará',
        '',
        'Depósito judicial feito, peticiona-se o alvará. Há skill própria: só mudam comarca, vara, autos e partes — os dados da conta de recebimento do escritório já vêm preenchidos.',
        '',
        '## Prestação de contas',
        '',
        'A conta é sempre explicada, nunca só informada:',
        '',
        '1. **Valor bruto levantado.**',
        '2. **Honorário contratual** — o percentual da cláusula, incidente sobre o **proveito econômico** do cliente.',
        '3. **Honorário de sucumbência** — é do advogado por direito próprio (art. 23 do Estatuto) e **não entra na base do contratual**.',
        '4. **Custas e despesas** reembolsáveis, se houver.',
        '5. **Líquido do cliente.**',
        '',
        '> Confira a cláusula **daquele contrato**. Percentual e base variam entre clientes; aplicar de memória é a origem de conflito.',
        '',
        '## A blindagem do art. 50 do Código de Ética',
        '',
        'Em caso de êxito, o que o advogado recebe somando contratual e sucumbência **não pode ultrapassar a vantagem obtida pelo cliente**. O hub emite alerta quando o cálculo se aproxima disso. Alerta aceso é para parar e conferir, não para clicar em cima.',
        '',
        '## Aprovação e envio',
        '',
        'O hub monta a prévia, você revisa o texto e o PDF, e só então aprova o envio. Fora da janela de 24 horas, sai por template aprovado. Fica a prova do envio.',
        '',
        '## Repasse',
        '',
        'Transferência para a conta **do próprio cliente**. Nunca para conta de terceiro sem autorização formal e documentada — nem de filho, nem de cuidador, nem de quem "sempre resolve as coisas dele".',
        '',
        'Comprovante anexado ao processo e enviado ao cliente.',
        '',
        '## Cliente que não responde',
        '',
        'O hub registra cada tentativa, com cadência de 48 horas e depois 5 dias, guardando o identificador da mensagem e se foi lida. Esse rastro é a prova que sustenta uma eventual **consignação em pagamento**.',
        '',
        '> Dinheiro de cliente parado na conta do escritório é risco. O caminho é insistir, documentar e, se não houver saída, consignar.',
      ].join('\n'),
      checklist: [
        'Confiro a cláusula de honorários daquele contrato.',
        'Sei que sucumbência não entra na base do contratual.',
        'Só repasso para a conta do próprio cliente.',
        'Documento cada tentativa de contato para repasse.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre alvará, prestação de contas e repasse no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado associado que vai conduzir a ponta final do caso.',
        'TOM: muito sério, é dinheiro de cliente idoso.',
        '',
        'ROTEIRO:',
        '1. Alvará: skill própria, em que só mudam comarca, vara, autos e partes, com os dados da conta do escritório já preenchidos.',
        '2. A prestação de contas em cinco linhas: valor bruto, honorário contratual sobre o proveito econômico, honorário de sucumbência que é do advogado por direito próprio pelo artigo 23 do Estatuto e não entra na base do contratual, custas e despesas, e o líquido do cliente. Alerte para conferir a cláusula daquele contrato, porque percentual e base variam e aplicar de memória gera conflito.',
        '3. A blindagem do artigo 50 do Código de Ética: contratual mais sucumbência não pode ultrapassar a vantagem obtida pelo cliente, com alerta no sistema. Diga que alerta aceso é para parar e conferir.',
        '4. Aprovação e envio: prévia montada, revisão humana do texto e do PDF, envio por template fora da janela de 24 horas, com prova guardada.',
        '5. Repasse: sempre para a conta do próprio cliente, nunca para terceiro sem autorização formal e documentada, nem de filho nem de cuidador. Comprovante anexado ao processo e enviado.',
        '6. Cliente que não responde: registro de tentativas com cadência de 48 horas e 5 dias, guardando identificador e leitura, como prova para eventual consignação em pagamento. Termine dizendo que dinheiro de cliente parado na conta do escritório é risco.',
        '',
        'NÃO FAÇA: sugerir repassar para familiar por conveniência; tratar o registro de tentativas como burocracia.',
      ].join('\n'),
    },
  ],
};
