import type { Trilha } from '../types';

export const TESES: Trilha = {
  id: 'teses',
  titulo: 'As teses do escritório',
  subtitulo: 'O que o escritório defende e por quê',
  icone: 'Landmark',
  cor: '#02883C',
  publico: 'Advogados e estagiários. Comercial faz as duas primeiras aulas.',
  aulas: [
    {
      id: 'rmc-rcc',
      videoPlanejado: true,
      titulo: 'RMC e RCC: a tese principal',
      resumo: 'O que é a reserva de margem consignável, por que ela lesa o aposentado.',
      minutos: 14,
      acervo: {
        titulo: 'Acervo — RMC e RCC, noções gerais',
        url: 'https://drive.google.com/drive/folders/1JWHbj4ArnV8K_YHUN5xNWG0kqH9DzvwW',
      },
      manual: [
        '## O que acontece com a cliente',
        '',
        'A aposentada procura crédito. Sai da agência ou do telefone acreditando que contratou **empréstimo consignado** — parcelas fixas, prazo definido, fim à vista.',
        '',
        'O que foi contratado, no papel, é outra coisa: um **cartão de crédito consignado (RCC)** com **reserva de margem consignável (RMC)**. O valor que ela recebeu foi um saque no cartão. E o desconto mensal no benefício não amortiza a dívida como parcela de empréstimo — é o pagamento mínimo da fatura.',
        '',
        '## Por que isso é ruinoso',
        '',
        '- O desconto é **eterno**: paga-se o mínimo, o saldo é rolado com juros rotativos, a dívida não acaba.',
        '- A cliente **nunca usou o cartão** como cartão: não há compras nas faturas, só o saque inicial.',
        '- A **margem fica reservada**, impedindo-a de contratar um consignado comum, mais barato.',
        '- Muitas vezes o cartão **nunca chegou** às mãos dela.',
        '',
        '> É o caso clássico: a cliente descobre, cinco anos depois, que pagou mais do que recebeu e ainda deve.',
        '',
        '## As duas situações e as duas bases',
        '',
        '### Contrato quitado / encerrado',
        '',
        'A base é de **repetição de indébito**: pede-se a devolução do que foi descontado indevidamente, além dos danos morais.',
        '',
        '### Contrato em aberto',
        '',
        'A base é de **conversão** do cartão em empréstimo consignado comum, com recálculo pelos juros do consignado, compensação do que já foi pago, liberação da margem e danos morais.',
        '',
        '## Antes de tudo: o RMC está suspenso no país',
        '',
        '> Desde **08/04/2026** o STJ determinou a **suspensão nacional** de todos os processos, individuais e coletivos, sobre cartão de crédito consignado e RMC — em 1º e 2º graus e nos Juizados. A única exceção é **cumprimento de sentença** (art. 1.037, II, do CPC).',
        '',
        'São dois temas repetitivos, ambos do Min. Raul Araújo, na 2ª Seção:',
        '',
        '- **Tema 1.328** — há dano moral *in re ipsa* na invalidação da contratação do cartão com RMC em benefício previdenciário?',
        '- **Tema 1.414** — quais os parâmetros objetivos de validade e abusividade do cartão consignado, à luz do dever de informação; e, invalidado o contrato, se a consequência é voltar ao estado anterior, converter em consignado ou revisar cláusulas.',
        '',
        'O que isso muda no seu dia: **o caso não anda enquanto a tese não sai**. Ajuizar continua fazendo sentido — interrompe a prescrição e trava o caso esperando o julgamento, em vez de deixar o contrato envelhecer. O que não se faz é prometer prazo de julgamento ao cliente (art. 41 do Código de Ética).',
        '',
        '## O filtro de Minas Gerais: quatro anos da assinatura',
        '',
        '> Em MG existe jurisprudência consolidada — 9ª, 11ª e 20ª Câmaras Cíveis — reconhecendo **de ofício** a decadência do art. 178, II, do Código Civil: **quatro anos contados da assinatura do contrato**. Os descontos mensais são trato sucessivo e **não** reabrem o prazo.',
        '',
        'E não morre só a anulação: caem junto **repetição do indébito e dano moral**, por serem acessórios do pedido (art. 487, II, do CPC). O Tema 610 do STJ já foi expressamente rejeitado ali como argumento contrário.',
        '',
        'A ironia é que a própria tese que ganha o mérito é a que mata o caso pelo prazo: o IRDR do TJMG fixou o RMC em cima de **erro substancial**, que é anulabilidade — e anulabilidade decai em quatro anos.',
        '',
        '**Na prática, antes de ajuizar em MG:** contrato com mais de quatro anos não vai como anulatória por erro substancial. Ou se reposiciona a causa de pedir em **nulidade por violação do dever de informação** (CDC, arts. 6º, III, 46 e 51 — linha minoritária, mas existente), ou se aguarda a tese do Tema 1.414, que pode derrubar a decadência justamente por enquadrar a controvérsia no CDC e não no vício de consentimento.',
        '',
        '## A linha de argumentação',
        '',
        '1. **Vício de consentimento / ausência de contratação informada** — ela não sabia o que estava contratando. Isso é falha de dever de informação.',
        '2. **Ausência de uso do cartão** — as faturas provam que nunca houve compra. O produto foi vendido como empréstimo e usado como empréstimo.',
        '3. **Onerosidade e abusividade** — a comparação entre o que teria pago num consignado comum e o que pagou no cartão mostra o excesso.',
        '4. **Vulnerabilidade agravada** — consumidora idosa, hipossuficiente, com proteção reforçada.',
        '5. **Indícios concretos de fraude no contrato digital**, quando houver — assinatura relâmpago, laudo do assistente técnico apontando integridade comprometida da selfie, não conformidade com a IN 01 da Dataprev, e a ausência, nos autos, de IP, geolocalização, carimbo de tempo e trilha de auditoria.',
        '',
        '> ⚠️ **Não lidere com a falta de certificação ICP-Brasil.** Em 03/03/2026 a 3ª Turma do STJ decidiu que a simples ausência de ICP-Brasil **não anula** o contrato digital quando o conjunto probatório indica que não houve fraude. Alegar só isso entrega ao banco um precedente pronto. O eixo é outro: o ônus segue sendo da instituição financeira, e o que o STJ tratou como anuência — dados, selfie, geolocalização — é justamente o que o banco costuma **não juntar**.',
        '',
        '## O que nunca se afirma',
        '',
        '> Não se promete resultado, valor nem prazo ao cliente. A linguagem é de objetivo: "o que buscamos é a conversão e a devolução do que foi pago a mais".',
      ].join('\n'),
      checklist: [
        'Sei explicar RMC e RCC para um leigo em três frases.',
        'Sei quando a base é repetição e quando é conversão.',
        'Sei as cinco linhas de argumentação.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos explicando a tese de RMC e RCC do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado, estagiário e equipe comercial. Precisa servir tanto para fundamentar peça quanto para explicar a um leigo.',
        'TOM: didático, com narrativa de caso real no começo.',
        '',
        'ROTEIRO:',
        '1. Comece pela história: a aposentada procura crédito e sai acreditando que contratou empréstimo consignado, quando contratou cartão de crédito consignado com reserva de margem. O dinheiro que recebeu foi saque no cartão, e o desconto mensal é pagamento mínimo de fatura, não parcela de empréstimo.',
        '2. Por que é ruinoso: desconto eterno com juros rotativos, cartão nunca usado como cartão, margem reservada impedindo consignado mais barato, e cartão que muitas vezes nunca chegou.',
        '3. As duas situações e as duas bases: contrato quitado leva a repetição de indébito com danos morais; contrato em aberto leva a conversão em consignado comum, com recálculo, compensação, liberação da margem e danos morais.',
        '4. As cinco linhas de argumentação: vício de consentimento e falha de informação, ausência de uso do cartão provada pelas faturas, onerosidade comparada ao consignado comum, vulnerabilidade agravada da consumidora idosa, e vícios do contrato digital.',
        '5. Feche com a regra de comunicação: nunca prometer resultado, valor ou prazo; usar linguagem de objetivo.',
        '',
        'NÃO FAÇA: citar número de indenização como se fosse padrão; prometer devolução em dobro como garantida.',
      ].join('\n'),
    },

    {
      id: 'hiscon',
      titulo: 'HISCON, HISCRE e a leitura do extrato',
      resumo: 'Como provar o que está sendo descontado e desde quando.',
      minutos: 10,
      manual: [
        '## Os documentos',
        '',
        '- **HISCON** — Histórico de Consignações. Mostra os contratos consignados averbados no benefício: banco, tipo, valor, data de início, prazo. É onde a RMC aparece.',
        '- **HISCRE** — Histórico de Créditos. Mostra os créditos pagos ao segurado, mês a mês, com os descontos. É onde se vê **quanto** foi descontado e **por quantos meses**.',
        '- **Extrato de empréstimos consignados** — a visão consolidada dos contratos.',
        '',
        'Todos saem do Meu INSS, com a senha do gov.br do cliente.',
        '',
        '## O que você procura',
        '',
        '1. **A rubrica da reserva de margem** — o desconto identificado como RMC ou cartão consignado, e não como empréstimo.',
        '2. **A data de início** — o marco de quando o desconto começou. É daqui que sai o período da repetição.',
        '3. **O valor mensal** e a **soma do período**.',
        '4. **Se há empréstimo consignado comum do mesmo banco** — ajuda a mostrar que ela sabia contratar consignado e que o cartão foi outra coisa.',
        '5. **Quantos contratos** existem: às vezes há mais de uma RMC, de bancos diferentes, e cada uma pode ser uma ação.',
        '',
        '## O cálculo nasce daqui',
        '',
        'O cálculo do hub se alimenta desses dados: valor descontado por mês, período, e a comparação com o que seria devido num consignado comum. **Cálculo sem HISCRE é cálculo por estimativa** — e estimativa não sustenta pedido.',
        '',
        '## Cuidado com a senha do cliente',
        '',
        'A senha do gov.br é do cliente. Guarde-a apenas onde o escritório determina, use-a apenas para o que ele autorizou, e nunca a compartilhe fora da estrutura. Isso é dado pessoal sensível.',
        '',
        '## Faturas do cartão',
        '',
        'Peça as faturas ao banco (ou junte as que a cliente tiver). São elas que provam a **ausência de compras** — o argumento mais visual da tese: um cartão de crédito que em cinco anos não registrou uma única compra nunca foi um cartão de crédito.',
      ].join('\n'),
      checklist: [
        'Sei o que cada documento prova.',
        'Sei extrair período e valor para o cálculo.',
        'Trato a senha gov.br do cliente como dado sensível.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre HISCON, HISCRE e leitura de extrato no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado, estagiário e back office que montam a prova do caso.',
        'TOM: prático, de bancada.',
        '',
        'ROTEIRO:',
        '1. Os documentos e o que cada um prova: HISCON com os contratos averbados, onde a RMC aparece; HISCRE com os créditos e descontos mês a mês, onde se vê quanto e por quantos meses; e o extrato consolidado. Todos saem do Meu INSS com a senha gov.br do cliente.',
        '2. Os cinco pontos a procurar: a rubrica da reserva de margem, a data de início como marco do período de repetição, o valor mensal e a soma, a existência de consignado comum do mesmo banco, e quantos contratos existem, já que cada RMC pode ser uma ação.',
        '3. Explique que o cálculo nasce desses documentos e que cálculo sem HISCRE é estimativa, e estimativa não sustenta pedido.',
        '4. Cuidado com a senha do gov.br: é do cliente, é dado pessoal sensível, guarda-se só onde o escritório determina e não sai da estrutura.',
        '5. Feche com as faturas do cartão e o argumento mais visual da tese: um cartão que em cinco anos não registrou uma compra nunca foi um cartão de crédito.',
        '',
        'NÃO FAÇA: mostrar dados reais de cliente; ensinar a acessar conta gov.br sem autorização.',
      ].join('\n'),
    },

    {
      id: 'contrato-digital',
      titulo: 'Contrato digital: como se prova a fraude',
      resumo: 'Os sete sinais de que aquela assinatura não vale o que o banco diz.',
      minutos: 11,
      acervo: {
        titulo: 'Acervo — Análise de contratos (checklist e materiais)',
        url: 'https://drive.google.com/drive/folders/1JWIpalJ3iZUi1ZyDLeRV2vP3JdSNm_hP',
      },
      manual: [
        '## O ponto de partida',
        '',
        'O banco junta um contrato eletrônico e diz: está assinado, foi ela. A pergunta técnica é: **assinado como, e com que prova de que foi ela e de que ela entendeu?**',
        '',
        '## Os sinais de exame',
        '',
        '1. **Tipo de assinatura** — há certificado **ICP-Brasil**? Assinatura eletrônica simples (clique, aceite, token por SMS) tem força probatória menor e pode ser contestada.',
        '2. **Tempo entre abertura e assinatura** — assinatura "relâmpago", em segundos, indica que ninguém leu. Um contrato de crédito com dezenas de cláusulas não se lê em 40 segundos.',
        '3. **Geolocalização e IP** — batem com onde a cliente estava e mora? IP de outro estado é sinal forte.',
        '4. **Dispositivo** — aparelho compatível com o que a cliente tem? Idosa que não usa smartphone e "assinou" por aplicativo é contradição.',
        '5. **Biometria e selfie** — existe? A imagem é dela ou de terceiro?',
        '6. **Trilha de auditoria** — o registro do processo de contratação está completo, ou só existe o PDF final?',
        '7. **Consentimento informado** — houve informação clara sobre o produto? Há gravação? A gravação diz "cartão de crédito consignado" com todas as letras, ou fala em "empréstimo"?',
        '',
        '> Investigar a certificação **sim**; **liderar a peça com ela, não**. Desde o julgado do STJ de março de 2026, a simples ausência de ICP-Brasil não anula o contrato digital se o conjunto probatório indicar que não houve fraude. O que sustenta a peça são os indícios concretos — assinatura relâmpago, laudo do assistente técnico, ausência de IP, geolocalização e trilha de auditoria nos autos.',
        '',
        '## O que fazer com o que você encontrar',
        '',
        '- Sinal isolado → argumento na réplica.',
        '- Vários sinais → pedido de **perícia digital documentoscópica**.',
        '- Gravação de áudio juntada → **perícia de áudio** e transcrição.',
        '- Contrato físico com assinatura suspeita → **grafotécnica**.',
        '',
        '## A pergunta que resume tudo',
        '',
        '> O banco consegue provar que **aquela pessoa**, naquele momento, **entendeu** que estava contratando um cartão de crédito consignado com reserva de margem — e não um empréstimo?',
        '',
        'Se a resposta for não, o vício está demonstrado.',
      ].join('\n'),
      checklist: [
        'Sei os sete sinais de exame de contrato digital.',
        'Sei qual perícia pedir para cada tipo de sinal.',
        'Sei a pergunta que resume a tese.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre análise de contrato digital em ações bancárias, no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogado que recebeu contestação com contrato eletrônico juntado.',
        'TOM: investigativo e técnico.',
        '',
        'ROTEIRO:',
        '1. O ponto de partida: o banco junta o contrato e diz que está assinado. A pergunta técnica é assinado como, e com que prova de que foi ela e de que ela entendeu.',
        '2. Percorra os sete sinais de exame: tipo de assinatura e presença de certificado ICP-Brasil; tempo entre abertura e assinatura, com o exemplo de que um contrato de crédito não se lê em 40 segundos; geolocalização e IP; dispositivo compatível com o que a cliente usa; biometria e selfie; trilha de auditoria completa ou apenas o PDF final; e consentimento informado, verificando se a gravação diz cartão de crédito consignado com todas as letras ou fala em empréstimo.',
        '3. O que fazer com o achado: sinal isolado vira argumento na réplica, vários sinais viram pedido de perícia digital documentoscópica, gravação juntada pede perícia de áudio, contrato físico suspeito pede grafotécnica.',
        '4. Feche com a pergunta que resume a tese: o banco consegue provar que aquela pessoa, naquele momento, entendeu que contratava cartão de crédito consignado com reserva de margem, e não empréstimo? Se não, o vício está demonstrado.',
        '',
        'NÃO FAÇA: afirmar que assinatura eletrônica simples é sempre inválida; a força é menor, não inexistente.',
      ].join('\n'),
    },

    {
      id: 'outras-verticais',
      titulo: 'As outras verticais',
      resumo: 'Contribuições, superendividamento, REPB, previdenciário e acidente de trabalho.',
      minutos: 12,
      manual: [
        '## Contribuições associativas',
        '',
        'Descontos de associação, sindicato ou entidade no benefício, sem filiação consciente. A lógica é a mesma da RMC: o aposentado não pediu, não usa, não sabia. Pede-se a cessação do desconto e a devolução.',
        '',
        '> Cuidado com a prescrição e com a prova de que houve alguma filiação formal. Nem todo desconto associativo é indevido.',
        '',
        '## Seguros embutidos',
        '',
        'Seguro prestamista ou de vida vendido junto com o empréstimo, sem escolha real. Discute-se venda casada e o dever de informação.',
        '',
        '## Superendividamento',
        '',
        'Lei do superendividamento: o consumidor com dívidas de consumo que comprometem o mínimo existencial pode pedir a **repactuação em bloco**, com todos os credores.',
        '',
        'O trabalho é diferente do resto: mapear todas as dívidas, calcular a capacidade real de pagamento preservando o mínimo existencial e montar um plano. Menos litígio, mais engenharia financeira.',
        '',
        '## REPB — Reestruturação de Passivo',
        '',
        'A vertical de reorganização de dívida, com esteira própria no hub. Tem funil, qualificação e critérios próprios.',
        '',
        '> Regra do escritório: ausência de reserva de margem **não** desqualifica um caso de REPB. Se o caso é de outra área, ele é encaminhado ao responsável certo, não descartado.',
        '',
        '## Previdenciário',
        '',
        'Duas frentes no hub: **Planejamento Previdenciário** (escolher a melhor data e a melhor regra de aposentadoria) e **INSS Administrativo** (benefícios, indeferimentos, recursos administrativos).',
        '',
        '## Acidente de trabalho e doença ocupacional',
        '',
        'A vertical trabalhista do escritório, com biblioteca e skills próprias e profundas: triagem de viabilidade, inicial sobre base real, quesitos de perícia médica e ergonômica, impugnação de laudo, réplica, razões finais, recurso ordinário e recurso de revista.',
        '',
        'Conceitos que você precisa conhecer antes de pegar um caso:',
        '',
        '- **NTEP** — nexo técnico epidemiológico, que em certos casos presume o nexo entre a doença e a atividade.',
        '- **Concausa** — a atividade não precisa ser a única causa; basta ter contribuído.',
        '- **Escada da responsabilidade** — objetiva, subjetiva por culpa, concausa.',
        '- **Prescrição pela actio nata** — o prazo corre da ciência da lesão e de sua extensão, não necessariamente do acidente.',
        '',
        '## A regra comum a todas',
        '',
        'Cada vertical tem seu quadro no hub, seu fluxo e suas skills. **Não improvise em vertical que não é sua** — encaminhe ao responsável.',
      ].join('\n'),
      checklist: [
        'Sei o que cada vertical do escritório faz.',
        'Sei que caso fora da minha vertical se encaminha, não se descarta.',
        'Conheço NTEP, concausa e actio nata de nome e de conceito.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos apresentando as verticais do escritório Frider Andrade | Advogados além de RMC e RCC.',
        '',
        'PÚBLICO: equipe inteira, para saber o que existe e para onde encaminhar.',
        'TOM: panorâmico, sem esgotar cada tema.',
        '',
        'ROTEIRO:',
        '1. Contribuições associativas: descontos de associação ou sindicato sem filiação consciente, com a mesma lógica da RMC, mas com alerta sobre prescrição e sobre a prova de filiação formal, porque nem todo desconto associativo é indevido.',
        '2. Seguros embutidos: prestamista ou de vida vendido junto com o empréstimo, com discussão de venda casada e dever de informação.',
        '3. Superendividamento: repactuação em bloco com todos os credores, preservando o mínimo existencial. Explique que o trabalho é menos litígio e mais engenharia financeira.',
        '4. REPB, reestruturação de passivo, com esteira própria. Inclua a regra do escritório de que ausência de reserva de margem não desqualifica o caso, e que caso de outra área é encaminhado, não descartado.',
        '5. Previdenciário em duas frentes: planejamento previdenciário e INSS administrativo.',
        '6. Acidente de trabalho e doença ocupacional, com as skills próprias, e os quatro conceitos que se precisa conhecer antes de pegar um caso: NTEP, concausa, escada da responsabilidade e prescrição pela actio nata.',
        '7. Feche com a regra comum: não improvisar em vertical que não é sua, encaminhar ao responsável.',
        '',
        'NÃO FAÇA: aprofundar cálculo trabalhista ou previdenciário, isso é assunto das skills específicas.',
      ].join('\n'),
    },
  ],
};
