import type { Trilha } from '../types';

export const CLIENTE: Trilha = {
  id: 'cliente',
  titulo: 'Cliente: atendimento e comunicação',
  subtitulo: 'Para o cliente, você é o escritório inteiro',
  icone: 'MessageSquare',
  cor: '#E64980',
  publico: 'Todo mundo que fala com cliente.',
  aulas: [
    {
      id: 'voce-e-o-escritorio',
      titulo: 'Você é o escritório para o cliente',
      resumo: 'Quem é o nosso cliente e o que ele espera de cada contato.',
      minutos: 8,
      manual: [
        '## Quem é o nosso cliente',
        '',
        'Em regra: **idoso, aposentado pelo INSS, com renda de um a dois salários mínimos**. Muitas vezes com pouca familiaridade digital, às vezes com dificuldade de audição ou de leitura, e quase sempre com desconfiança — porque já foi enganado uma vez, e foi por isso que nos procurou.',
        '',
        '> A pessoa que assina a procuração já foi enganada por alguém que também parecia confiável. A confiança em nós não vem de graça.',
        '',
        '## O que ele espera',
        '',
        '1. **Ser entendido** — que alguém escute a história inteira antes de responder.',
        '2. **Entender** — resposta em português, sem termo técnico solto.',
        '3. **Saber o que vai acontecer** — próximo passo e prazo aproximado.',
        '4. **Não ser esquecido** — notícia mesmo quando não há novidade.',
        '',
        '## O padrão de atendimento',
        '',
        '- **Resposta no mesmo dia.** Sempre. Se precisa apurar, responda dizendo que está apurando e quando retorna — e retorne.',
        '- **Cordialidade nominal**: chame pelo nome, com o tratamento que ele prefere.',
        '- **Frases curtas.** Áudio quando o cliente tem dificuldade de leitura — é frequente, e ajuda muito.',
        '- **Confirme entendimento**: "ficou claro?" vale mais que uma explicação perfeita não compreendida.',
        '',
        '## O que sempre estraga',
        '',
        '- Sumir por semanas.',
        '- Responder com jargão ("o feito foi saneado", "houve preclusão").',
        '- Prometer prazo que não depende de nós.',
        '- Falar mal de outro profissional ou do banco em termos agressivos.',
        '- Deixar o cliente saber pela internet algo que ele deveria ter sabido por você.',
        '',
        '## Registre',
        '',
        'Toda conversa relevante fica no hub. Combinação por telefone que não virou mensagem escrita não existe — nem para o escritório, nem como prova.',
      ].join('\n'),
      checklist: [
        'Respondo no mesmo dia, sempre.',
        'Explico sem jargão e confirmo entendimento.',
        'Registro no hub o que foi combinado.',
      ],
      promptVideo: [
        'Gere um vídeo, de 3 a 5 minutos sobre atendimento ao cliente no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogados, estagiários e back office que falam com cliente por WhatsApp.',
        'TOM: humano e concreto, com foco na realidade do cliente idoso.',
        '',
        'ROTEIRO:',
        '1. Quem é o nosso cliente: idoso, aposentado pelo INSS, renda de um a dois salários mínimos, pouca familiaridade digital, desconfiado porque já foi enganado uma vez. Use a frase de que a confiança em nós não vem de graça.',
        '2. As quatro expectativas: ser entendido, entender, saber o que vai acontecer e não ser esquecido.',
        '3. O padrão de atendimento: resposta no mesmo dia sem exceção, cordialidade nominal, frases curtas, uso de áudio quando há dificuldade de leitura, e confirmação de entendimento.',
        '4. O que sempre estraga: sumir, responder com jargão, prometer prazo que não depende de nós, falar mal de outro profissional, e deixar o cliente descobrir pela internet o que devia saber por nós.',
        '5. Feche com o registro: combinação por telefone que não virou mensagem escrita não existe, nem para o escritório nem como prova.',
        '',
        'NÃO FAÇA: caricaturar o cliente idoso; sugerir que se pode adiar resposta para o dia seguinte.',
      ].join('\n'),
    },

    {
      id: 'traduzir',
      titulo: 'Traduzir o processo para quem não é advogado',
      resumo: 'Um dicionário de como dizer cada ato processual em português.',
      minutos: 9,
      manual: [
        '## A regra',
        '',
        'Diga **o que aconteceu**, **o que significa para ele** e **o que vem agora**. Nessa ordem, em três frases.',
        '',
        '## O dicionário',
        '',
        '- **Distribuída** → "sua ação foi protocolada e já tem número. Agora o juiz vai analisar e o banco vai ser chamado a se defender."',
        '- **Emenda à inicial** → "o juiz pediu um documento a mais antes de seguir. É normal, já estamos providenciando."',
        '- **Citação** → "o banco foi oficialmente avisado da ação e tem prazo para responder."',
        '- **Contestação** → "o banco apresentou a defesa dele. Agora nós respondemos, ponto por ponto."',
        '- **Tutela deferida** → "o juiz mandou o banco parar o desconto agora, antes do fim do processo. Confira no próximo pagamento e me avise se ainda descontarem."',
        '- **Tutela indeferida** → "o juiz preferiu decidir isso só no final, com todas as provas. O processo continua normalmente."',
        '- **Perícia** → "um especialista vai examinar o contrato para dizer se aquela assinatura e aquela contratação são válidas."',
        '- **Sentença procedente** → "ganhamos em primeiro grau. O banco ainda pode recorrer, então o dinheiro não é imediato — vou te avisando."',
        '- **Sentença improcedente** → "o juiz de primeiro grau não acolheu nosso pedido. Vou te explicar por quê e qual a minha recomendação."',
        '- **Acórdão** → "o tribunal, com três juízes, revisou a decisão."',
        '- **Trânsito em julgado** → "acabaram os recursos. A decisão é definitiva."',
        '- **Cumprimento de sentença** → "agora começamos a cobrança do valor que o banco foi condenado a pagar."',
        '- **Alvará** → "o dinheiro já está depositado na Justiça e pedimos autorização para levantar."',
        '',
        '## Números',
        '',
        'Fale em reais e em meses, não em índices e em anos processuais. "Cerca de oitocentos reais" comunica; "repetição do indébito corrigida pelo INPC" não.',
        '',
        '## Prazo',
        '',
        'Nunca dê data. Dê faixa e diga de quem depende: "isso costuma levar de três a seis meses, mas depende do tribunal, não de nós".',
        '',
        '## A frase proibida',
        '',
        '> "Pode ficar tranquilo que a senhora vai receber."',
        '',
        'Substitua por: "o que buscamos é a devolução do que foi descontado e a suspensão do desconto. Vou te informando cada etapa."',
      ].join('\n'),
      checklist: [
        'Uso a estrutura: o que aconteceu, o que significa, o que vem agora.',
        'Falo em reais e meses, não em índices.',
        'Nunca dou data nem garantia.',
      ],
      promptVideo: [
        'Gere um vídeo, de 3 a 5 minutos ensinando a traduzir o processo judicial para o cliente leigo, no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogados e estagiários que se comunicam com aposentados.',
        'TOM: prático, quase um dicionário falado, com exemplos ditos em voz alta.',
        '',
        'ROTEIRO:',
        '1. A regra das três frases: o que aconteceu, o que significa para ele, o que vem agora.',
        '2. Percorra o dicionário, lendo a versão técnica e depois a versão em português para: distribuída, emenda, citação, contestação, tutela deferida, tutela indeferida, perícia, sentença procedente, sentença improcedente, acórdão, trânsito em julgado, cumprimento de sentença e alvará.',
        '3. Números: falar em reais e em meses, não em índices e anos processuais.',
        '4. Prazo: nunca dar data, dar faixa e dizer de quem depende.',
        '5. Feche com a frase proibida "pode ficar tranquilo que a senhora vai receber" e a substituição correta, em linguagem de objetivo.',
        '',
        'NÃO FAÇA: usar exemplos com valores prometidos; sugerir simplificar ao ponto de omitir risco.',
      ].join('\n'),
    },

    {
      id: 'noticia-ruim',
      titulo: 'Dar notícia ruim e lidar com cliente insatisfeito',
      resumo: 'A conversa que ninguém quer ter — e o jeito de não perder o cliente nela.',
      minutos: 8,
      manual: [
        '## Notícia ruim se dá cedo e de frente',
        '',
        '1. **Você comunica primeiro.** Antes que ele descubra sozinho, antes que passe uma semana.',
        '2. **Diga o que houve**, sem rodeio e sem culpar terceiros.',
        '3. **Diga o que isso muda** na prática para ele.',
        '4. **Traga o próximo passo** — sempre há um, ainda que seja "vou avaliar em três dias e te retorno".',
        '5. **Assuma o que é nosso.** Se o erro foi do escritório, isso se diz. Não se inventa culpa do sistema.',
        '',
        '> Cliente aceita notícia ruim. O que ele não aceita é descobrir sozinho e perceber que você sabia.',
        '',
        '## Cliente irritado',
        '',
        '- **Deixe falar até o fim.** Interromper dobra a irritação.',
        '- **Reconheça o que é legítimo**: "a senhora tem razão, faz duas semanas que não damos notícia".',
        '- **Separe o que é nosso do que não é**, sem usar isso como escudo.',
        '- **Ofereça algo concreto** com prazo: "até sexta eu te mando o resumo completo do processo".',
        '- **Cumpra.** Uma promessa quebrada aqui vale por dez.',
        '',
        '## Quando escalar',
        '',
        'Leve à coordenação quando houver: ameaça de reclamação na OAB, pedido de rescisão, acusação de má-fé, discussão de valor de honorários, ou cliente que você já não consegue atender com serenidade.',
        '',
        'Escalar não é fraqueza. É o procedimento.',
        '',
        '## O que nunca fazer',
        '',
        '- Responder no calor, por escrito.',
        '- Prometer resultado ou dinheiro para acalmar.',
        '- Devolver ironia.',
        '- Sumir da conversa.',
        '',
        '## Depois',
        '',
        'Registre no hub o que aconteceu e o que foi combinado. Se o caso for delicado, avise a coordenação antes que ela saiba por outro caminho.',
      ].join('\n'),
      checklist: [
        'Comunico notícia ruim antes que o cliente descubra.',
        'Sei os cinco gatilhos para escalar à coordenação.',
        'Não respondo no calor, por escrito.',
      ],
      promptVideo: [
        'Gere um vídeo, de 3 a 5 minutos sobre dar notícia ruim e lidar com cliente insatisfeito, no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogados e back office. O vídeo precisa reduzir o medo dessa conversa.',
        'TOM: sereno, adulto, com exemplos de fala.',
        '',
        'ROTEIRO:',
        '1. Notícia ruim se dá cedo e de frente, em cinco movimentos: comunicar primeiro, dizer o que houve sem rodeio, dizer o que muda na prática, trazer o próximo passo e assumir o que é nosso. Use a frase: cliente aceita notícia ruim, o que ele não aceita é descobrir sozinho e perceber que você sabia.',
        '2. Cliente irritado: deixar falar até o fim, reconhecer o que é legítimo com um exemplo de fala, separar o que é nosso do que não é sem usar isso como escudo, oferecer algo concreto com prazo e cumprir.',
        '3. Quando escalar à coordenação: ameaça de reclamação na OAB, pedido de rescisão, acusação de má-fé, discussão de honorários, ou quando já não se consegue atender com serenidade. Diga que escalar é procedimento, não fraqueza.',
        '4. O que nunca fazer: responder no calor por escrito, prometer resultado ou dinheiro para acalmar, devolver ironia, sumir.',
        '5. Feche com o registro no hub e o aviso à coordenação antes que ela saiba por outro caminho.',
        '',
        'NÃO FAÇA: ensinar a acalmar o cliente com promessa; sugerir ignorar cliente difícil.',
      ].join('\n'),
    },
  ],
};
