import type { Trilha } from '../types';

export const ETICA: Trilha = {
  id: 'etica',
  titulo: 'Ética, sigilo e segurança',
  subtitulo: 'O que não se negocia',
  icone: 'ShieldCheck',
  cor: '#4C6EF5',
  publico: 'Todo mundo, sem exceção.',
  aulas: [
    {
      id: 'oab',
      videoPlanejado: true,
      titulo: 'Estatuto e Código de Ética no dia a dia',
      resumo: 'As regras da OAB que aparecem na sua semana, não no seu exame.',
      minutos: 9,
      manual: [
        '## Não prometa resultado',
        '',
        '> **Art. 41 do Código de Ética.** É vedado ao advogado prometer resultado.',
        '',
        'Vale para a conversa com o cliente, para o anúncio, para o áudio de WhatsApp e para o texto que a IA escreveu e você não leu.',
        '',
        '**Linguagem certa:** "o objetivo da ação é", "o que buscamos é", "você pode ter direito a", "nos casos parecidos costuma-se discutir".',
        '',
        '**Linguagem proibida:** "você vai receber", "é certo que", "garantimos", "não tem como perder".',
        '',
        '## Publicidade',
        '',
        'A publicidade da advocacia é informativa, não mercantil. Não se anuncia valor de causa ganha, não se usa caso de cliente sem autorização, não se promete êxito.',
        '',
        'Depoimento de cliente tem regra própria. **Nada sai em nome do escritório sem passar pelo Marketing.**',
        '',
        '## Captação',
        '',
        'Não se capta cliente de forma vedada. A entrada de cliente aqui é pelos canais do escritório, não por abordagem individual sua fora deles.',
        '',
        '## Honorários',
        '',
        '- O contrato é do **escritório** com o cliente, não seu com o cliente.',
        '- **Art. 23 do Estatuto**: os honorários de sucumbência pertencem ao advogado, por direito próprio, e por isso **não integram a base do honorário contratual**.',
        '- **Art. 50 do Código de Ética**: em caso de êxito, o total recebido pelo advogado não pode ultrapassar a vantagem obtida pelo cliente.',
        '',
        '## Sigilo',
        '',
        'Sigilo profissional não termina com o contrato, nem com sua saída do escritório. Vale para o caso, para o nome do cliente e para o que você soube por causa da função.',
        '',
        '## Conflito de interesses',
        '',
        'Antes de aceitar caso novo, verifique se o escritório já atua contra aquela parte ou já atuou para ela. Conflito descoberto depois custa o caso e a credibilidade.',
        '',
        '## Diligência',
        '',
        'O regimento é explícito: elaborar em tempo hábil todas as peças e recursos cabíveis, acompanhar a tramitação em todas as instâncias, e responder pelos danos causados por dolo ou culpa, sem prejuízo da responsabilidade disciplinar.',
        '',
        '> Traduzindo: prazo perdido não é só problema interno. Pode virar ação de responsabilidade e processo na OAB.',
      ].join('\n'),
      checklist: [
        'Sei reescrever qualquer frase de promessa em linguagem de objetivo.',
        'Sei que sucumbência não entra na base do contratual.',
        'Verifico conflito de interesses antes de aceitar caso.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre ética profissional no dia a dia do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: advogados, estagiários e back office. Precisa ser aplicável, não teórico.',
        'TOM: firme e concreto, com exemplos de fala.',
        '',
        'ROTEIRO:',
        '1. O artigo 41 do Código de Ética e a proibição de prometer resultado, valendo para conversa, anúncio, áudio e texto escrito por IA. Dê exemplos de linguagem certa e de linguagem proibida, lendo as frases.',
        '2. Publicidade informativa e não mercantil, sem valor de causa ganha e sem caso de cliente sem autorização. Nada sai em nome do escritório sem passar pelo Marketing.',
        '3. Captação: a entrada de cliente é pelos canais do escritório.',
        '4. Honorários: o contrato é do escritório com o cliente; o artigo 23 do Estatuto, segundo o qual a sucumbência pertence ao advogado por direito próprio e por isso não integra a base do contratual; e o artigo 50 do Código de Ética, pelo qual em êxito o total recebido pelo advogado não pode ultrapassar a vantagem do cliente.',
        '5. Sigilo que não termina com o contrato nem com a saída do escritório.',
        '6. Conflito de interesses verificado antes de aceitar o caso.',
        '7. Feche com a diligência exigida pelo regimento e o alerta de que prazo perdido pode virar ação de responsabilidade e processo na OAB.',
        '',
        'NÃO FAÇA: transformar em aula de exame de ordem; manter tudo em exemplos da rotina do escritório.',
      ].join('\n'),
    },

    {
      id: 'lgpd',
      titulo: 'LGPD e dados do cliente',
      resumo: 'O que você trata, como guarda e o que fazer se vazar.',
      minutos: 8,
      manual: [
        '## Que dados nós tratamos',
        '',
        'Nome, CPF, RG, endereço, telefone, número do benefício, extratos, contratos, dados bancários e, em casos trabalhistas e previdenciários, **dados de saúde** — que são dados sensíveis, com proteção maior.',
        '',
        'Também tratamos as credenciais que o cliente nos confia, como a senha do gov.br para tirar HISCON e HISCRE.',
        '',
        '## As regras práticas',
        '',
        '1. **Finalidade** — o dado se usa para o caso do cliente. Para mais nada.',
        '2. **Mínimo necessário** — não peça documento que o caso não exige.',
        '3. **Guarda** — dado de cliente mora na pasta do cliente no Drive do escritório e no hub. Não no seu desktop, não no seu WhatsApp pessoal, não na sua nuvem pessoal.',
        '4. **Compartilhamento** — só com quem precisa, dentro do escritório, e com o cliente. Nunca em grupo, nunca com terceiro sem autorização.',
        '5. **Descarte** — documento impresso que não serve mais se destrói, não se joga no lixo inteiro.',
        '',
        '## Ao sair de perto do computador',
        '',
        'Bloqueie a tela. Parece pequeno. Não é: o hub aberto mostra a carteira inteira do escritório.',
        '',
        '## Se algo vazou',
        '',
        '1. **Avise a coordenação imediatamente.** Não tente resolver sozinho, não apague rastro.',
        '2. Descreva o que aconteceu, que dado foi exposto, para quem e quando.',
        '3. A comunicação a autoridade e a titulares tem prazo curto e é decisão do escritório, não sua.',
        '',
        '> Ninguém aqui é punido por avisar cedo. O problema começa quando se esconde.',
        '',
        '## Backup',
        '',
        'O que está no Drive e no hub tem backup do escritório. O que está só na sua máquina, não. Mais um motivo para nada viver só na sua máquina.',
      ].join('\n'),
      checklist: [
        'Nada de cliente vive só na minha máquina ou no meu WhatsApp.',
        'Bloqueio a tela ao sair.',
        'Sei o que fazer nos primeiros minutos de um vazamento.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre LGPD e proteção de dados de cliente no escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: toda a equipe, incluindo quem não é advogado.',
        'TOM: prático e sem juridiquês.',
        '',
        'ROTEIRO:',
        '1. Que dados o escritório trata, incluindo dados sensíveis de saúde em casos trabalhistas e previdenciários, e as credenciais que o cliente confia, como a senha do gov.br.',
        '2. As cinco regras práticas: finalidade, mínimo necessário, guarda no Drive e no hub e não em máquina ou nuvem pessoal, compartilhamento restrito, e descarte com destruição de papel.',
        '3. Bloquear a tela ao sair, explicando que o hub aberto mostra a carteira inteira do escritório.',
        '4. O que fazer se algo vazou: avisar a coordenação imediatamente, não tentar resolver sozinho, não apagar rastro, descrever o que foi exposto, para quem e quando. Explicar que a comunicação à autoridade tem prazo curto e é decisão do escritório. Repetir que ninguém é punido por avisar cedo.',
        '5. Feche com backup: o que está no Drive e no hub tem backup, o que está só na máquina pessoal não tem.',
        '',
        'NÃO FAÇA: citar artigo de lei sem explicar; assustar sem dar o procedimento.',
      ].join('\n'),
    },

    {
      id: 'seguranca',
      titulo: 'Segurança do dia a dia',
      resumo: 'Senha, certificado digital, golpe e o que fazer quando desconfiar.',
      minutos: 7,
      manual: [
        '## Senhas',
        '',
        '- Uma senha por serviço, forte, guardada em gerenciador — não em papel na gaveta nem em arquivo chamado "senhas".',
        '- **Segundo fator** ligado onde houver.',
        '- Senha do escritório não circula por WhatsApp, e-mail ou áudio.',
        '- Suspeitou que alguém viu? Troque na hora e avise.',
        '',
        '## Certificado digital',
        '',
        'É a sua assinatura. Protocolo feito com ele é feito por **você**, com a sua OAB.',
        '',
        '- Não empreste a senha do certificado.',
        '- Não deixe o token conectado em máquina compartilhada.',
        '- Perdeu ou desconfiou de uso indevido? Revogue e comunique.',
        '',
        '## Golpes que atingem escritório',
        '',
        '- **Falso cliente** pedindo alteração de conta para repasse. **Confirme sempre pelo canal que você já usava** — nunca pelo número novo que pediu a mudança.',
        '- **Falso banco / falso tribunal** com link de "intimação". Tribunal não manda link por WhatsApp.',
        '- **Falso sócio** pedindo transferência urgente. Confirme por voz, por canal conhecido.',
        '- **Cliente pedindo repasse na conta de outra pessoa.** Só com autorização formal e documentada.',
        '',
        '> Golpe funciona por urgência. Toda vez que a mensagem disser "agora", "urgente", "antes que feche", desacelere e confirme.',
        '',
        '## Máquina e rede',
        '',
        '- Sistema e navegador atualizados.',
        '- Nada de instalar programa aleatório na máquina de trabalho.',
        '- Wi-fi público sem rede segura: evite abrir o hub e os tribunais.',
        '',
        '## Ao desligar-se do escritório',
        '',
        'Os acessos são revogados no mesmo dia. Documento de cliente não vai junto — nem cópia. O sigilo continua valendo depois da saída.',
      ].join('\n'),
      checklist: [
        'Uso gerenciador de senhas e segundo fator.',
        'Nunca empresto a senha do certificado digital.',
        'Confirmo mudança de conta de repasse pelo canal antigo.',
      ],
      promptVideo: [
        'Gere um vídeo de 3 a 5 minutos sobre segurança digital no dia a dia do escritório Frider Andrade | Advogados.',
        '',
        'PÚBLICO: toda a equipe.',
        'TOM: direto, com exemplos de golpe reais e reconhecíveis.',
        '',
        'ROTEIRO:',
        '1. Senhas: uma por serviço, em gerenciador, com segundo fator, sem circular por WhatsApp ou áudio, e troca imediata em caso de suspeita.',
        '2. Certificado digital como assinatura pessoal: protocolo feito com ele é feito pela pessoa, com a OAB dela. Não emprestar senha, não deixar token em máquina compartilhada, revogar e comunicar em caso de perda.',
        '3. Os quatro golpes que atingem escritório: falso cliente pedindo mudança de conta de repasse, falso tribunal com link de intimação por WhatsApp, falso sócio pedindo transferência urgente, e cliente pedindo repasse na conta de terceiro. Ensine a regra de confirmar sempre pelo canal antigo, nunca pelo canal novo que pediu a mudança.',
        '4. A heurística central: golpe funciona por urgência, então toda mensagem que diz agora, urgente ou antes que feche pede desaceleração e confirmação.',
        '5. Máquina e rede: atualização, nada de programa aleatório, cuidado com wi-fi público.',
        '6. Feche com o desligamento: acessos revogados no mesmo dia, nenhum documento de cliente vai junto, e o sigilo continua valendo depois da saída.',
        '',
        'NÃO FAÇA: dar instruções técnicas de invasão; usar caso real identificável.',
      ].join('\n'),
    },
  ],
};
