"""
Roteiro visual de cada aula: em que segundo entra cada tela.

Os tempos vêm da transcrição (o .vtt da aula), não de chute — cada corte cai
numa pausa da narração, entre um assunto e o seguinte. Para levantá-los:

    curl -s .../academia/<slug>.vtt | grep ' --> '

Regra ao escrever: a tela acompanha o que está sendo dito. Slide que fica
parado enquanto a narração já mudou de assunto é pior que slide nenhum, porque
compete com quem escuta.
"""

ROTEIROS = {
    # 1.5 — Suas ferramentas e seus acessos (2:52). Saiu abaixo dos 3 minutos
    # pedidos, e tudo bem: o roteiro inteiro foi coberto. A aula é uma lista de
    # ferramentas, não tem o que esticar sem encher linguiça.
    #
    # A transcrição trouxe "AZAS" por ASAAS e "co-work" por Cowork — o áudio
    # está certo, a grafia não. Mesmo padrão do Claude/Cloud. Corrigido na
    # legenda e os dois nomes entraram no glossário do legendador.
    'ferramentas': {
        'duracao': 172.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 5',
             'titulo': 'Suas ferramentas e seus acessos',
             'sub': ['O que você usa, onde cada coisa vive', 'e o que pedir ao RH.']},

            {'t': 11.0, 'tipo': 'frase', 'secao': 'O centro de tudo', 'corpo': 52,
             'linhas': ['O hub.'],
             'rodape': 'O fluxo de trabalho inteiro, do primeiro contato ao repasse, acontece dentro dele.'},

            {'t': 17.0, 'tipo': 'cartoes', 'secao': 'O que o hub faz',
             'titulo': 'Quatro frentes numa tela só', 'cartoes': [
               {'icone': 'chat',       'titulo': 'Atendimento', 'sub': 'WhatsApp, pelos agentes de IA'},
               {'icone': 'pasta',      'titulo': 'Kanban',      'sub': 'onde cada processo mora'},
               {'icone': 'relogio',    'titulo': 'Prazos',      'sub': 'agenda e controladoria'},
               {'icone': 'dinheiro',   'titulo': 'Financeiro',  'sub': 'RH, calculadoras e peças'}], 'aceso': None},

            {'t': 35.0, 'tipo': 'contraste', 'secao': 'Duas ferramentas, dois papéis',
             'esquerda': {'rotulo': 'Agentes de IA do hub', 'titulo': 'Falam com o cliente',
                          'linhas': ['Recebem, triam e respondem', 'no WhatsApp.']},
             'direita': {'rotulo': 'Claude, no Cowork', 'titulo': 'Monta a peça', 'manda': True,
                         'linhas': ['Peça, pesquisa e revisão,', 'com as skills do escritório.',
                                    'Não fala com cliente.']}},

            {'t': 59.0, 'tipo': 'lista', 'secao': 'As outras ferramentas',
             'titulo': 'Cada uma com um trabalho', 'itens': ['Google Drive: a pasta de cada cliente e os modelos',
                       'ZapSign: assinatura de contrato e procuração',
                       'Cálculo Jurídico: execução que a calculadora do hub não cobre',
                       'ASAAS: cobrança por boleto, PIX e cartão',
                       'PJe, e-SAJ, Projudi e eproc: onde se protocola'], 'aceso': None},
            {'t': 66.0, 'tipo': 'lista', 'secao': 'As outras ferramentas',
             'titulo': 'Cada uma com um trabalho', 'itens': ['Google Drive: a pasta de cada cliente e os modelos',
                       'ZapSign: assinatura de contrato e procuração',
                       'Cálculo Jurídico: execução que a calculadora do hub não cobre',
                       'ASAAS: cobrança por boleto, PIX e cartão',
                       'PJe, e-SAJ, Projudi e eproc: onde se protocola'], 'aceso': 1},
            {'t': 74.0, 'tipo': 'lista', 'secao': 'As outras ferramentas',
             'titulo': 'Cada uma com um trabalho', 'itens': ['Google Drive: a pasta de cada cliente e os modelos',
                       'ZapSign: assinatura de contrato e procuração',
                       'Cálculo Jurídico: execução que a calculadora do hub não cobre',
                       'ASAAS: cobrança por boleto, PIX e cartão',
                       'PJe, e-SAJ, Projudi e eproc: onde se protocola'], 'aceso': 3},
            {'t': 85.0, 'tipo': 'lista', 'secao': 'As outras ferramentas',
             'titulo': 'Cada uma com um trabalho', 'itens': ['Google Drive: a pasta de cada cliente e os modelos',
                       'ZapSign: assinatura de contrato e procuração',
                       'Cálculo Jurídico: execução que a calculadora do hub não cobre',
                       'ASAAS: cobrança por boleto, PIX e cartão',
                       'PJe, e-SAJ, Projudi e eproc: onde se protocola'], 'aceso': 5},

            {'t': 93.0, 'tipo': 'lista', 'secao': 'Seus acessos',
             'titulo': 'Seis, e nenhum a menos', 'itens': ['E-mail do escritório',
                       'Login no hub',
                       'Google Drive do escritório',
                       'Claude no Cowork, com as skills instaladas',
                       'Certificado digital e cadastro nos tribunais',
                       'WhatsApp do escritório configurado no hub'], 'aceso': None},
            {'t': 108.0, 'tipo': 'lista', 'secao': 'Seus acessos',
             'titulo': 'Seis, e nenhum a menos', 'itens': ['E-mail do escritório',
                       'Login no hub',
                       'Google Drive do escritório',
                       'Claude no Cowork, com as skills instaladas',
                       'Certificado digital e cadastro nos tribunais',
                       'WhatsApp do escritório configurado no hub'], 'aceso': 5},
            {'t': 112.0, 'tipo': 'lista', 'secao': 'Seus acessos',
             'titulo': 'Seis, e nenhum a menos', 'itens': ['E-mail do escritório',
                       'Login no hub',
                       'Google Drive do escritório',
                       'Claude no Cowork, com as skills instaladas',
                       'Certificado digital e cadastro nos tribunais',
                       'WhatsApp do escritório configurado no hub'], 'aceso': 6,
             'rodape': 'Seu número pessoal nunca entra no atendimento.'},

            {'t': 119.0, 'tipo': 'frase', 'secao': 'Quanto tempo leva', 'corpo': 50,
             'linhas': ['Até 48 horas', 'depois do ingresso.'],
             'rodape': 'Passou disso e falta alguma coisa? O que faltar se pede ao RH.'},

            {'t': 133.0, 'tipo': 'lista', 'secao': 'A regra de ouro',
             'titulo': 'Três linhas que não se cruzam',
             'itens': ['Senha do escritório não circula por WhatsApp',
                       'Senha não fica anotada em papel na mesa',
                       'Cada pessoa usa o próprio login'],
             'aceso': None},
            {'t': 149.0, 'tipo': 'lista', 'secao': 'A regra de ouro',
             'titulo': 'Três linhas que não se cruzam',
             'itens': ['Senha do escritório não circula por WhatsApp',
                       'Senha não fica anotada em papel na mesa',
                       'Cada pessoa usa o próprio login'],
             'aceso': 3},

            {'t': 153.0, 'tipo': 'frase', 'corpo': 44,
             'linhas': ['Trabalho feito no login de outro', 'não tem dono.',
                        'E prazo sem dono é prazo perdido.']},
        ],
    },

    # 1.4 — As regras do jogo: regimento interno na prática (3:58).
    #
    # O quadro das sanções é o miolo: dois vínculos, três graus cada, seis
    # números que TÊM de bater com o manual. Conferidos um a um na transcrição
    # antes de montar — é o tipo de tela em que um número errado vira promessa
    # falsa sobre o emprego de quem assiste.
    'regras-do-jogo': {
        'duracao': 238.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 4',
             'titulo': 'As regras do jogo',
             'sub': ['O regimento interno traduzido', 'para o que você faz hoje.']},

            {'t': 10.5, 'tipo': 'frase', 'secao': 'A obrigação número um', 'corpo': 46,
             'linhas': ['Cumprir e fazer cumprir', 'prazos judiciais.'],
             'rodape': 'Abre a lista porque é a linha de defesa do cliente. Falha aqui compromete o resto.'},

            {'t': 24.2, 'tipo': 'lista', 'secao': 'Suas obrigações',
             'titulo': 'As que mais pesam', 'itens': ['Registrar toda movimentação no hub',
                       'Sigilo sobre tudo que souber pela função',
                       'OAB e obrigações profissionais em dia',
                       'Urbanidade com todo mundo',
                       'Estatuto e Código de Ética acima da regra interna'], 'aceso': None},
            {'t': 33.9, 'tipo': 'lista', 'secao': 'Suas obrigações',
             'titulo': 'As que mais pesam', 'itens': ['Registrar toda movimentação no hub',
                       'Sigilo sobre tudo que souber pela função',
                       'OAB e obrigações profissionais em dia',
                       'Urbanidade com todo mundo',
                       'Estatuto e Código de Ética acima da regra interna'], 'aceso': 1,
             'rodape': 'Sem registro não há controle de prazo nem prova do que foi feito.'},
            {'t': 41.3, 'tipo': 'lista', 'secao': 'Suas obrigações',
             'titulo': 'As que mais pesam', 'itens': ['Registrar toda movimentação no hub',
                       'Sigilo sobre tudo que souber pela função',
                       'OAB e obrigações profissionais em dia',
                       'Urbanidade com todo mundo',
                       'Estatuto e Código de Ética acima da regra interna'], 'aceso': 3},

            {'t': 48.8, 'tipo': 'lista', 'secao': 'Proibições',
             'titulo': 'Os limites', 'itens': ['Falar em nome do escritório sem o Marketing',
                       'Usar recurso material ou humano em atividade particular',
                       'Cuidar de assunto pessoal no expediente',
                       'Retirar documento do escritório sem autorização',
                       'Usar a razão social para fim estranho à sociedade'], 'aceso': None},
            {'t': 61.8, 'tipo': 'lista', 'secao': 'Proibições',
             'titulo': 'Os limites', 'itens': ['Falar em nome do escritório sem o Marketing',
                       'Usar recurso material ou humano em atividade particular',
                       'Cuidar de assunto pessoal no expediente',
                       'Retirar documento do escritório sem autorização',
                       'Usar a razão social para fim estranho à sociedade'], 'aceso': 1,
             'rodape': 'Por qualquer meio: post, áudio, grupo, entrevista. Sem o Marketing, não sai.'},
            {'t': 83.9, 'tipo': 'lista', 'secao': 'Proibições',
             'titulo': 'Os limites', 'itens': ['Falar em nome do escritório sem o Marketing',
                       'Usar recurso material ou humano em atividade particular',
                       'Cuidar de assunto pessoal no expediente',
                       'Retirar documento do escritório sem autorização',
                       'Usar a razão social para fim estranho à sociedade'], 'aceso': 2},

            {'t': 101.7, 'tipo': 'fluxo', 'secao': 'Quando se descumpre',
             'titulo': 'Três graus', 'etapas': ['Leve', 'Média', 'Grave'], 'aceso': None,
             'rodape': 'Leve e média: Diretoria de RH. Grave: vai à Assembleia Geral.'},
            {'t': 115.5, 'tipo': 'fluxo', 'secao': 'Quando se descumpre',
             'titulo': 'Três graus', 'etapas': ['Leve', 'Média', 'Grave'], 'aceso': 3,
             'rodape': 'Leve e média: Diretoria de RH. Grave: vai à Assembleia Geral.'},

            # Os seis números abaixo são do manual, conferidos na transcrição.
            {'t': 124.5, 'tipo': 'contraste', 'secao': 'A sanção por vínculo',
             'esquerda': {'rotulo': 'Empregados', 'titulo': 'Suspensão', 'manda': True,
                          'linhas': ['Leve: advertência até 6 dias.', 'Média: 7 a 15 dias.',
                                     'Grave: 16 dias até a demissão.']},
             'direita': {'rotulo': 'Sócios e associados', 'titulo': 'Sem processos',
                         'linhas': ['Leve: advertência até 1 semana.', 'Média: 1 a 3 semanas.',
                                    'Grave: 3 a 4 semanas ou rescisão.']}},
            {'t': 135.8, 'tipo': 'contraste', 'secao': 'A sanção por vínculo',
             'esquerda': {'rotulo': 'Empregados', 'titulo': 'Suspensão',
                          'linhas': ['Leve: advertência até 6 dias.', 'Média: 7 a 15 dias.',
                                     'Grave: 16 dias até a demissão.']},
             'direita': {'rotulo': 'Sócios e associados', 'titulo': 'Sem processos', 'manda': True,
                         'linhas': ['Leve: advertência até 1 semana.', 'Média: 1 a 3 semanas.',
                                    'Grave: 3 a 4 semanas ou rescisão.']}},

            {'t': 150.3, 'tipo': 'frase', 'secao': 'Por que dói', 'corpo': 44,
             'linhas': ['Parar de receber processo', 'atinge a remuneração por êxito.'],
             'rodape': 'É de propósito.'},

            {'t': 169.2, 'tipo': 'frase', 'secao': 'A regra que salva', 'corpo': 44,
             'linhas': ['Doença, audiência sobreposta,', 'sistema do tribunal fora do ar:', 'isso a equipe resolve.'],
             'rodape': 'O que a equipe não resolve é o que ela não sabe.'},

            {'t': 194.0, 'tipo': 'frase', 'secao': 'Está no regimento', 'corpo': 40,
             'linhas': ['A ausência de comunicação', 'transforma um problema contornável',
                        'em falha irreversível.']},

            {'t': 209.2, 'tipo': 'contraste', 'secao': 'A diferença',
             'esquerda': {'rotulo': 'Avisou cedo', 'titulo': 'Sem punição', 'manda': True,
                          'linhas': ['Ninguém aqui é punido', 'por avisar a tempo.']},
             'direita': {'rotulo': 'Avisou depois', 'titulo': 'Cobrança',
                         'linhas': ['A cobrança recai sobre quem', 'conta quando já era.']}},

            {'t': 227.3, 'tipo': 'frase', 'corpo': 42,
             'linhas': ['Se a antecipação resolve', 'quase toda crise,', 'por que deixar o silêncio decidir?']},
        ],
    },

    # 1.3 — Como o escritório funciona por dentro (3:18). Segunda geração: a
    # primeira narrou uma meta de 48h para cadastro que NÃO existe no material,
    # e traduziu Back Office e Marketing por causa da regra que proíbe inglês.
    # As duas coisas viraram correção de prompt e de regra fixa.
    #
    # O contraste das assembleias aparece duas vezes, trocando o lado aceso:
    # sem isso os dois lados ficam cinza ao mesmo tempo, porque é o 'manda' que
    # acende a coluna — e aqui nenhum lado "vence" o outro, eles se alternam
    # conforme a narração fala de um e depois do outro.
    'como-funciona': {
        'duracao': 198.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 3',
             'titulo': 'Como o escritório funciona por dentro',
             'sub': ['Quem faz o quê, quem decide o quê', 'e o que se espera de você.']},

            {'t': 16.8, 'tipo': 'lista', 'secao': 'Os cargos',
             'titulo': 'Cinco níveis', 'itens': ['Estagiário: formação prática, sempre supervisionada',
                       'Back Office: cadastro, documentos e organização',
                       'Associado: conduz o processo de ponta a ponta',
                       'Sócio: carteira de clientes e gestão',
                       'Sócio nominal: capital, estatuto e entrada de sócios'], 'aceso': None},
            {'t': 29.5, 'tipo': 'lista', 'secao': 'Os cargos',
             'titulo': 'Cinco níveis', 'itens': ['Estagiário: formação prática, sempre supervisionada',
                       'Back Office: cadastro, documentos e organização',
                       'Associado: conduz o processo de ponta a ponta',
                       'Sócio: carteira de clientes e gestão',
                       'Sócio nominal: capital, estatuto e entrada de sócios'], 'aceso': 3,
             'rodape': 'Se você entrou como advogado, é aqui que você está.'},
            {'t': 40.0, 'tipo': 'lista', 'secao': 'Os cargos',
             'titulo': 'Cinco níveis', 'itens': ['Estagiário: formação prática, sempre supervisionada',
                       'Back Office: cadastro, documentos e organização',
                       'Associado: conduz o processo de ponta a ponta',
                       'Sócio: carteira de clientes e gestão',
                       'Sócio nominal: capital, estatuto e entrada de sócios'], 'aceso': 5},

            {'t': 47.0, 'tipo': 'lista', 'secao': 'Os setores',
             'titulo': 'Sete áreas', 'itens': ['Controladoria Jurídica', 'Back Office', 'Diretoria Estratégica',
                       'Diretoria de RH', 'Diretoria de Marketing',
                       'Diretoria Operacional', 'Diretoria Financeira'], 'aceso': None},
            {'t': 65.8, 'tipo': 'lista', 'secao': 'Os setores',
             'titulo': 'Sete áreas', 'itens': ['Controladoria Jurídica', 'Back Office', 'Diretoria Estratégica',
                       'Diretoria de RH', 'Diretoria de Marketing',
                       'Diretoria Operacional', 'Diretoria Financeira'], 'aceso': 1,
             'rodape': 'É o setor que impede prazo de morrer e documento de sumir.'},

            {'t': 81.8, 'tipo': 'contraste', 'secao': 'Quem decide o quê',
             'esquerda': dict({'rotulo': 'Assembleia de Sócios Nominais', 'titulo': 'Estrutura',
                          'linhas': ['Capital social e estatuto.', 'Entrada e saída de sócios.',
                                     'Alienação de cotas.']}, manda=True),
             'direita': {'rotulo': 'Assembleia de Sócios', 'titulo': 'Operação',
                         'linhas': ['Rotina e gestão.', 'Metas e remuneração.',
                                    'Punições e desligamentos.']}},
            {'t': 94.5, 'tipo': 'contraste', 'secao': 'Quem decide o quê',
             'esquerda': {'rotulo': 'Assembleia de Sócios Nominais', 'titulo': 'Estrutura',
                          'linhas': ['Capital social e estatuto.', 'Entrada e saída de sócios.',
                                     'Alienação de cotas.']},
             'direita': dict({'rotulo': 'Assembleia de Sócios', 'titulo': 'Operação',
                         'linhas': ['Rotina e gestão.', 'Metas e remuneração.',
                                    'Punições e desligamentos.']}, manda=True)},

            {'t': 107.5, 'tipo': 'frase', 'secao': 'A regra prática', 'corpo': 46,
             'linhas': ['Se muda a estrutura', 'ou o dinheiro do escritório,', 'não é decisão sua.'],
             'rodape': 'As diretorias executam; não deliberam sobre isso. Leve à coordenação.'},

            {'t': 122.8, 'tipo': 'frase', 'secao': 'Plano de carreira', 'corpo': 44,
             'linhas': ['Associado pode virar sócio.', 'Não é automático', 'nem é de curto prazo.']},

            {'t': 134.0, 'tipo': 'cartoes', 'secao': 'Plano de carreira',
             'titulo': 'O que pesa na avaliação', 'cartoes': [
               {'icone': 'dinheiro',  'titulo': 'Resultado', 'sub': 'o que a carteira entrega'},
               {'icone': 'relogio',   'titulo': 'Prazo',     'sub': 'cumprimento, sem exceção'},
               {'icone': 'documento', 'titulo': 'Técnica',   'sub': 'qualidade da peça'},
               {'icone': 'pessoa',    'titulo': 'Postura',   'sub': 'com cliente e com a equipe'}], 'aceso': None},

            {'t': 142.5, 'tipo': 'lista', 'secao': 'O que se espera de você',
             'titulo': 'No cargo de associado', 'itens': ['Conduzir o caso do cadastro ao repasse',
                       '100% de prazos e zero audiência perdida',
                       'Resposta ao cliente no mesmo dia',
                       'Hub sempre atualizado',
                       '5 dias úteis para montar as ações do cliente novo'], 'aceso': None},
            {'t': 153.5, 'tipo': 'lista', 'secao': 'O que se espera de você',
             'titulo': 'No cargo de associado', 'itens': ['Conduzir o caso do cadastro ao repasse',
                       '100% de prazos e zero audiência perdida',
                       'Resposta ao cliente no mesmo dia',
                       'Hub sempre atualizado',
                       '5 dias úteis para montar as ações do cliente novo'], 'aceso': 3},
            {'t': 159.0, 'tipo': 'lista', 'secao': 'O que se espera de você',
             'titulo': 'No cargo de associado', 'itens': ['Conduzir o caso do cadastro ao repasse',
                       '100% de prazos e zero audiência perdida',
                       'Resposta ao cliente no mesmo dia',
                       'Hub sempre atualizado',
                       '5 dias úteis para montar as ações do cliente novo'], 'aceso': 4,
             'rodape': 'O que não está no hub não existe.'},
            {'t': 165.5, 'tipo': 'lista', 'secao': 'O que se espera de você',
             'titulo': 'No cargo de associado', 'itens': ['Conduzir o caso do cadastro ao repasse',
                       '100% de prazos e zero audiência perdida',
                       'Resposta ao cliente no mesmo dia',
                       'Hub sempre atualizado',
                       '5 dias úteis para montar as ações do cliente novo'], 'aceso': 5},

            {'t': 172.5, 'tipo': 'fluxo', 'secao': 'Quando atrasa',
             'titulo': 'O que acontece com o caso',
             'etapas': ['Montagem atrasa', 'Caso é redistribuído', 'Cliente segue atendido'],
             'aceso': 3,
             'rodape': 'A medida protege o cliente, que não pode esperar. Não é punição.'},

            {'t': 187.0, 'tipo': 'frase', 'corpo': 42,
             'linhas': ['A estrutura existe', 'para quem confia no escritório', 'não depender de sorte.']},
        ],
    },

    # 8.1 — Estatuto e Código de Ética no dia a dia (4:44). A narração anuncia
    # o título de cada bloco em voz alta, o que entrega os cortes prontos: cada
    # anúncio é o começo de uma seção. A tela do meio, linguagem certa ou
    # proibida, é a mais útil do vídeo e por isso fica parada os 31 segundos em
    # que as frases são lidas uma a uma.
    'oab': {
        'duracao': 284.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 8 · Aula 1',
             'titulo': 'Estatuto e Código de Ética no dia a dia',
             'sub': ['A regra não vive no exame de ordem.', 'Vive na frase que você manda hoje.']},

            {'t': 20.8, 'tipo': 'frase', 'secao': 'Promessa de resultado', 'corpo': 48,
             'linhas': ['Prometer resultado', 'é proibido.'],
             'rodape': 'Na conversa, no anúncio, no áudio — e no texto escrito por inteligência artificial.'},

            {'t': 44.5, 'tipo': 'cartoes', 'secao': 'De onde vem a regra',
             'titulo': 'Duas frentes, não uma', 'cartoes': [
               {'icone': 'balanca',   'titulo': 'Provimento 205/2021, art. 6º',
                'sub': 'proíbe prometer resultado na publicidade'},
               {'icone': 'documento', 'titulo': 'Código de Ética, art. 9º',
                'sub': 'obriga informar o risco com clareza'}], 'aceso': None},
            {'t': 48.9, 'tipo': 'cartoes', 'secao': 'De onde vem a regra',
             'titulo': 'Duas frentes, não uma', 'cartoes': [
               {'icone': 'balanca',   'titulo': 'Provimento 205/2021, art. 6º',
                'sub': 'proíbe prometer resultado na publicidade'},
               {'icone': 'documento', 'titulo': 'Código de Ética, art. 9º',
                'sub': 'obriga informar o risco com clareza'}], 'aceso': 1},
            {'t': 56.3, 'tipo': 'cartoes', 'secao': 'De onde vem a regra',
             'titulo': 'Duas frentes, não uma', 'cartoes': [
               {'icone': 'balanca',   'titulo': 'Provimento 205/2021, art. 6º',
                'sub': 'proíbe prometer resultado na publicidade'},
               {'icone': 'documento', 'titulo': 'Código de Ética, art. 9º',
                'sub': 'obriga informar o risco com clareza'}], 'aceso': 2},

            # A tela mais útil do vídeo: as frases exatas. Fica os 31s em que a
            # narração lê uma a uma — dividir aqui só faria perder a comparação.
            {'t': 69.3, 'tipo': 'contraste', 'secao': 'A escolha das palavras',
             'esquerda': {'rotulo': 'Pode dizer', 'titulo': 'Assim', 'manda': True,
                          'linhas': ['"O objetivo da ação é..."', '"O que buscamos é..."',
                                     '"A senhora pode ter direito a..."']},
             'direita': {'rotulo': 'Nunca diga', 'titulo': 'Assim não',
                         'linhas': ['"A senhora vai receber."', '"É certo que..."',
                                    '"Garantimos."', '"Não tem como perder."']}},

            {'t': 100.7, 'tipo': 'lista', 'secao': 'Publicidade e captação',
             'titulo': 'Cinco limites inegociáveis', 'itens': ['Informativa, nunca mercantil',
                       'Sem valor de causa ganha',
                       'Caso real só com autorização documentada',
                       'Nada sai em nome do escritório sem o Marketing',
                       'Cliente entra pelos canais oficiais da banca'], 'aceso': None},
            {'t': 125.3, 'tipo': 'lista', 'secao': 'Publicidade e captação',
             'titulo': 'Cinco limites inegociáveis', 'itens': ['Informativa, nunca mercantil',
                       'Sem valor de causa ganha',
                       'Caso real só com autorização documentada',
                       'Nada sai em nome do escritório sem o Marketing',
                       'Cliente entra pelos canais oficiais da banca'], 'aceso': 1},
            {'t': 128.4, 'tipo': 'lista', 'secao': 'Publicidade e captação',
             'titulo': 'Cinco limites inegociáveis', 'itens': ['Informativa, nunca mercantil',
                       'Sem valor de causa ganha',
                       'Caso real só com autorização documentada',
                       'Nada sai em nome do escritório sem o Marketing',
                       'Cliente entra pelos canais oficiais da banca'], 'aceso': 3},
            {'t': 136.0, 'tipo': 'lista', 'secao': 'Publicidade e captação',
             'titulo': 'Cinco limites inegociáveis', 'itens': ['Informativa, nunca mercantil',
                       'Sem valor de causa ganha',
                       'Caso real só com autorização documentada',
                       'Nada sai em nome do escritório sem o Marketing',
                       'Cliente entra pelos canais oficiais da banca'], 'aceso': 4},
            {'t': 142.6, 'tipo': 'lista', 'secao': 'Publicidade e captação',
             'titulo': 'Cinco limites inegociáveis', 'itens': ['Informativa, nunca mercantil',
                       'Sem valor de causa ganha',
                       'Caso real só com autorização documentada',
                       'Nada sai em nome do escritório sem o Marketing',
                       'Cliente entra pelos canais oficiais da banca'], 'aceso': 5},

            {'t': 147.8, 'tipo': 'lista', 'secao': 'Honorários',
             'titulo': 'A matemática da ética', 'itens': ['O contrato é do escritório com o cliente',
                       'Sucumbência é do advogado, por direito próprio',
                       'Em êxito, o advogado não leva mais que o cliente'], 'aceso': None},
            {'t': 167.8, 'tipo': 'lista', 'secao': 'Honorários',
             'titulo': 'A matemática da ética', 'itens': ['O contrato é do escritório com o cliente',
                       'Sucumbência é do advogado, por direito próprio',
                       'Em êxito, o advogado não leva mais que o cliente'], 'aceso': 1},
            {'t': 174.1, 'tipo': 'lista', 'secao': 'Honorários',
             'titulo': 'A matemática da ética', 'itens': ['O contrato é do escritório com o cliente',
                       'Sucumbência é do advogado, por direito próprio',
                       'Em êxito, o advogado não leva mais que o cliente'], 'aceso': 2,
             'rodape': 'Art. 23 do Estatuto: por ser do advogado, a sucumbência não entra na base do contratual.'},
            {'t': 181.9, 'tipo': 'lista', 'secao': 'Honorários',
             'titulo': 'A matemática da ética', 'itens': ['O contrato é do escritório com o cliente',
                       'Sucumbência é do advogado, por direito próprio',
                       'Em êxito, o advogado não leva mais que o cliente'], 'aceso': 3,
             'rodape': 'Art. 50 do Código de Ética: o total do advogado não supera a vantagem do cliente.'},

            {'t': 191.3, 'tipo': 'linha_tempo', 'secao': 'Conflito e sigilo',
             'titulo': 'Antes, durante e depois',
             'marcos': [{'titulo': 'Antes',   'sub': 'conflito verificado antes de aceitar'},
                        {'titulo': 'Durante', 'sub': 'sigilo sobre documento e estratégia'},
                        {'titulo': 'Depois',  'sub': 'o sigilo continua'}],
             'aceso': None},
            {'t': 208.5, 'tipo': 'linha_tempo', 'secao': 'Conflito e sigilo',
             'titulo': 'Antes, durante e depois',
             'marcos': [{'titulo': 'Antes',   'sub': 'conflito verificado antes de aceitar'},
                        {'titulo': 'Durante', 'sub': 'sigilo sobre documento e estratégia'},
                        {'titulo': 'Depois',  'sub': 'o sigilo continua'}],
             'aceso': 1, 'rodape': 'Evita patrocinar contra parte que a banca já representa.'},
            {'t': 218.9, 'tipo': 'linha_tempo', 'secao': 'Conflito e sigilo',
             'titulo': 'Antes, durante e depois',
             'marcos': [{'titulo': 'Antes',   'sub': 'conflito verificado antes de aceitar'},
                        {'titulo': 'Durante', 'sub': 'sigilo sobre documento e estratégia'},
                        {'titulo': 'Depois',  'sub': 'o sigilo continua'}],
             'aceso': 2},
            {'t': 228.1, 'tipo': 'linha_tempo', 'secao': 'Conflito e sigilo',
             'titulo': 'Antes, durante e depois',
             'marcos': [{'titulo': 'Antes',   'sub': 'conflito verificado antes de aceitar'},
                        {'titulo': 'Durante', 'sub': 'sigilo sobre documento e estratégia'},
                        {'titulo': 'Depois',  'sub': 'o sigilo continua'}],
             'aceso': 3, 'rodape': 'Não acaba com o contrato, nem com a saída do escritório.'},

            {'t': 236.1, 'tipo': 'lista', 'secao': 'Prazo e diligência',
             'titulo': 'O que o regimento exige', 'itens': ['Peça elaborada em tempo hábil',
                       'Tramitação acompanhada em todas as instâncias',
                       'Prazo perdido vira ação de responsabilidade e processo na OAB'], 'aceso': None},
            {'t': 244.9, 'tipo': 'lista', 'secao': 'Prazo e diligência',
             'titulo': 'O que o regimento exige', 'itens': ['Peça elaborada em tempo hábil',
                       'Tramitação acompanhada em todas as instâncias',
                       'Prazo perdido vira ação de responsabilidade e processo na OAB'], 'aceso': 2},
            {'t': 254.1, 'tipo': 'lista', 'secao': 'Prazo e diligência',
             'titulo': 'O que o regimento exige', 'itens': ['Peça elaborada em tempo hábil',
                       'Tramitação acompanhada em todas as instâncias',
                       'Prazo perdido vira ação de responsabilidade e processo na OAB'], 'aceso': 3},

            {'t': 271.4, 'tipo': 'frase', 'corpo': 42,
             'linhas': ['A minuta que você escreve hoje', 'blinda o escritório', 'ou cria um passivo silencioso.']},
        ],
    },

    # 7.1 — Você é o escritório para o cliente (3:54). Vídeo curto, então o
    # ritmo é outro: em vez de telas novas, o mesmo quadro acende item a item
    # conforme a narração avança. Trocar de assunto a cada 8 segundos cansaria.
    'voce-e-o-escritorio': {
        'duracao': 234.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 7 · Aula 1',
             'titulo': 'Você é o escritório para o cliente',
             'sub': ['Quem atende não representa o escritório.', 'Naquele momento, ele é o escritório.']},

            {'t': 8.7, 'tipo': 'cartoes', 'secao': 'Quem está do outro lado',
             'titulo': 'O nosso cliente, em regra',
             'cartoes': [
               {'icone': 'pessoa',   'titulo': 'Idoso',         'sub': 'aposentado pelo INSS'},
               {'icone': 'dinheiro', 'titulo': 'Um a dois',     'sub': 'salários mínimos de renda'},
               {'icone': 'chat',     'titulo': 'Pouco digital', 'sub': 'ouve melhor do que lê'},
               {'icone': 'alerta',   'titulo': 'Desconfiado',   'sub': 'já foi enganado uma vez'}], 'aceso': None},
            {'t': 15.5, 'tipo': 'cartoes', 'secao': 'Quem está do outro lado',
             'titulo': 'O nosso cliente, em regra',
             'cartoes': [
               {'icone': 'pessoa',   'titulo': 'Idoso',         'sub': 'aposentado pelo INSS'},
               {'icone': 'dinheiro', 'titulo': 'Um a dois',     'sub': 'salários mínimos de renda'},
               {'icone': 'chat',     'titulo': 'Pouco digital', 'sub': 'ouve melhor do que lê'},
               {'icone': 'alerta',   'titulo': 'Desconfiado',   'sub': 'já foi enganado uma vez'}], 'aceso': 4},

            {'t': 27.7, 'tipo': 'frase', 'secao': 'Por que isso muda tudo', 'corpo': 48,
             'linhas': ['A confiança em nós', 'não vem de graça.'],
             'rodape': 'Quem assina a procuração já foi enganado por alguém que também parecia confiável.'},

            {'t': 45.9, 'tipo': 'lista', 'secao': 'O que ele espera',
             'titulo': 'Quatro expectativas', 'itens': ['Ser entendido: escutar a história inteira antes de responder',
                       'Entender: português claro, sem termo técnico solto',
                       'Saber o que vem: qual é o próximo passo',
                       'Não ser esquecido: notícia mesmo quando nada andou'], 'aceso': None},
            {'t': 61.2, 'tipo': 'lista', 'secao': 'O que ele espera',
             'titulo': 'Quatro expectativas', 'itens': ['Ser entendido: escutar a história inteira antes de responder',
                       'Entender: português claro, sem termo técnico solto',
                       'Saber o que vem: qual é o próximo passo',
                       'Não ser esquecido: notícia mesmo quando nada andou'], 'aceso': 2},
            {'t': 78.5, 'tipo': 'lista', 'secao': 'O que ele espera',
             'titulo': 'Quatro expectativas', 'itens': ['Ser entendido: escutar a história inteira antes de responder',
                       'Entender: português claro, sem termo técnico solto',
                       'Saber o que vem: qual é o próximo passo',
                       'Não ser esquecido: notícia mesmo quando nada andou'], 'aceso': 4},

            {'t': 90.4, 'tipo': 'passos', 'secao': 'O padrão de atendimento',
             'titulo': 'Como se responde aqui', 'passos': ['Resposta no mesmo dia. Sem exceção.',
                       'Nem que seja para dizer que está apurando.',
                       'Chame pelo nome, com o tratamento que ele prefere.',
                       'Feche perguntando se ficou claro.',
                       'Frases curtas; áudio quando a leitura é difícil.'], 'ate': 0},
            {'t': 100.0, 'tipo': 'passos', 'secao': 'O padrão de atendimento',
             'titulo': 'Como se responde aqui', 'passos': ['Resposta no mesmo dia. Sem exceção.',
                       'Nem que seja para dizer que está apurando.',
                       'Chame pelo nome, com o tratamento que ele prefere.',
                       'Feche perguntando se ficou claro.',
                       'Frases curtas; áudio quando a leitura é difícil.'], 'ate': 2},
            {'t': 107.3, 'tipo': 'passos', 'secao': 'O padrão de atendimento',
             'titulo': 'Como se responde aqui', 'passos': ['Resposta no mesmo dia. Sem exceção.',
                       'Nem que seja para dizer que está apurando.',
                       'Chame pelo nome, com o tratamento que ele prefere.',
                       'Feche perguntando se ficou claro.',
                       'Frases curtas; áudio quando a leitura é difícil.'], 'ate': 3},
            {'t': 114.0, 'tipo': 'passos', 'secao': 'O padrão de atendimento',
             'titulo': 'Como se responde aqui', 'passos': ['Resposta no mesmo dia. Sem exceção.',
                       'Nem que seja para dizer que está apurando.',
                       'Chame pelo nome, com o tratamento que ele prefere.',
                       'Feche perguntando se ficou claro.',
                       'Frases curtas; áudio quando a leitura é difícil.'], 'ate': 4},
            {'t': 124.2, 'tipo': 'passos', 'secao': 'O padrão de atendimento',
             'titulo': 'Como se responde aqui', 'passos': ['Resposta no mesmo dia. Sem exceção.',
                       'Nem que seja para dizer que está apurando.',
                       'Chame pelo nome, com o tratamento que ele prefere.',
                       'Feche perguntando se ficou claro.',
                       'Frases curtas; áudio quando a leitura é difícil.'], 'ate': 5},

            {'t': 141.7, 'tipo': 'lista', 'secao': 'O que sempre estraga',
             'titulo': 'Cinco maneiras de perder o cliente',
             'itens': ['Sumir por semanas',
                       'Prometer data de julgamento',
                       'Falar mal de outro profissional ou do banco',
                       'Deixar o cliente descobrir o revés pela internet',
                       'Responder com jargão'], 'aceso': None,
             'rodape': 'Nenhuma delas é sobre técnica jurídica. Todas são sobre o contato.'},
            {'t': 155.0, 'tipo': 'lista', 'secao': 'O que sempre estraga',
             'titulo': 'Cinco maneiras de perder o cliente', 'itens': ['Sumir por semanas',
                       'Prometer data de julgamento',
                       'Falar mal de outro profissional ou do banco',
                       'Deixar o cliente descobrir o revés pela internet',
                       'Responder com jargão'], 'aceso': 1},
            {'t': 158.4, 'tipo': 'lista', 'secao': 'O que sempre estraga',
             'titulo': 'Cinco maneiras de perder o cliente', 'itens': ['Sumir por semanas',
                       'Prometer data de julgamento',
                       'Falar mal de outro profissional ou do banco',
                       'Deixar o cliente descobrir o revés pela internet',
                       'Responder com jargão'], 'aceso': 2,
             'rodape': 'Em RMC e RCC, com os processos suspensos pelo STJ, nem faixa se dá.'},
            {'t': 169.8, 'tipo': 'lista', 'secao': 'O que sempre estraga',
             'titulo': 'Cinco maneiras de perder o cliente', 'itens': ['Sumir por semanas',
                       'Prometer data de julgamento',
                       'Falar mal de outro profissional ou do banco',
                       'Deixar o cliente descobrir o revés pela internet',
                       'Responder com jargão'], 'aceso': 3},
            {'t': 177.5, 'tipo': 'lista', 'secao': 'O que sempre estraga',
             'titulo': 'Cinco maneiras de perder o cliente', 'itens': ['Sumir por semanas',
                       'Prometer data de julgamento',
                       'Falar mal de outro profissional ou do banco',
                       'Deixar o cliente descobrir o revés pela internet',
                       'Responder com jargão'], 'aceso': 4},
            {'t': 182.1, 'tipo': 'lista', 'secao': 'O que sempre estraga',
             'titulo': 'Cinco maneiras de perder o cliente', 'itens': ['Sumir por semanas',
                       'Prometer data de julgamento',
                       'Falar mal de outro profissional ou do banco',
                       'Deixar o cliente descobrir o revés pela internet',
                       'Responder com jargão'], 'aceso': 5},

            {'t': 191.3, 'tipo': 'fluxo', 'secao': 'Como se dá uma notícia',
             'titulo': 'Três frases, nesta ordem',
             'etapas': ['O que aconteceu', 'O que significa para ele', 'O que vem agora'],
             'rodape': 'A mesma ordem serve para a notícia boa e para a ruim.'},

            # A narração larga a estrutura das três frases em 200,7 e passa à
            # salvaguarda. Sem esta cena o fluxo ficava 20s parado na tela
            # enquanto já se falava de outra coisa.
            {'t': 200.7, 'tipo': 'frase', 'secao': 'A salvaguarda', 'corpo': 46,
             'linhas': ['Uma regra protege os dois:', 'o cliente e o escritório.'],
             'rodape': 'Ela não é sobre técnica jurídica. É sobre o que fica escrito.'},

            {'t': 211.4, 'tipo': 'contraste', 'secao': 'A regra de ouro',
             'esquerda': {'rotulo': 'Combinado por telefone', 'titulo': 'Não existe',
                          'linhas': ['Nem para o escritório,', 'nem como prova.']},
             'direita': {'rotulo': 'Escrito no hub', 'titulo': 'Existe', 'manda': True,
                         'linhas': ['Qualquer um retoma o caso', 'de onde o outro parou.']}},

            {'t': 222.1, 'tipo': 'frase', 'corpo': 44,
             'linhas': ['Para quem está do outro lado,', 'você não representa o escritório.',
                        'Você é o escritório.']},
        ],
    },

    # 6.1 — Tese de RMC e RCC, versão completa (14:26). O roteiro mais longo:
    # 25 cenas, nenhuma passando de ~40s, porque tela parada cansa mais que
    # texto. Tempos medidos no vtt de 303 deixas.
    'rmc-rcc': {
        'duracao': 865.7,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 6 · Aula 1',
             'titulo': 'RMC e RCC: a tese principal',
             'sub': ['A mecânica da lesão, as bases legais', 'e o estado atual da carteira.']},

            {'t': 34.6, 'tipo': 'frase', 'secao': 'O que a cliente achou que fez', 'corpo': 46,
             'linhas': ['Ela pediu um empréstimo.', 'Saiu com um cartão de crédito.'],
             'rodape': 'O dinheiro veio de saque no cartão. O desconto é pagamento mínimo de fatura.'},

            {'t': 70.5, 'tipo': 'contraste', 'secao': 'O que o banco registrou',
             'esquerda': {'rotulo': 'O que ela contratou', 'titulo': 'Consignado', 'manda': True,
                          'linhas': ['Parcela fixa.', 'Prazo com fim.', 'Saldo que diminui.']},
             'direita': {'rotulo': 'O que o banco lançou', 'titulo': 'Cartão',
                         'linhas': ['Pagamento mínimo de fatura.', 'Sem prazo para acabar.',
                                    'Saldo que rola com rotativo.']}},

            {'t': 107.5, 'tipo': 'cartoes', 'secao': 'Por que é ruinoso',
             'titulo': 'Quatro danos que se somam',
             'cartoes': [
               {'icone': 'relogio',  'titulo': 'Dívida eterna', 'sub': 'juros rotativos sobre o que sobra'},
               {'icone': 'cartao',   'titulo': 'Nunca usado',   'sub': 'cartão que não comprou nada'},
               {'icone': 'cadeado',  'titulo': 'Margem presa',  'sub': 'impede consignado mais barato'},
               {'icone': 'alerta',   'titulo': 'Sem plástico',  'sub': 'muitas vezes nem chegou'}],
             'aceso': None},
            {'t': 142.5, 'tipo': 'cartoes', 'secao': 'Por que é ruinoso',
             'titulo': 'Quatro danos que se somam',
             'cartoes': [
               {'icone': 'relogio',  'titulo': 'Dívida eterna', 'sub': 'juros rotativos sobre o que sobra'},
               {'icone': 'cartao',   'titulo': 'Nunca usado',   'sub': 'cartão que não comprou nada'},
               {'icone': 'cadeado',  'titulo': 'Margem presa',  'sub': 'impede consignado mais barato'},
               {'icone': 'alerta',   'titulo': 'Sem plástico',  'sub': 'muitas vezes nem chegou'}],
             'aceso': 4},

            {'t': 178.5, 'tipo': 'contraste', 'secao': 'As duas situações',
             'esquerda': {'rotulo': 'Contrato quitado', 'titulo': 'Repetição', 'manda': True,
                          'linhas': ['Devolução do que foi descontado', 'a mais, com danos morais.']},
             'direita': {'rotulo': 'Contrato em aberto', 'titulo': 'Conversão',
                         'linhas': ['Vira consignado comum:', 'recálculo, compensação,',
                                    'margem liberada e danos morais.']}},

            {'t': 213.5, 'tipo': 'cartoes', 'secao': 'A fundação probatória',
             'titulo': 'Três pilares inegociáveis',
             'cartoes': [
               {'icone': 'documento', 'titulo': 'Extrato',  'sub': 'do benefício, com os descontos'},
               {'icone': 'dinheiro',  'titulo': 'Cálculo',  'sub': 'estimativa genérica não condena'},
               {'icone': 'cartao',    'titulo': 'Faturas',  'sub': 'provam que o cartão não foi usado'}],
             'aceso': 1},
            {'t': 247.5, 'tipo': 'cartoes', 'secao': 'A fundação probatória',
             'titulo': 'Três pilares inegociáveis',
             'cartoes': [
               {'icone': 'documento', 'titulo': 'Extrato',  'sub': 'do benefício, com os descontos'},
               {'icone': 'dinheiro',  'titulo': 'Cálculo',  'sub': 'estimativa genérica não condena'},
               {'icone': 'cartao',    'titulo': 'Faturas',  'sub': 'provam que o cartão não foi usado'}],
             'aceso': 3},

            {'t': 282.5, 'tipo': 'lista', 'secao': 'A linha de argumentação',
             'titulo': 'Cinco frentes, nesta ordem',
             'itens': ['Vício de consentimento e falha de informação',
                       'Ausência de uso, provada pelas faturas',
                       'Onerosidade comparada ao consignado comum',
                       'Vulnerabilidade agravada da consumidora idosa',
                       'Indícios concretos de fraude no contrato digital'],
             'aceso': None},

            {'t': 316.6, 'tipo': 'cartoes', 'secao': 'O quinto argumento, por dentro',
             'titulo': 'O que se examina no contrato digital',
             'cartoes': [
               {'icone': 'relogio',    'titulo': 'Tempo',      'sub': 'assinatura em segundos não se lê'},
               {'icone': 'engrenagem', 'titulo': 'Dispositivo','sub': 'aparelho compatível com a cliente?'},
               {'icone': 'pessoa',     'titulo': 'Biometria',  'sub': 'a selfie é dela mesma?'},
               {'icone': 'documento',  'titulo': 'Trilha',     'sub': 'ou só o PDF final?'}],
             'aceso': None},
            {'t': 353.3, 'tipo': 'cartoes', 'secao': 'O quinto argumento, por dentro',
             'titulo': 'O que se examina no contrato digital',
             'cartoes': [
               {'icone': 'relogio',    'titulo': 'Tempo',      'sub': 'assinatura em segundos não se lê'},
               {'icone': 'engrenagem', 'titulo': 'Dispositivo','sub': 'aparelho compatível com a cliente?'},
               {'icone': 'pessoa',     'titulo': 'Biometria',  'sub': 'a selfie é dela mesma?'},
               {'icone': 'documento',  'titulo': 'Trilha',     'sub': 'ou só o PDF final?'}],
             'aceso': 2},

            # 388.6s: o STJ de março de 2026 — o ICP deixou de ser pilar
            {'t': 388.6, 'tipo': 'contraste', 'secao': 'Março de 2026: o que mudou',
             'esquerda': {'rotulo': 'Não basta mais', 'titulo': 'Faltar ICP',
                          'linhas': ['O STJ decidiu que a ausência', 'de certificação, sozinha,',
                                     'não anula o contrato digital.']},
             'direita': {'rotulo': 'É isto que sustenta', 'titulo': 'Indício de fraude',
                         'manda': True,
                         'linhas': ['Assinatura relâmpago, laudo do', 'assistente — e o que o banco',
                                    'NÃO juntou: IP, geolocalização,', 'carimbo de tempo, trilha.']}},

            {'t': 423.5, 'tipo': 'frase', 'secao': 'O eixo da peça', 'corpo': 44,
             'linhas': ['O consentimento livre e informado', 'simplesmente nunca existiu.'],
             'rodape': 'É isso que a peça precisa demonstrar — não a falta de um certificado.'},

            # 460.5s: A SUSPENSÃO NACIONAL
            {'t': 460.5, 'tipo': 'frase', 'secao': 'O estado da carteira', 'corpo': 78,
             'linhas': ['O RMC está suspenso', 'no país inteiro.'],
             'rodape': 'Desde 08/04/2026, por decisão do STJ. 1º e 2º graus e Juizados.'},

            {'t': 497.5, 'tipo': 'cartoes', 'secao': 'Os dois temas repetitivos',
             'titulo': 'O que o STJ vai decidir',
             'cartoes': [
               {'icone': 'balanca', 'titulo': 'Tema 1.328', 'sub': 'há dano moral in re ipsa na invalidação?'},
               {'icone': 'documento','titulo': 'Tema 1.414', 'sub': 'parâmetros de validade e a consequência'}],
             'aceso': None,
             'rodape': 'Ambos da 2ª Seção, rel. Min. Raul Araújo. Exceção à suspensão: cumprimento de sentença.'},

            {'t': 531.5, 'tipo': 'contraste', 'secao': 'O que fazer enquanto isso',
             'esquerda': {'rotulo': 'Ajuizar', 'titulo': 'Continua valendo', 'manda': True,
                          'linhas': ['Interrompe a prescrição', 'e trava o caso esperando a tese,',
                                     'em vez de deixar envelhecer.']},
             'direita': {'rotulo': 'O que não se faz', 'titulo': 'Prometer prazo',
                         'linhas': ['Ninguém sabe quando o STJ julga.', 'Dizer data ao cliente é prometer',
                                    'o que não se controla.']}},

            # 566.0s: a decadência de MG
            {'t': 566.0, 'tipo': 'calendario', 'secao': 'O filtro de Minas Gerais',
             'titulo': 'Quatro anos da assinatura',
             'total': 4, 'corridos': 4, 'numero': 'E o caso decai',
             'rodape': 'O TJMG reconhece de ofício. Descontos sucessivos NÃO reabrem o prazo.'},

            {'t': 600.0, 'tipo': 'frase', 'secao': 'Por que isso é grave', 'corpo': 42,
             'linhas': ['Cai a anulação — e caem junto', 'a repetição e o dano moral.'],
             'rodape': 'São acessórios do pedido principal (art. 487, II, do CPC).'},

            {'t': 634.8, 'tipo': 'cartoes', 'secao': 'Além do bancário',
             'titulo': 'As outras frentes do escritório',
             'cartoes': [
               {'icone': 'balanca',   'titulo': 'Previdenciário', 'sub': 'planejamento e concessão'},
               {'icone': 'pessoa',    'titulo': 'Acidentário',    'sub': 'acidente e doença do trabalho'},
               {'icone': 'dinheiro',  'titulo': 'Superendividado','sub': 'repactuação e mínimo existencial'}],
             'aceso': None},
            {'t': 672.5, 'tipo': 'cartoes', 'secao': 'Além do bancário',
             'titulo': 'As outras frentes do escritório',
             'cartoes': [
               {'icone': 'balanca',   'titulo': 'Previdenciário', 'sub': 'planejamento e concessão'},
               {'icone': 'pessoa',    'titulo': 'Acidentário',    'sub': 'acidente e doença do trabalho'},
               {'icone': 'dinheiro',  'titulo': 'Superendividado','sub': 'repactuação e mínimo existencial'}],
             'aceso': 2},

            {'t': 707.8, 'tipo': 'cartoes', 'secao': 'Quem faz o quê',
             'titulo': 'A divisão de tarefas',
             'cartoes': [
               {'icone': 'chat',      'titulo': 'Agentes do hub', 'sub': 'o primeiro contato e o WhatsApp'},
               {'icone': 'documento', 'titulo': 'Claude',         'sub': 'peça e pesquisa, sobre os autos'},
               {'icone': 'balanca',   'titulo': 'Você',           'sub': 'a estratégia e a assinatura'}],
             'aceso': None},

            {'t': 744.8, 'tipo': 'frase', 'secao': 'O princípio que subordina tudo', 'corpo': 46,
             'linhas': ['Toda a tecnologia serve', 'à ética — nunca o contrário.'],
             'rodape': 'Art. 6º do Provimento 205/2021 e art. 9º do Código de Ética.'},

            {'t': 780.0, 'tipo': 'contraste', 'secao': 'Como se fala com o cliente',
             'esquerda': {'rotulo': 'Linguagem certa', 'titulo': 'Objetivo', 'manda': True,
                          'linhas': ['“O que buscamos é a conversão', 'e a devolução do que foi pago',
                                     'a mais.”']},
             'direita': {'rotulo': 'Linguagem proibida', 'titulo': 'Promessa',
                         'linhas': ['“A senhora vai receber.”', '“É certo que ganhamos.”',
                                    '“Garantimos o dobro.”']}},

            {'t': 814.0, 'tipo': 'frase', 'secao': 'A pergunta da réplica', 'corpo': 44,
             'linhas': ['O banco provou que houve', 'consentimento informado?'],
             'rodape': 'O ônus é dele. E é justamente isso que ele costuma não juntar.'},

            {'t': 849.8, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 50,
             'linhas': ['Expor, combater', 'e punir a falta de transparência.'],
             'rodape': 'Academia Frider · Trilha 6, aula 1'},
        ]},

    # 6.1 — versão curta (1:30), o mesmo conteúdo em síntese. Serve para
    # relembrar a tese antes de um atendimento.
    'rmc-rcc-curto': {
        'duracao': 86.5,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 6 · Aula 1 · Resumo',
             'titulo': 'RMC e RCC em um minuto',
             'sub': ['A tese principal do escritório,', 'em síntese.']},
            {'t': 9.0, 'tipo': 'contraste', 'secao': 'A troca',
             'esquerda': {'rotulo': 'Ela pediu', 'titulo': 'Empréstimo', 'manda': True,
                          'linhas': ['Parcela fixa, prazo com fim.']},
             'direita': {'rotulo': 'Recebeu', 'titulo': 'Cartão',
                         'linhas': ['Pagamento mínimo, rotativo,', 'sem fim.']}},
            {'t': 27.0, 'tipo': 'contraste', 'secao': 'As duas bases',
             'esquerda': {'rotulo': 'Quitado', 'titulo': 'Repetição',
                          'linhas': ['Devolução do que se pagou a mais.']},
             'direita': {'rotulo': 'Em aberto', 'titulo': 'Conversão', 'manda': True,
                         'linhas': ['Vira consignado comum,', 'com a margem liberada.']}},
            {'t': 50.0, 'tipo': 'frase', 'secao': 'O estado da carteira', 'corpo': 66,
             'linhas': ['Suspenso no país', 'desde 08/04/2026.'],
             'rodape': 'Temas 1.328 e 1.414 do STJ. Ajuizar interrompe a prescrição; o caso espera a tese.'},
            {'t': 66.0, 'tipo': 'calendario', 'secao': 'O filtro de Minas',
             'titulo': 'Quatro anos da assinatura',
             'total': 4, 'corridos': 4, 'numero': 'E o caso decai',
             'rodape': 'Academia Frider · Trilha 6, aula 1 — resumo'},
        ]},
    # 5.1 — Panorama da fase judicial (4:03). Primeiro roteiro escrito já com
    # os tipos gráficos: linha do tempo, fluxo, cartões e contraste.
    'panorama': {
        'duracao': 243.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 5 · Aula 1',
             'titulo': 'Panorama da fase judicial',
             'sub': ['Do protocolo da inicial ao dinheiro', 'na conta do cliente.']},

            # 34.0s: "cada ato processual gera exatamente três obrigações"
            {'t': 34.0, 'tipo': 'cartoes', 'secao': 'O princípio que atravessa tudo',
             'titulo': 'Cada ato gera três obrigações',
             'cartoes': [
               {'icone': 'balanca',   'titulo': 'Cumprir',   'sub': 'o ato processual em si'},
               {'icone': 'pasta',     'titulo': 'Registrar', 'sub': 'o andamento no hub'},
               {'icone': 'chat',      'titulo': 'Comunicar', 'sub': 'o cliente, quando for relevante'}],
             'aceso': None},

            # 54.6s: "fazer só a primeira é entregar um terço do trabalho"
            {'t': 54.6, 'tipo': 'proporcao', 'secao': 'O nível de exigência',
             'titulo': 'Peça protocolada, sem registro e sem aviso',
             'total': 3, 'marcados': 1, 'numero': 'Um terço do trabalho',
             'rodape': 'A peça impecável sozinha não fecha o ato.'},

            # 72.5s: as quatro grandes etapas
            {'t': 72.5, 'tipo': 'linha_tempo', 'secao': 'As grandes etapas',
             'titulo': 'Quatro estágios, sempre nesta ordem',
             'marcos': [{'titulo': 'Início', 'sub': 'protocolo e admissibilidade'},
                        {'titulo': 'Conhecimento', 'sub': 'defesa e provas'},
                        {'titulo': 'Sentença', 'sub': 'a decisão do juiz'},
                        {'titulo': 'Encerramento', 'sub': 'recurso, cumprimento, repasse'}],
             'aceso': None},

            # 90.7s: "descendo para o nível tático, a linha do tempo do fluxo diário"
            {'t': 90.7, 'tipo': 'fluxo', 'secao': 'O ciclo, ato por ato',
             'titulo': 'Do protocolo ao arquivamento',
             'etapas': ['Protocolo da inicial', 'Admissibilidade e emenda', 'Citação do réu', 'Contestação e réplica', 'Provas ou julgamento antecipado', 'Sentença', 'Recurso e trânsito', 'Cumprimento, alvará e repasse'], 'aceso': 1,
             'rodape': 'Conferir os documentos antes de protocolar é o primeiro ato — e o mais barato.'},
            {'t': 107.7, 'tipo': 'fluxo', 'secao': 'O ciclo, ato por ato',
             'titulo': 'Do protocolo ao arquivamento', 'etapas': ['Protocolo da inicial', 'Admissibilidade e emenda', 'Citação do réu', 'Contestação e réplica', 'Provas ou julgamento antecipado', 'Sentença', 'Recurso e trânsito', 'Cumprimento, alvará e repasse'], 'aceso': 2,
             'rodape': 'Emenda, gratuidade, custas: despacho de admissibilidade pede resposta imediata.'},
            {'t': 125.3, 'tipo': 'fluxo', 'secao': 'O ciclo, ato por ato',
             'titulo': 'Do protocolo ao arquivamento', 'etapas': ['Protocolo da inicial', 'Admissibilidade e emenda', 'Citação do réu', 'Contestação e réplica', 'Provas ou julgamento antecipado', 'Sentença', 'Recurso e trânsito', 'Cumprimento, alvará e repasse'], 'aceso': 4,
             'rodape': 'A contestação mapeia a estratégia da defesa. A réplica responde ponto a ponto.'},
            {'t': 144.8, 'tipo': 'fluxo', 'secao': 'O ciclo, ato por ato',
             'titulo': 'Do protocolo ao arquivamento', 'etapas': ['Protocolo da inicial', 'Admissibilidade e emenda', 'Citação do réu', 'Contestação e réplica', 'Provas ou julgamento antecipado', 'Sentença', 'Recurso e trânsito', 'Cumprimento, alvará e repasse'], 'aceso': 6,
             'rodape': 'Na sentença: ler o dispositivo primeiro, conferir pedido por pedido.'},
            {'t': 161.7, 'tipo': 'fluxo', 'secao': 'O ciclo, ato por ato',
             'titulo': 'Do protocolo ao arquivamento', 'etapas': ['Protocolo da inicial', 'Admissibilidade e emenda', 'Citação do réu', 'Contestação e réplica', 'Provas ou julgamento antecipado', 'Sentença', 'Recurso e trânsito', 'Cumprimento, alvará e repasse'], 'aceso': 8,
             'rodape': 'Trânsito em julgado: cumprimento, alvará e o dinheiro de volta ao cliente.'},

            # 180.0s: "a lógica muda completamente na ponta final"
            {'t': 180.0, 'tipo': 'contraste', 'secao': 'Os dois quadros',
             'esquerda': {'rotulo': 'Kanban Fase Judicial', 'titulo': 'Prazo',
                          'manda': True,
                          'linhas': ['Uma coluna por etapa.', 'O DJEN move o card sozinho,',
                                     'conforme as publicações.']},
             'direita': {'rotulo': 'Execução & Repasse', 'titulo': 'Dinheiro',
                         'linhas': ['Outra lógica na ponta final:', 'liberar valores e encerrar',
                                    'o caso de verdade.']}},

            {'t': 197.5, 'tipo': 'tela', 'secao': 'Onde isso vive',
             'titulo': 'O quadro se move com o DJEN', 'print': 'kanban-fase-judicial'},

            # 215.9s: Claude × agentes
            {'t': 215.9, 'tipo': 'cartoes', 'secao': 'Cada ferramenta no seu lugar',
             'titulo': 'Quem faz o quê',
             'cartoes': [
               {'icone': 'documento',  'titulo': 'Claude',  'sub': 'peça jurídica e pesquisa'},
               {'icone': 'chat',       'titulo': 'Agentes do hub', 'sub': 'todo o WhatsApp com o cliente'}],
             'aceso': None,
             'rodape': 'São esteiras separadas. O Claude não fala com cliente em hipótese nenhuma.'},

            # 235.9s: a pergunta final
            {'t': 235.9, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 44,
             'linhas': ['Cumpri, registrei', 'e comuniquei?'],
             'rodape': 'Academia Frider · Trilha 5, aula 1'},
        ]},
    # 2.2 — O foco do Início (2:34). Sete blocos, medidos no vtt de 59 deixas.
    'inicio': {
        'duracao': 154.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura',
             'etiqueta': 'Trilha 2 · Aula 2',
             'titulo': 'O Foco do Início',
             'sub': ['A mesa de trabalho diária: o que abrir primeiro,',
                     'e o que nunca deixar para depois.']},

            # 10.5s: "o objetivo desse painel é dar clareza sobre as responsabilidades do dia"
            {'t': 10.5, 'tipo': 'frase', 'secao': 'Para que serve',
             'linhas': ['“O que está esperando', 'por mim agora?”'],
             'rodape': 'A tela inteira existe para responder a esta pergunta.'},

            # 41.0s: "na prática, a interface apresenta as conversas, tarefas, publicações"
            {'t': 41.0, 'tipo': 'tela', 'secao': 'A mesa de trabalho',
             'titulo': 'Início', 'print': 'inicio-mesa'},

            # 63.8s: "o filtro dessa tela é estritamente pessoal"
            {'t': 63.8, 'tipo': 'contraste', 'secao': 'O filtro é pessoal',
             'esquerda': {'rotulo': 'O que o Início mostra', 'titulo': 'Você',
                          'manda': True,
                          'linhas': ['Só as suas pendências.', 'Lista curta de manhã não quer dizer',
                                     'escritório parado — quer dizer que há', 'menos coisa designada a você.']},
             'direita': {'rotulo': 'O que ele não mostra', 'titulo': 'O escritório',
                         'linhas': ['A fila das outras equipes.', 'O volume delas pode estar alto;',
                                    'esta visão protege a sua', 'concentração.']}},

            # 92.8s: "uma rotina de abertura do dia, dividida em quatro passos"
            {'t': 92.8, 'tipo': 'fluxo', 'secao': 'Rotina de abertura',
             'titulo': 'Todo dia, nesta ordem',
             'etapas': ['Limpar as publicações', 'Tratar as conversas pendentes', 'Conferir a agenda da semana', 'Mover os cards do Kanban'], 'aceso': 1},
            {'t': 100.5, 'tipo': 'fluxo', 'secao': 'Rotina de abertura',
             'titulo': 'Todo dia, nesta ordem',
             'etapas': ['Limpar as publicações', 'Tratar as conversas pendentes', 'Conferir a agenda da semana', 'Mover os cards do Kanban'], 'aceso': 2},
            {'t': 104.0, 'tipo': 'fluxo', 'secao': 'Rotina de abertura',
             'titulo': 'Todo dia, nesta ordem',
             'etapas': ['Limpar as publicações', 'Tratar as conversas pendentes', 'Conferir a agenda da semana', 'Mover os cards do Kanban'], 'aceso': 3},
            {'t': 106.0, 'tipo': 'fluxo', 'secao': 'Rotina de abertura',
             'titulo': 'Todo dia, nesta ordem',
             'etapas': ['Limpar as publicações', 'Tratar as conversas pendentes', 'Conferir a agenda da semana', 'Mover os cards do Kanban'], 'aceso': 4},

            # 110.5s: "a justificativa para essa ordem é estritamente técnica"
            {'t': 110.5, 'tipo': 'contraste', 'secao': 'Por que nesta ordem',
             'esquerda': {'rotulo': 'Publicação do tribunal', 'titulo': 'Preclui',
                          'manda': True,
                          'linhas': ['Gera prazo. Prazo perdido', 'não volta.', '',
                                     'Por isso vem primeiro.']},
             'direita': {'rotulo': 'Conversa de cliente', 'titulo': 'Não preclui',
                         'linhas': ['Exige retorno rápido,', 'mas não fecha porta nenhuma.', '',
                                    'Vem logo depois.']}},

            # 126.0s: "uma regra fundamental sobre o sino de notificações e a agenda"
            {'t': 126.0, 'tipo': 'contraste', 'secao': 'Sino e agenda',
             'esquerda': {'rotulo': 'O sino', 'titulo': 'Lembra',
                          'linhas': ['Alerta pontual.', 'Ajuda, mas não é controle.']},
             'direita': {'rotulo': 'A agenda', 'titulo': 'Controla',
                         'manda': True,
                         'linhas': ['O prazo se confere aqui.', 'A notificação nunca substitui',
                                    'o hábito de olhar a pauta', 'da semana inteira.']}},

            # 144.0s: fecho — "o prazo processual se confere na agenda"
            {'t': 144.0, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 58,
             'linhas': ['O prazo se confere na agenda.'],
             'rodape': 'Academia Frider · Trilha 2, aula 2'},
        ],
    },
    # 1.1 — Comece por aqui: como usar esta Academia (2:53)
    'como-usar': {
        'duracao': 173.2,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 1',
             'titulo': 'Como usar esta Academia',
             'sub': ['O treinamento oficial do escritório,', 'dentro do próprio hub.']},
            {'t': 14.4, 'tipo': 'contraste', 'secao': 'Vídeo e manual',
             'esquerda': {'rotulo': 'O vídeo', 'titulo': 'Explica',
                          'linhas': ['Dá o panorama e o porquê.', 'Assiste-se uma vez.']},
             'direita': {'rotulo': 'O manual escrito', 'titulo': 'Procedimenta', 'manda': True,
                         'linhas': ['É mais completo que a gravação.', 'É o procedimento inteiro,',
                                    'para consultar no meio do caso.']}},
            {'t': 45.0, 'tipo': 'lista', 'secao': 'O caminho', 'titulo': 'Oito trilhas, nesta ordem',
             'itens': ['Comece por aqui', 'O hub por dentro', 'Claude: peças e pesquisa', 'Prazos e controladoria', 'A fase judicial ponta a ponta', 'As teses do escritório', 'Cliente', 'Ética, sigilo e segurança'], 'aceso': None},
            {'t': 90.6, 'tipo': 'lista', 'secao': 'Os cinco primeiros dias',
             'titulo': 'Um dia, um assunto',
             'itens': ['Dia 1 — a cultura', 'Dia 2 — o hub', 'Dia 3 — o Claude',
                       'Dia 4 — prazos', 'Dia 5 — a fase judicial'], 'aceso': None,
             'rodape': 'Exceção: quem já vai falar com cliente no dia 1 adianta a trilha de Cliente.'},
            {'t': 122.3, 'tipo': 'cartoes', 'secao': 'Como se faz cada aula',
             'titulo': 'Três passos, sempre',
             'cartoes': [
               {'icone': 'chat',      'titulo': 'Assistir',  'sub': 'o vídeo dá o panorama'},
               {'icone': 'documento', 'titulo': 'Ler',       'sub': 'o manual é o procedimento'},
               {'icone': 'balanca',   'titulo': 'Marcar',    'sub': '“você consegue fazer sozinho?”'}],
             'aceso': None},
            {'t': 136.6, 'tipo': 'contraste', 'secao': 'A quem recorrer',
             'esquerda': {'rotulo': 'Ajuda', 'titulo': 'Onde clico',
                          'linhas': ['A dúvida de operação do sistema.']},
             'direita': {'rotulo': 'Academia', 'titulo': 'Como se faz', 'manda': True,
                         'linhas': ['E por quê. A metodologia.', '',
                                    'Tese e estratégia de caso:', 'pergunte ao advogado responsável.']}},
            {'t': 169.3, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 60,
             'linhas': ['Você consegue fazer sozinho?'],
             'rodape': 'Academia Frider · Trilha 1, aula 1'},
        ]},

    # 1.2 — Quem somos (3:03)
    'quem-somos': {
        'duracao': 182.8,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 2',
             'titulo': 'Quem somos',
             'sub': ['Missão, visão e valores —', 'e como isso aparece no dia a dia.']},
            {'t': 9.0, 'tipo': 'frase', 'secao': 'A missão', 'corpo': 62,
             'linhas': ['Somos a voz e a força', 'de quem o Estado esquece.'],
             'rodape': 'Com foco absoluto em idosos e aposentados.'},
            {'t': 30.8, 'tipo': 'frase', 'secao': 'O que chega à nossa mesa', 'corpo': 44,
             'linhas': ['Uma aposentada de 74 anos,', 'um salário mínimo, cinco anos de desconto',
                        'por um cartão que ela nunca contratou.'],
             'rodape': 'É para mudar essa realidade que o escritório existe.'},
            {'t': 48.0, 'tipo': 'lista', 'secao': 'A visão', 'titulo': 'Para onde vamos',
             'itens': ['Faturamento previsível', 'Atuação nacional', 'Equipe enxuta',
                       'Caminho até a sociedade'], 'aceso': None},
            {'t': 71.0, 'tipo': 'lista', 'secao': 'Os cinco prioritários',
             'titulo': 'De 15 valores, estes cinco',
             'itens': ['Eficiência — a melhor e mais rápida solução',
                       'Transparência — a verdade ao cliente, sem maquiagem',
                       'Vontade — entregar melhor que ontem',
                       'Segurança — o cliente precisa sentir, não só nós sabermos',
                       'Felicidade — um bom lugar para trabalhar'], 'aceso': None},
            {'t': 125.5, 'tipo': 'lista', 'secao': 'O que não toleramos',
             'titulo': 'Como NÃO se vive um valor',
             'itens': ['Trabalhar desmotivado', 'Agir na sorte em vez de estudar o processo',
                       'Omitir informação do cliente'], 'aceso': None},
            {'t': 139.5, 'tipo': 'cartoes', 'secao': 'Vantagens competitivas',
             'titulo': 'O que nos separa',
             'cartoes': [
               {'icone': 'pessoa',     'titulo': 'Padrão',     'sub': 'com cuidado individualizado'},
               {'icone': 'documento',  'titulo': 'Formação',   'sub': 'desenvolvimento contínuo'},
               {'icone': 'balanca',    'titulo': 'Postura',    'sub': 'humildade e ambição juntas'},
               {'icone': 'engrenagem', 'titulo': 'Tecnologia', 'sub': 'a favor, com limite claro'}],
             'aceso': None},
            {'t': 171.0, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 66,
             'linhas': ['Justiça. Crescimento. Excelência.'],
             'rodape': 'Vamos crescer juntos.'},
        ]},

    # 2.1 — A lógica do hub (3:34)
    'visao-geral': {
        'duracao': 214.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 2 · Aula 1',
             'titulo': 'A lógica do hub',
             'sub': ['Uma conversa vira lead, vira cliente,', 'vira processo, vira dinheiro.']},
            {'t': 12.0, 'tipo': 'tela', 'secao': 'O sistema do escritório',
             'titulo': 'Tudo em um lugar só', 'print': 'inicio-mesa'},
            {'t': 36.0, 'tipo': 'fluxo', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem',
             'etapas': ['Conversa no WhatsApp', 'Lead no funil comercial', 'Cliente: contrato assinado', 'Processo com ficha', 'Kanban movido pelo DJEN', 'Agenda e prazos', 'Execução e repasse'], 'aceso': 1},
            {'t': 52.0, 'tipo': 'tela', 'secao': 'A linha da vida · passo 2',
             'titulo': 'O lead entra no Funil', 'print': 'funil-comercial'},
            {'t': 60.0, 'tipo': 'fluxo', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem',
             'etapas': ['Conversa no WhatsApp', 'Lead no funil comercial', 'Cliente: contrato assinado', 'Processo com ficha', 'Kanban movido pelo DJEN', 'Agenda e prazos', 'Execução e repasse'], 'aceso': 3},
            {'t': 82.0, 'tipo': 'tela', 'secao': 'A linha da vida · passo 4',
             'titulo': 'O processo ganha ficha', 'print': 'ficha-processo'},
            {'t': 88.0, 'tipo': 'tela', 'secao': 'A linha da vida · passo 5',
             'titulo': 'O DJEN move o card', 'print': 'kanban-fase-judicial'},
            {'t': 96.0, 'tipo': 'fluxo', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem',
             'etapas': ['Conversa no WhatsApp', 'Lead no funil comercial', 'Cliente: contrato assinado', 'Processo com ficha', 'Kanban movido pelo DJEN', 'Agenda e prazos', 'Execução e repasse'], 'aceso': 6},
            {'t': 104.0, 'tipo': 'fluxo', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem',
             'etapas': ['Conversa no WhatsApp', 'Lead no funil comercial', 'Cliente: contrato assinado', 'Processo com ficha', 'Kanban movido pelo DJEN', 'Agenda e prazos', 'Execução e repasse'], 'aceso': 7},
            {'t': 110.0, 'tipo': 'contraste', 'secao': 'Cada um no seu lugar',
             'esquerda': {'rotulo': 'Agentes de IA do hub', 'titulo': 'Atendem',
                          'manda': True,
                          'linhas': ['Conduzem o WhatsApp com o cliente.']},
             'direita': {'rotulo': 'Claude', 'titulo': 'Redige',
                         'linhas': ['Peça e pesquisa, sobre os autos.', 'Sem contato externo nenhum.']}},
            {'t': 135.0, 'tipo': 'lista', 'secao': 'A barra lateral',
             'titulo': 'Os blocos do sistema',
             'itens': ['Início — a mesa de trabalho', 'Conquistas', 'Comercial — contatos e negócios',
                       'Jurídico — processos e calculadoras', 'Administrativo — financeiro e RH',
                       'Rodapé — ajuda, seu espaço, configurações'], 'aceso': None},
            {'t': 168.0, 'tipo': 'lista', 'secao': 'Conforto de uso',
             'titulo': 'Três coisas que facilitam o dia',
             'itens': ['Barra simples, só o essencial', 'Modo escuro',
                       'Instalação no celular como aplicativo'], 'aceso': None},
            {'t': 193.0, 'tipo': 'frase', 'secao': 'A regra', 'corpo': 62,
             'linhas': ['O que não está no hub', 'não aconteceu.'],
             'rodape': 'Academia Frider · Trilha 2, aula 1'},
        ]},

    # 2.3 — Conversas (3:25)
    'conversas': {
        'duracao': 205.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 2 · Aula 3',
             'titulo': 'Conversas',
             'sub': ['WhatsApp, inteligência artificial', 'e o momento em que você assume.']},
            {'t': 10.0, 'tipo': 'tela', 'secao': 'O módulo Conversas',
             'titulo': 'Onde o WhatsApp vira trabalho', 'print': 'conversas-chat'},
            {'t': 22.0, 'tipo': 'contraste', 'secao': 'Quem faz o quê',
             'esquerda': {'rotulo': 'Agentes de IA do hub', 'titulo': 'Atendem', 'manda': True,
                          'linhas': ['Recepção e triagem no WhatsApp.']},
             'direita': {'rotulo': 'Claude', 'titulo': 'Não atende',
                         'linhas': ['Em nenhuma hipótese.', 'São esteiras separadas.']}},
            {'t': 40.0, 'tipo': 'frase', 'secao': 'A pausa da IA', 'corpo': 46,
             'linhas': ['Ao responder à mão, a IA pausa —', 'de propósito, para não atropelar você.'],
             'rodape': '“O robô parou de responder” quase sempre é só falta de reativar.'},
            {'t': 66.0, 'tipo': 'contraste', 'secao': 'A janela de 24 horas',
             'esquerda': {'rotulo': 'Dentro de 24h', 'titulo': 'Texto livre', 'manda': True,
                          'linhas': ['Escreva normalmente.']},
             'direita': {'rotulo': 'Fora de 24h', 'titulo': 'Só modelo aprovado',
                         'linhas': ['Texto livre NÃO é entregue —', 'e você não é avisado.',
                                    'O modelo reabre o contato.']}},
            {'t': 111.0, 'tipo': 'cartoes', 'secao': 'Número oficial', 'titulo': 'Por que nunca o pessoal',
             'cartoes': [
               {'icone': 'pasta',   'titulo': 'Sem histórico', 'sub': 'a conversa não entra no hub'},
               {'icone': 'cadeado', 'titulo': 'Sem controle',  'sub': 'o escritório não vê o atendimento'},
               {'icone': 'pessoa',  'titulo': 'Sem cliente',   'sub': 'se a pessoa sai, ele vai junto'}],
             'aceso': None},
            {'t': 133.0, 'tipo': 'frase', 'secao': 'Alerta', 'corpo': 50,
             'linhas': ['Disparo em massa é proibido.'],
             'rodape': 'Já custou um número banido ao escritório.'},
            {'t': 142.0, 'tipo': 'lista', 'secao': 'Recursos do chat',
             'titulo': 'O que o chat resolve por você',
             'itens': ['Atalhos de resposta pronta', 'Enviar contato e documento',
                       'A IA lê e transcreve áudio e arquivo'], 'aceso': None},
            {'t': 168.0, 'tipo': 'frase', 'secao': 'Cadastro', 'corpo': 46,
             'linhas': ['Vincule pelo contato, nunca pelo nome.'],
             'rodape': 'Homônimo mistura processo de gente diferente.'},
            {'t': 188.5, 'tipo': 'frase', 'secao': 'A métrica', 'corpo': 58,
             'linhas': ['Responder no mesmo dia.'],
             'rodape': 'Sem resposta pronta? Avise que está apurando — mas responda.'},
        ]},

    # 3.1 — O que o Claude é (3:27)
    'o-que-e': {
        'duracao': 207.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 3 · Aula 1',
             'titulo': 'O que o Claude é aqui',
             'sub': ['E, principalmente,', 'o que ele não é.']},
            {'t': 16.5, 'tipo': 'lista', 'secao': 'O que ele faz', 'titulo': 'O Claude',
             'itens': ['Monta peça sobre as nossas bases', 'Pesquisa jurisprudência',
                       'Lê documento e extrai dado', 'Revisa peça pronta'], 'aceso': None},
            {'t': 39.0, 'tipo': 'cartoes', 'secao': 'O que ele NÃO é', 'titulo': 'Quatro limites, sempre',
             'cartoes': [
               {'icone': 'balanca',    'titulo': 'Não é advogado', 'sub': 'a OAB na peça é sua'},
               {'icone': 'documento',  'titulo': 'Não é fonte',    'sub': 'jurisprudência se confere no tribunal'},
               {'icone': 'pasta',      'titulo': 'Não lê os autos','sub': 'só enxerga o que subiu'},
               {'icone': 'engrenagem', 'titulo': 'Não decide',     'sub': 'tese, pedido e valor são humanos'}],
             'aceso': None},
            {'t': 78.5, 'tipo': 'frase', 'secao': 'A regra de ouro', 'corpo': 58,
             'linhas': ['Se existe skill para a tarefa,', 'a skill manda.'],
             'rodape': 'Improvisar é proibido.'},
            {'t': 100.0, 'tipo': 'frase', 'secao': 'Por quê', 'corpo': 44,
             'linhas': ['Cada regra foi escrita', 'depois de um erro medido em peça real.'],
             'rodape': 'As instruções blindam hoje contra as falhas de ontem.'},
            {'t': 112.0, 'tipo': 'lista', 'secao': 'As quatro proibições',
             'titulo': 'Não se faz, nunca',
             'itens': ['Escrever script próprio para o que a skill já resolve',
                       'Pular passo achando o caso simples',
                       'Inventar regra nova de forma ou estrutura',
                       'Trocar de ferramenta no meio sem reler a skill'], 'aceso': None},
            {'t': 152.0, 'tipo': 'lista', 'secao': 'Antes de entregar',
             'titulo': 'A conferência é humana',
             'itens': ['Ler a skill inteira antes de tocar no arquivo',
                       'Comparar com a base daquela família de peça',
                       'Rodar a revisão, quando existir'], 'aceso': None},
            {'t': 176.0, 'tipo': 'frase', 'secao': 'O ponto crítico', 'corpo': 44,
             'linhas': ['“Aplicado com sucesso”', 'não é verificação.'],
             'rodape': 'A mensagem diz que rodou — não que ficou certo.'},
            {'t': 196.0, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 48,
             'linhas': ['Uma pergunta custa uma linha.', 'Um palpite custa uma peça refeita.'],
             'rodape': 'Academia Frider · Trilha 3, aula 1'},
        ]},

    # 4.1 — Como o prazo chega até você (2:49)
    'como-chega': {
        'duracao': 169.2,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 4 · Aula 1',
             'titulo': 'Como o prazo chega',
             'sub': ['O tema em que erro custa mais caro.']},
            {'t': 15.7, 'tipo': 'cartoes', 'secao': 'De onde vem', 'titulo': 'Quatro fontes de intimação',
             'cartoes': [
               {'icone': 'documento',  'titulo': 'DJEN',    'sub': 'a principal, lida todo dia pelo hub'},
               {'icone': 'banco',      'titulo': 'Portal',  'sub': 'do tribunal, com regra própria'},
               {'icone': 'engrenagem', 'titulo': 'Projudi', 'sub': 'onde nasce o ato cego'},
               {'icone': 'pessoa',     'titulo': 'Oficial', 'sub': 'ou carta, no papel'}],
             'aceso': None},
            {'t': 43.0, 'tipo': 'proporcao', 'secao': 'A armadilha do ponteiro',
             'titulo': 'Quantas publicações chegam vazias',
             'total': 20, 'marcados': 5, 'numero': 'Uma em cada quatro',
             'rodape': 'Ato cego: houve algo ali e ninguém sabe o quê. Abra os autos hoje, não amanhã.'},
            {'t': 64.4, 'tipo': 'calendario', 'secao': 'A armadilha do portal',
             'titulo': 'A intimação que ninguém abriu',
             'total': 10, 'corridos': 7, 'numero': '10 dias corridos',
             'rodape': 'A contagem avança sem você abrir. Quem acumula descobre o prazo já correndo.'},
            {'t': 92.0, 'tipo': 'contraste', 'secao': 'Máquina e pessoa',
             'esquerda': {'rotulo': 'O classificador', 'titulo': 'Organiza',
                          'linhas': ['Lê o teor, identifica o ato,', 'calcula o prazo, cria a agenda',
                                     'e move o card.']},
             'direita': {'rotulo': 'Você', 'titulo': 'Decide', 'manda': True,
                         'linhas': ['Abre os autos.', 'Conhece a estratégia.',
                                    'Resolve de quem é o prazo.']}},
            {'t': 139.9, 'tipo': 'tela', 'secao': 'A rotina',
             'titulo': 'Todo dia, a semana inteira', 'print': 'agenda-semana'},
            {'t': 155.6, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 54,
             'linhas': ['O prazo se confere na agenda.'],
             'rodape': 'Academia Frider · Trilha 4, aula 1'},
        ]},
}
