"""
Roteiro visual de cada aula: em que segundo entra cada tela.

Os tempos vêm da transcrição (o .vtt da aula), não de chute — cada corte cai
numa pausa da narração, entre um assunto e o seguinte. Para levantá-los:

    curl -s .../academia/<slug>.vtt | grep ' --> '

Regra ao escrever: a tela acompanha o que está sendo dito. Slide que fica
parado enquanto a narração já mudou de assunto é pior que slide nenhum, porque
compete com quem escuta.
"""

ROTEIROS = {
    # 2.2 — O foco do Início (2:34). Sete blocos, medidos no vtt de 59 deixas.
    'inicio': {
        'duracao': 154.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura',
             'etiqueta': 'Trilha 2 · Aula 2',
             'titulo': 'O Foco do Início',
             'sub': ['A mesa de trabalho diária: o que abrir primeiro,',
                     'e o que nunca deixar para depois.']},

            # 10.5s: "o objetivo desse painel é dar clareza sobre as responsabilidades do dia"
            {'t': 10.5, 'tipo': 'frase', 'secao': 'Para que serve',
             'linhas': ['“O que está esperando', 'por mim agora?”'],
             'rodape': 'A tela inteira existe para responder a esta pergunta.'},

            # 41.0s: "na prática, a interface apresenta as conversas, tarefas, publicações"
            {'t': 41.0, 'tipo': 'tela', 'secao': 'A mesa de trabalho',
             'titulo': 'Início', 'print': 'inicio-mesa'},

            # 63.8s: "o filtro dessa tela é estritamente pessoal"
            {'t': 63.8, 'tipo': 'contraste', 'secao': 'O filtro é pessoal',
             'esquerda': {'rotulo': 'O que o Início mostra', 'titulo': 'Você',
                          'manda': True,
                          'linhas': ['Só as suas pendências.', 'Lista curta de manhã não quer dizer',
                                     'escritório parado — quer dizer que há', 'menos coisa designada a você.']},
             'direita': {'rotulo': 'O que ele não mostra', 'titulo': 'O escritório',
                         'linhas': ['A fila das outras equipes.', 'O volume delas pode estar alto;',
                                    'esta visão protege a sua', 'concentração.']}},

            # 92.8s: "uma rotina de abertura do dia, dividida em quatro passos"
            {'t': 92.8, 'tipo': 'passos', 'secao': 'Rotina de abertura', 'ate': 1,
             'titulo': 'Todo dia, nesta ordem',
             'passos': ['Limpar as publicações', 'Tratar as conversas pendentes',
                        'Conferir a agenda da semana', 'Mover os cards do Kanban']},
            {'t': 100.5, 'tipo': 'passos', 'secao': 'Rotina de abertura', 'ate': 2,
             'titulo': 'Todo dia, nesta ordem',
             'passos': ['Limpar as publicações', 'Tratar as conversas pendentes',
                        'Conferir a agenda da semana', 'Mover os cards do Kanban']},
            {'t': 104.0, 'tipo': 'passos', 'secao': 'Rotina de abertura', 'ate': 3,
             'titulo': 'Todo dia, nesta ordem',
             'passos': ['Limpar as publicações', 'Tratar as conversas pendentes',
                        'Conferir a agenda da semana', 'Mover os cards do Kanban']},
            {'t': 106.0, 'tipo': 'passos', 'secao': 'Rotina de abertura', 'ate': 4,
             'titulo': 'Todo dia, nesta ordem',
             'passos': ['Limpar as publicações', 'Tratar as conversas pendentes',
                        'Conferir a agenda da semana', 'Mover os cards do Kanban']},

            # 110.5s: "a justificativa para essa ordem é estritamente técnica"
            {'t': 110.5, 'tipo': 'contraste', 'secao': 'Por que nesta ordem',
             'esquerda': {'rotulo': 'Publicação do tribunal', 'titulo': 'Preclui',
                          'manda': True,
                          'linhas': ['Gera prazo. Prazo perdido', 'não volta.', '',
                                     'Por isso vem primeiro.']},
             'direita': {'rotulo': 'Conversa de cliente', 'titulo': 'Não preclui',
                         'linhas': ['Exige retorno rápido,', 'mas não fecha porta nenhuma.', '',
                                    'Vem logo depois.']}},

            # 126.0s: "uma regra fundamental sobre o sino de notificações e a agenda"
            {'t': 126.0, 'tipo': 'contraste', 'secao': 'Sino e agenda',
             'esquerda': {'rotulo': 'O sino', 'titulo': 'Lembra',
                          'linhas': ['Alerta pontual.', 'Ajuda, mas não é controle.']},
             'direita': {'rotulo': 'A agenda', 'titulo': 'Controla',
                         'manda': True,
                         'linhas': ['O prazo se confere aqui.', 'A notificação nunca substitui',
                                    'o hábito de olhar a pauta', 'da semana inteira.']}},

            # 144.0s: fecho — "o prazo processual se confere na agenda"
            {'t': 144.0, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 58,
             'linhas': ['O prazo se confere na agenda.'],
             'rodape': 'Academia Frider · Trilha 2, aula 2'},
        ],
    },
    # 1.1 — Comece por aqui: como usar esta Academia (2:53)
    'como-usar': {
        'duracao': 173.2,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 1',
             'titulo': 'Como usar esta Academia',
             'sub': ['O treinamento oficial do escritório,', 'dentro do próprio hub.']},
            {'t': 14.4, 'tipo': 'contraste', 'secao': 'Vídeo e manual',
             'esquerda': {'rotulo': 'O vídeo', 'titulo': 'Explica',
                          'linhas': ['Dá o panorama e o porquê.', 'Assiste-se uma vez.']},
             'direita': {'rotulo': 'O manual escrito', 'titulo': 'Procedimenta', 'manda': True,
                         'linhas': ['É mais completo que a gravação.', 'É o procedimento inteiro,',
                                    'para consultar no meio do caso.']}},
            {'t': 45.0, 'tipo': 'lista', 'secao': 'O caminho', 'titulo': 'Oito trilhas, nesta ordem',
             'itens': ['Comece por aqui', 'O hub por dentro', 'Claude: peças e pesquisa', 'Prazos e controladoria', 'A fase judicial ponta a ponta', 'As teses do escritório', 'Cliente', 'Ética, sigilo e segurança'], 'aceso': None},
            {'t': 90.6, 'tipo': 'lista', 'secao': 'Os cinco primeiros dias',
             'titulo': 'Um dia, um assunto',
             'itens': ['Dia 1 — a cultura', 'Dia 2 — o hub', 'Dia 3 — o Claude',
                       'Dia 4 — prazos', 'Dia 5 — a fase judicial'], 'aceso': None,
             'rodape': 'Exceção: quem já vai falar com cliente no dia 1 adianta a trilha de Cliente.'},
            {'t': 122.3, 'tipo': 'lista', 'secao': 'Como se faz cada aula',
             'titulo': 'Três passos, sempre',
             'itens': ['Assistir ao vídeo', 'Ler o manual até o fim',
                       'Marcar a lista do “você consegue fazer sozinho?”'], 'aceso': None},
            {'t': 136.6, 'tipo': 'contraste', 'secao': 'A quem recorrer',
             'esquerda': {'rotulo': 'Ajuda', 'titulo': 'Onde clico',
                          'linhas': ['A dúvida de operação do sistema.']},
             'direita': {'rotulo': 'Academia', 'titulo': 'Como se faz', 'manda': True,
                         'linhas': ['E por quê. A metodologia.', '',
                                    'Tese e estratégia de caso:', 'pergunte ao advogado responsável.']}},
            {'t': 169.3, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 60,
             'linhas': ['Você consegue fazer sozinho?'],
             'rodape': 'Academia Frider · Trilha 1, aula 1'},
        ]},

    # 1.2 — Quem somos (3:03)
    'quem-somos': {
        'duracao': 182.8,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 1 · Aula 2',
             'titulo': 'Quem somos',
             'sub': ['Missão, visão e valores —', 'e como isso aparece no dia a dia.']},
            {'t': 9.0, 'tipo': 'frase', 'secao': 'A missão', 'corpo': 62,
             'linhas': ['Somos a voz e a força', 'de quem o Estado esquece.'],
             'rodape': 'Com foco absoluto em idosos e aposentados.'},
            {'t': 30.8, 'tipo': 'frase', 'secao': 'O que chega à nossa mesa', 'corpo': 44,
             'linhas': ['Uma aposentada de 74 anos,', 'um salário mínimo, cinco anos de desconto',
                        'por um cartão que ela nunca contratou.'],
             'rodape': 'É para mudar essa realidade que o escritório existe.'},
            {'t': 48.0, 'tipo': 'lista', 'secao': 'A visão', 'titulo': 'Para onde vamos',
             'itens': ['Faturamento previsível', 'Atuação nacional', 'Equipe enxuta',
                       'Caminho até a sociedade'], 'aceso': None},
            {'t': 71.0, 'tipo': 'lista', 'secao': 'Os cinco prioritários',
             'titulo': 'De 15 valores, estes cinco',
             'itens': ['Eficiência — a melhor e mais rápida solução',
                       'Transparência — a verdade ao cliente, sem maquiagem',
                       'Vontade — entregar melhor que ontem',
                       'Segurança — o cliente precisa sentir, não só nós sabermos',
                       'Felicidade — um bom lugar para trabalhar'], 'aceso': None},
            {'t': 125.5, 'tipo': 'lista', 'secao': 'O que não toleramos',
             'titulo': 'Como NÃO se vive um valor',
             'itens': ['Trabalhar desmotivado', 'Agir na sorte em vez de estudar o processo',
                       'Omitir informação do cliente'], 'aceso': None},
            {'t': 139.5, 'tipo': 'lista', 'secao': 'Vantagens competitivas',
             'titulo': 'O que nos separa',
             'itens': ['Atendimento padronizado, cuidado individualizado',
                       'Desenvolvimento contínuo da equipe',
                       'Humildade e ambição na mesma postura',
                       'Tecnologia a favor, com limite claro'], 'aceso': None},
            {'t': 171.0, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 66,
             'linhas': ['Justiça. Crescimento. Excelência.'],
             'rodape': 'Vamos crescer juntos.'},
        ]},

    # 2.1 — A lógica do hub (3:34)
    'visao-geral': {
        'duracao': 214.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 2 · Aula 1',
             'titulo': 'A lógica do hub',
             'sub': ['Uma conversa vira lead, vira cliente,', 'vira processo, vira dinheiro.']},
            {'t': 12.0, 'tipo': 'tela', 'secao': 'O sistema do escritório',
             'titulo': 'Tudo em um lugar só', 'print': 'inicio-mesa'},
            {'t': 36.0, 'tipo': 'lista', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem', 'itens': ['Conversa — chega no WhatsApp', 'Lead — entra no funil comercial', 'Cliente — contrato assinado, pasta criada', 'Processo — ficha com partes e documentos', 'Kanban jurídico — o DJEN move o card', 'Agenda e prazos — a semana inteira', 'Execução e repasse — o dinheiro volta'], 'aceso': 1},
            {'t': 52.0, 'tipo': 'tela', 'secao': 'A linha da vida · passo 2',
             'titulo': 'O lead entra no Funil', 'print': 'funil-comercial'},
            {'t': 60.0, 'tipo': 'lista', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem', 'itens': ['Conversa — chega no WhatsApp', 'Lead — entra no funil comercial', 'Cliente — contrato assinado, pasta criada', 'Processo — ficha com partes e documentos', 'Kanban jurídico — o DJEN move o card', 'Agenda e prazos — a semana inteira', 'Execução e repasse — o dinheiro volta'], 'aceso': 3},
            {'t': 82.0, 'tipo': 'tela', 'secao': 'A linha da vida · passo 4',
             'titulo': 'O processo ganha ficha', 'print': 'ficha-processo'},
            {'t': 88.0, 'tipo': 'tela', 'secao': 'A linha da vida · passo 5',
             'titulo': 'O DJEN move o card', 'print': 'kanban-fase-judicial'},
            {'t': 96.0, 'tipo': 'lista', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem', 'itens': ['Conversa — chega no WhatsApp', 'Lead — entra no funil comercial', 'Cliente — contrato assinado, pasta criada', 'Processo — ficha com partes e documentos', 'Kanban jurídico — o DJEN move o card', 'Agenda e prazos — a semana inteira', 'Execução e repasse — o dinheiro volta'], 'aceso': 6},
            {'t': 104.0, 'tipo': 'lista', 'secao': 'A linha da vida de um caso',
             'titulo': 'Sete passos, sempre nesta ordem', 'itens': ['Conversa — chega no WhatsApp', 'Lead — entra no funil comercial', 'Cliente — contrato assinado, pasta criada', 'Processo — ficha com partes e documentos', 'Kanban jurídico — o DJEN move o card', 'Agenda e prazos — a semana inteira', 'Execução e repasse — o dinheiro volta'], 'aceso': 7},
            {'t': 110.0, 'tipo': 'contraste', 'secao': 'Cada um no seu lugar',
             'esquerda': {'rotulo': 'Agentes de IA do hub', 'titulo': 'Atendem',
                          'manda': True,
                          'linhas': ['Conduzem o WhatsApp com o cliente.']},
             'direita': {'rotulo': 'Claude', 'titulo': 'Redige',
                         'linhas': ['Peça e pesquisa, sobre os autos.', 'Sem contato externo nenhum.']}},
            {'t': 135.0, 'tipo': 'lista', 'secao': 'A barra lateral',
             'titulo': 'Os blocos do sistema',
             'itens': ['Início — a mesa de trabalho', 'Conquistas', 'Comercial — contatos e negócios',
                       'Jurídico — processos e calculadoras', 'Administrativo — financeiro e RH',
                       'Rodapé — ajuda, seu espaço, configurações'], 'aceso': None},
            {'t': 168.0, 'tipo': 'lista', 'secao': 'Conforto de uso',
             'titulo': 'Três coisas que facilitam o dia',
             'itens': ['Barra simples, só o essencial', 'Modo escuro',
                       'Instalação no celular como aplicativo'], 'aceso': None},
            {'t': 193.0, 'tipo': 'frase', 'secao': 'A regra', 'corpo': 62,
             'linhas': ['O que não está no hub', 'não aconteceu.'],
             'rodape': 'Academia Frider · Trilha 2, aula 1'},
        ]},

    # 2.3 — Conversas (3:25)
    'conversas': {
        'duracao': 205.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 2 · Aula 3',
             'titulo': 'Conversas',
             'sub': ['WhatsApp, inteligência artificial', 'e o momento em que você assume.']},
            {'t': 10.0, 'tipo': 'tela', 'secao': 'O módulo Conversas',
             'titulo': 'Onde o WhatsApp vira trabalho', 'print': 'conversas-chat'},
            {'t': 22.0, 'tipo': 'contraste', 'secao': 'Quem faz o quê',
             'esquerda': {'rotulo': 'Agentes de IA do hub', 'titulo': 'Atendem', 'manda': True,
                          'linhas': ['Recepção e triagem no WhatsApp.']},
             'direita': {'rotulo': 'Claude', 'titulo': 'Não atende',
                         'linhas': ['Em nenhuma hipótese.', 'São esteiras separadas.']}},
            {'t': 40.0, 'tipo': 'frase', 'secao': 'A pausa da IA', 'corpo': 46,
             'linhas': ['Ao responder à mão, a IA pausa —', 'de propósito, para não atropelar você.'],
             'rodape': '“O robô parou de responder” quase sempre é só falta de reativar.'},
            {'t': 66.0, 'tipo': 'contraste', 'secao': 'A janela de 24 horas',
             'esquerda': {'rotulo': 'Dentro de 24h', 'titulo': 'Texto livre', 'manda': True,
                          'linhas': ['Escreva normalmente.']},
             'direita': {'rotulo': 'Fora de 24h', 'titulo': 'Só modelo aprovado',
                         'linhas': ['Texto livre NÃO é entregue —', 'e você não é avisado.',
                                    'O modelo reabre o contato.']}},
            {'t': 111.0, 'tipo': 'lista', 'secao': 'Número oficial', 'titulo': 'Por que nunca o pessoal',
             'itens': ['O histórico não entra no hub',
                       'O escritório perde o controle do atendimento',
                       'Se a pessoa sai, o cliente vai junto'], 'aceso': None},
            {'t': 133.0, 'tipo': 'frase', 'secao': 'Alerta', 'corpo': 50,
             'linhas': ['Disparo em massa é proibido.'],
             'rodape': 'Já custou um número banido ao escritório.'},
            {'t': 142.0, 'tipo': 'lista', 'secao': 'Recursos do chat',
             'titulo': 'O que o chat resolve por você',
             'itens': ['Atalhos de resposta pronta', 'Enviar contato e documento',
                       'A IA lê e transcreve áudio e arquivo'], 'aceso': None},
            {'t': 168.0, 'tipo': 'frase', 'secao': 'Cadastro', 'corpo': 46,
             'linhas': ['Vincule pelo contato, nunca pelo nome.'],
             'rodape': 'Homônimo mistura processo de gente diferente.'},
            {'t': 188.5, 'tipo': 'frase', 'secao': 'A métrica', 'corpo': 58,
             'linhas': ['Responder no mesmo dia.'],
             'rodape': 'Sem resposta pronta? Avise que está apurando — mas responda.'},
        ]},

    # 3.1 — O que o Claude é (3:27)
    'o-que-e': {
        'duracao': 207.0,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 3 · Aula 1',
             'titulo': 'O que o Claude é aqui',
             'sub': ['E, principalmente,', 'o que ele não é.']},
            {'t': 16.5, 'tipo': 'lista', 'secao': 'O que ele faz', 'titulo': 'O Claude',
             'itens': ['Monta peça sobre as nossas bases', 'Pesquisa jurisprudência',
                       'Lê documento e extrai dado', 'Revisa peça pronta'], 'aceso': None},
            {'t': 39.0, 'tipo': 'lista', 'secao': 'O que ele NÃO é', 'titulo': 'Quatro limites',
             'itens': ['Não é advogado — a OAB na peça é sua',
                       'Não é fonte — jurisprudência se confere no tribunal',
                       'Não substitui a leitura dos autos — ele só lê o que subiu',
                       'Não decide estratégia, tese, pedido nem valor'], 'aceso': None},
            {'t': 78.5, 'tipo': 'frase', 'secao': 'A regra de ouro', 'corpo': 58,
             'linhas': ['Se existe skill para a tarefa,', 'a skill manda.'],
             'rodape': 'Improvisar é proibido.'},
            {'t': 100.0, 'tipo': 'frase', 'secao': 'Por quê', 'corpo': 44,
             'linhas': ['Cada regra foi escrita', 'depois de um erro medido em peça real.'],
             'rodape': 'As instruções blindam hoje contra as falhas de ontem.'},
            {'t': 112.0, 'tipo': 'lista', 'secao': 'As quatro proibições',
             'titulo': 'Não se faz, nunca',
             'itens': ['Escrever script próprio para o que a skill já resolve',
                       'Pular passo achando o caso simples',
                       'Inventar regra nova de forma ou estrutura',
                       'Trocar de ferramenta no meio sem reler a skill'], 'aceso': None},
            {'t': 152.0, 'tipo': 'lista', 'secao': 'Antes de entregar',
             'titulo': 'A conferência é humana',
             'itens': ['Ler a skill inteira antes de tocar no arquivo',
                       'Comparar com a base daquela família de peça',
                       'Rodar a revisão, quando existir'], 'aceso': None},
            {'t': 176.0, 'tipo': 'frase', 'secao': 'O ponto crítico', 'corpo': 44,
             'linhas': ['“Aplicado com sucesso”', 'não é verificação.'],
             'rodape': 'A mensagem diz que rodou — não que ficou certo.'},
            {'t': 196.0, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 48,
             'linhas': ['Uma pergunta custa uma linha.', 'Um palpite custa uma peça refeita.'],
             'rodape': 'Academia Frider · Trilha 3, aula 1'},
        ]},

    # 4.1 — Como o prazo chega até você (2:49)
    'como-chega': {
        'duracao': 169.2,
        'cenas': [
            {'t': 0.0, 'tipo': 'abertura', 'etiqueta': 'Trilha 4 · Aula 1',
             'titulo': 'Como o prazo chega',
             'sub': ['O tema em que erro custa mais caro.']},
            {'t': 15.7, 'tipo': 'lista', 'secao': 'De onde vem', 'titulo': 'Quatro fontes',
             'itens': ['DJEN — a principal, lida todo dia pelo hub',
                       'Portal do tribunal', 'Projudi',
                       'Oficial de justiça ou carta'], 'aceso': None},
            {'t': 43.0, 'tipo': 'frase', 'secao': 'A armadilha do ponteiro', 'corpo': 46,
             'linhas': ['Ato cego: houve algo ali', 'e ninguém sabe o quê.'],
             'rodape': 'Um quarto das publicações não traz o teor. Abra os autos hoje, não amanhã.'},
            {'t': 64.4, 'tipo': 'frase', 'secao': 'A armadilha do portal', 'corpo': 92,
             'linhas': ['10 dias'],
             'rodape': 'Intimação não aberta é lida em 10 dias corridos. Quem acumula descobre o prazo já correndo.'},
            {'t': 92.0, 'tipo': 'contraste', 'secao': 'Máquina e pessoa',
             'esquerda': {'rotulo': 'O classificador', 'titulo': 'Organiza',
                          'linhas': ['Lê o teor, identifica o ato,', 'calcula o prazo, cria a agenda',
                                     'e move o card.']},
             'direita': {'rotulo': 'Você', 'titulo': 'Decide', 'manda': True,
                         'linhas': ['Abre os autos.', 'Conhece a estratégia.',
                                    'Resolve de quem é o prazo.']}},
            {'t': 139.9, 'tipo': 'tela', 'secao': 'A rotina',
             'titulo': 'Todo dia, a semana inteira', 'print': 'agenda-semana'},
            {'t': 155.6, 'tipo': 'frase', 'secao': 'Fecho', 'corpo': 54,
             'linhas': ['O prazo se confere na agenda.'],
             'rodape': 'Academia Frider · Trilha 4, aula 1'},
        ]},
}
